### ISSUE TITLE
Resolver generation using graphql-code-generator

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#100]
## Goals
- Reformating resolvers from older pattern to use `graphql-codegen` version `1.0.0`
- Matching resolvers to schema definition generated. Current implementation missing a lot of stuff.

**Comment by ankitjena** [comment]
From what we discussed about using one generator to build a inputContext a major things to notice is that schema and resolvers need quite different output. We need just the types and the fields from the model file in schema whereas in resolvers we need fields of all object definitions and interface to create resolvers upon like Pagination or <some>Filter or Query for example. Don't see how that will work out.

We would have to also resolve on all the interfaces and objects, so creating a context object which will have fields and their return types which will be fed implementations to what type the user wants.

@wtrocki Not sure about things, Can you provide some more info?

**Comment by wtrocki** [comment]
Key was to see if the output is the same or different. I think there is no problem to have 2 separate generators one dedicated for schema and one for resolvers.

> Don't see how that will work out.

So let's forget about common generator and use individual generators for schema and resolvers. 

Side question: 
Do we have any problem with not being able to build dedicated target object for resolvers? Anything that will be really hard to extract using visitor?


Reference #83

**Comment by ankitjena** [comment]
What's the ideal structure for target object.
```
interface Type {
   name: string,
   fields: Field[]
}

interface Field {
  name: string,
  returnType: Type(enum having all return types)
}
```

**Comment by ankitjena** [comment]
@wtrocki What would be the ideal structure for the target object. with types and their fields and return types.

**Comment by wtrocki** [comment]
@ankitjena Let's update info in top level issue about what we agreed on.

**Comment by ankitjena** [comment]
We decided to not use graphql-code-generator and went for a global context object using visitor pattern.
