### ISSUE TITLE
Graphback v1 Roadmap

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1012]
This is an open discussion on the road to Graphback version 1!

See https://github.com/aerogear/graphback/milestone/3

**Comment by craicoverflow** [comment]
## Model

1. Missing a `@CreatedAt` and `@UpdatedAt` directive to set timestamp values from runtime datasources.
2. [MongoDB] `db.default` `db.unique` annotations do not do anything for MongoDB as there is no migrations. These seem like something we should have in place for MongoDB.
3. If we have a `@Default` directive this could be applied to data at runtime in the CRUD Layer.
4. Remove requirement of primary key field.
4. Allow non-model object types to be fields for model types. E.g:

```gql
"""
@model
"""
type Comment {
  id: ID!
  text: String
  """
  @db.type: 'json'
  """
  metadata: CommentMetadata
}

# not a model
type CommentMetadata {
  createdAt: DateTime
  updatedAt: DateTime
  openedAt: DateTime
}
```

## API

3. `createKnexCRUDX` functions should be able to accept `Knex.Config` or `any` so that the template does not require Knex to be installed directly.
4. Should PubSub instance be optional when creating CRUD Services?

## CLI*

1. `graphback config` should not generate a blank data model if user selects no model - they probably have their own already.
2. General CLI user experience improvements.

## CRUD Spec

**XFields**

We need a separate input type for querying fields. For example `NoteFields` and `NoteInput`.

**Update Mutation**

The update mutation relies on the ID field to do the update. This presents two problems for the future:

- If a model does not have an ID field, the update cannot be performed
- The current approach is very limited and people would have to write their own custom update resolvers for scenarios other than updating by ID field.

Proposed spec change:

`updateNote(where: NoteFields, input: NoteInput)`

This change would allow the user to update multiple items by a matching criteria; For example if somebody wants to set all notes from `published: false` to `published: true` where created > 3 days ago.

This would make a much more useful standard Update resolver.

**Delete Mutation**

The exact same logic as **Update Mutation** can be applied to delete mutations.

```
`deleteNote(where: NoteFields)`
```

`fields` input variable should be changed to `filter` or `where`. Fields does not make sense for what it is used for.

- user defined crud queries in data model will override generated CRUD queries in final schema, without specifying """crud.x: false""". Do we want this? Let's discuss.

## graphql-migrations

- graphql-migrations assume all object types in the model are database tables and creates them all.

**Comment by craicoverflow** [comment]
> Putting down my thoughts from researching and testing Graphback functionality:
> 
> ## Model
> 1. Missing a `@CreatedAt` and `@UpdatedAt` directive to set timestamp values from runtime datasources.
> 2. [MongoDB] `db.default` `db.unique` `db.index` annotations do not do anything for MongoDB as there is no migrations. These seem like something we should have in place for MongoDB.
> 3. If we have a `@Default` directive this could be applied to data at runtime in the CRUD Layer.
> 4. Remove requirement of primary key field.
> 5. Allow non-model object types to be fields for model types. E.g:
> 
> ```graphql
> """
> @model
> """
> type Comment {
>   id: ID!
>   text: String
>   """
>   @db.type: 'json'
>   """
>   metadata: CommentMetadata
> }
> 
> # not a model
> type CommentMetadata {
>   createdAt: DateTime
>   updatedAt: DateTime
>   openedAt: DateTime
> }
> ```
> 
> 1. Add a """@field.ignore""" or similar which does not add a field to query-able fields input:
> 
> ```
> ""@model"""
> type User {
>   id: ID!
>   name: String
>   """
>   @field.ignore
>   """
>   password: String
> }
> ```
> 
> generates:
> 
> ```
> input UserFields {
>   id: ID
>   name: String
> }
> ```
> 
> ## API
> 1. `createKnexCRUDX` functions should be able to accept `Knex.Config` or `any` so that the template does not require Knex to be installed directly.
> 2. Should PubSub instance be optional when creating CRUD Services?
> 
> ## CLI*
> 1. `graphback config` should not generate a blank data model if user selects no model - they probably have their own already.
> 2. General CLI user experience improvements.
> 
> ## CRUD Spec
> **XFields**
> 
> We need a separate input type for querying fields. For example `NoteFields` and `NoteInput`.
> 
> **Update Mutation**
> 
> The update mutation relies on the ID field to do the update. This presents two problems for the future:
> 
> * If a model does not have an ID field, the update cannot be performed
> * The current approach is very limited and people would have to write their own custom update resolvers for scenarios other than updating by ID field.
> 
> Proposed spec change:
> 
> `updateNote(where: NoteFields, input: NoteInput)`
> 
> This change would allow the user to update multiple items by a matching criteria; For example if somebody wants to set all notes from `published: false` to `published: true` where created > 3 days ago.
> 
> This would make a much more useful standard Update resolver.
> 
> **Delete Mutation**
> 
> The exact same logic as **Update Mutation** can be applied to delete mutations.
> 
> ```
> `deleteNote(where: NoteFields)`
> ```
> 
> `fields` input variable should be changed to `filter` or `where`. Fields does not make sense for what it is used for.
> 
> * user defined crud queries in data model will override generated CRUD queries in final schema, without specifying """crud.x: false""". Do we want this? Let's discuss.
> 
> ## graphql-migrations
> * graphql-migrations assume all object types in the model are database tables and creates them all.
> 
> ## Other
> * If we changed the resolver functions from:
> 
> ```ts
> findAllUsers: (parent, args, context) => {
>   return context.User.findAll(args)
> },
> ```
> 
> to:
> 
> ```ts
> findAllUsers: (parent, args, { models }) => {
>   return models.User.findAll(args)
> },
> ```
> 
> Then it will make it easier for the user to define a fully-typed Context interface in their application, like:
> 
> ```ts
> export interface Context {
>   models: CRUDContext;
>   req: any;
>   res: any;
>   db: Knex;
> }
> 
> interface CRUDContext {
>   [modelName: string]: CRUDService
> }
> 
> ...
> 
> const services = createKnexPGCRUDRuntimeServices(models, schema, db, pubSub)
> 
> const server = new ApolloServer({
>   typeDefs,
>   resolvers,
>   context: context => ({
>     ...context,
>     db,
>     models: services
>   })
> })
> ```
> 
> `models.ts` should not be generated in the resolvers folder. This makes it hard for users to import the entire folder with `loadResolversFiles` from graphql-toolkit.

**Comment by craicoverflow** [comment]
@craicoverflow review this

**Comment by craicoverflow** [comment]
A lot of this done, I will close it and we can create a revised roadmap issue

**Comment by craicoverflow** [comment]
Instead of creating another issue that will go out of date, we can just reference https://github.com/aerogear/graphback/milestone/3

**Comment by wtrocki** [comment]
Amazing idea! THx
