### ISSUE TITLE
Connect create-graphql to graphback ecosystem

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1019]
Use CLI init capabilities. 
Add generate and DB to template scripts. 
Build more production-ready template

Old repository: https://github.com/graphql-community/create-graphql

**Comment by machi1990** [comment]
Related to https://github.com/aerogear/graphback/issues/1624. See the issue for context and discussion.

**Comment by machi1990** [comment]
Now that we have `create-graphback`, what's the plan with this?

/cc @craicoverflow @wtrocki

**Comment by craicoverflow** [comment]
We discussed postponing any changes to this tool until after Graphback v1 was released. If you look at it it is actually a very comprehensive code generator.

**Comment by machi1990** [comment]
Cool, thanks. Let's keep this issue around.
