### ISSUE TITLE
[Model] Models should not require an ID field

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1021]
Each model must specify an `id: ID` field for migrations and runtime to work.

This requirement should be removed so that many-to-many models can be created in the datamodel.

The datasources check for an ID field aswell, we need to adapt the database mapping to account for composite primary keys.

**Comment by wtrocki** [comment]
#543 Should be done before starting this isse

**Comment by craicoverflow** [comment]
> #543 Should be done before starting this issue

Won't this issue enable #543 to work by default?

**Comment by wtrocki** [comment]
@craicoverflow I do not think that it will be even possible to map many2many the way we pointed out if the #543 issue. We need to check it first before applying non ID case and making our codebase more complex and possibly introduce couple corner cases etc. Let's do less work - if we figured out that we cannot do many2many without ID then we can always prioritize this issue.
