### ISSUE TITLE
[Model] Allow non-model object types to be fields for model type

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1022]
It should be possible to have a field on a model map to a non-model type, for scenarios like JSON field in Postgres and MongoDB.

```gql
"""
@model
"""
type Comment {
  id: ID!
  text: String
  """
  @db.type: 'json'
  """
  metadata: CommentMetadata
}

# not a model
type CommentMetadata {
  createdAt: DateTime
  updatedAt: DateTime
  openedAt: DateTime
}
```

**Comment by craicoverflow** [comment]
@craicoverflow check for dupes

**Comment by craicoverflow** [comment]
cc @machi1990 @wtrocki

**Comment by machi1990** [comment]
This looks similar to https://github.com/aerogear/graphback/issues/1432 which was  fixed by https://github.com/aerogear/graphback/pull/1433.
