### ISSUE TITLE
[Schema] Separate input types for query fields and mutation fields

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1024]
Currently only a single input type is generated for each model and this is used for queries and mutations. This assumes all fields are non-required to be able to cater for both cases.

We need to generate a separate `<ModelName>Fields` input type specifically for queries, and update the `<ModelName>Input` input type to map the required constraint from the model.

**Comment by wtrocki** [comment]
We should have input types that actual match the require fields etc. to enable better validation

We should have 2 input types:

Used for filtering (without required fields)
Used for mutations (with required fields same as in original type)

Closing https://github.com/aerogear/graphback/issues/844 as duplicate

**Comment by craicoverflow** [comment]
```gql
type Note {
  id: ID!
  title: String
  description: String!
}
```

Two input types are generated:

```gql
type NoteData {
  id: ID # not required as this can be auto-generated
  title: String
  description: String!
}

type NoteFilter {
  id: ID
  title: String
  description: String
}
```

`NoteData` respects the required level of the fields - except for ID. This is because ID can be an auto-generated field and the input type is used for both update and create mutations. Updates require the ID for updating an item by its ID. Creates do not require IDs as they can be auto-generated by the database.

One solution for this is to have a separate input type for create and update mutations, but when we action https://github.com/aerogear/graphback/issues/1031 the CRUD Spec will change again anyway, so that update mutations would accept two types:

`updateNote(filter: NoteFilter!, data: NoteData!)`

At this point ID can be commpletely removed from NoteData as it would no longer be used.

**Comment by craicoverflow** [comment]
Outdated by https://github.com/aerogear/graphback/issues/1031
