### ISSUE TITLE
[CLI] Graphback CLI improvements

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1026]
The Graphback CLI experience could be improved with more clear instructions and more syntax highlighting.

This is really minor - we should just make our CLI experience consistent. For example we are using syntax highlighting in some places to indicate a command to run, but other times it is just in quotes like "graphback generate".

**Comment by wtrocki** [comment]
I think it will need more info. From my point of view we might no longer need to print instructions after generate - as there are numerous flows and commands. 

We should also call out generate being called from the `yarn generate`

**Comment by craicoverflow** [comment]
`yarn generate` will only work for prebuilt templates that have `"generate": "graphback generate"` script in the `package.json` file. Then should we also have a a script for `graphback db|openapi`?

**Comment by craicoverflow** [comment]
> I think it will need more info. From my point of view we might no longer need to print instructions after generate - as there are numerous flows and commands.

This issue is just to review the CLI experience to ensure that the flow is helpful and consistent.

https://github.com/aerogear/graphback/issues/1043 shows that the `--templateUrl` option does not seem to work
