### ISSUE TITLE
[Resolvers] Change path of CRUD services in generated resolvers context object

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1027]
If we changed the resolver functions from:

```ts
findAllUsers: (parent, args, context) => {
  return context.User.findAll(args)
},
```

to:

```ts
findAllUsers: (parent, args, { models }) => {
  return models.User.findAll(args)
},
```

Then it will make it easier for the user to define a fully-typed Context interface in their application, like:

```ts
export interface Context {
  models: CRUDContext;
  req: any;
  res: any;
  db: Knex;
}

interface CRUDContext {
  [modelName: string]: CRUDService
}

...

const services = createKnexPGCRUDRuntimeServices(models, schema, db, pubSub)

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: context => ({
    ...context,
    db,
    models: services
  })
})
```
 
`models.ts` should not be generated in the resolvers folder. This makes it hard for users to import the entire folder with `loadResolversFiles` from graphql-toolkit.

**Comment by wtrocki** [comment]
See: https://github.com/aerogear/graphback/blob/master/packages/graphback-codegen-resolvers/src/ResolverGeneratorPlugin.ts#L15-L23

We need filename for the models.

**Comment by machi1990** [comment]
This should be fixed within the new runtime API. Right? @craicoverflow

**Comment by craicoverflow** [comment]
Yep, thought I closed this. Thank!
