### ISSUE TITLE
[ResolverGenerator] Ability to customisation location of generated `models` file

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1028]
The generated `models` file is always placed in same directory as the resolvers. This does not play nicely if someone wants to export * files in that directory as resolvers, or use `loadResolversFiles` from `graphql-toolkit`.

**Comment by wtrocki** [comment]
See: https://github.com/aerogear/graphback/blob/master/packages/graphback-codegen-resolvers/src/ResolverGeneratorPlugin.ts#L15-L23

We need filename for the models.

**Comment by craicoverflow** [comment]
> See: [/packages/graphback-codegen-resolvers/src/ResolverGeneratorPlugin.ts@`master`#L15-L23](https://github.com/aerogear/graphback/blob/master/packages/graphback-codegen-resolvers/src/ResolverGeneratorPlugin.ts#L15-L23) [](/aerogear/graphback/blob/HEAD@{2020-04-02T08:19:42Z}/packages/graphback-codegen-resolvers/src/ResolverGeneratorPlugin.ts#L15-L23)
> 
> We need filename for the models.

filename for the model would still place the file in the same directory as the resolvers file though. I think it should by default be generated elsewhere like `src/models` or something. It is not a resolver and so should not be in the resolvers folder.

**Comment by craicoverflow** [comment]
There is the potential for this issue to be obsoleted by https://github.com/aerogear/graphback/issues/1059 - since the model context file is not used by resolvers and so might movec completely to a new ModelGeneratorPlugin. See https://github.com/aerogear/graphback/issues/1059#issuecomment-610815496

**Comment by craicoverflow** [comment]
Resolver code generation is gone
