### ISSUE TITLE
Add more generic CRUD capabilities

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1031]
### Overview

The Graphback CRUD Specification defines a simplistic set of CRUD capabilities.

These are fine in very basic CRUD scenarios, but people usually want to perform CRUD operations based on certain filters or criteria.

### Querying

Add support for common filtering capabilities (WHERE clause), grouping, ordering

#### Get a single record by its primary key

```graphql
getTask(id: ID!): Task
```

#### Get multiple records

We can fetch all or a subset of records from a single query. The previous CRUD specification had a `findAllTasks` and `findTasks` query but these can be combined into one (so we will drop findAll).

```graphql
findTasks(filter: TaskFilterInput, orderBy: TaskOrderByInput, limit: Int, offset: String): TaskResultList
```

Each scalar in the model is mapped to a scalar input for querying:

```graphql
input TaskFilter {
  id: IDInput
  title: StringInput
  content: StringInput
  price: IntInput
  rating: FloatInput
  createdAt: DateTimeInput
  and: [TaskFilterInput]
  or: [TaskFilterInput]
  not: TaskFilterInput
}
```

You can refer to [schemaDefinitions](https://github.com/aerogear/graphback/blob/f04f723b920a215792faf9bd64e8b7677b9996f6/packages/graphback-codegen-schema/src/definitions/schemaDefinitions.ts) where these types are defined.

The returned type is a wrapper type with the list of items and pagination details:

```graphql
type TaskListResult {
  items: [Task]!
}
```

## Mutations

```graphql
""" Represents Input for the create """
input CreateCommentInput {
  id: ID
  title: String!
  description: String!
}

""" Represents Input for the update/delete """
input CommentMutateInput {
  id: ID!
  title: String
  description: String
}

type Mutation {
  likeNote(id: ID!): Note!
  createNote(input: NoteCreationInput!): Note!
  updateNote(input: NoteMutationInput!): Note!
  deleteNote(input: NoteMutationInput!): Note!
}
```
## Subscriptions

```graphql
""" Represents object filter used for subscriptions """
input NoteSubscriptionFilter {
  someid: ID
  title: String
  description: String
}

type Subscription {
  newNote(filter: NoteSubscriptionFilter): Note!
  updatedNote(filter: NoteSubscriptionFilter): Note!
  deletedNote(filter: NoteSubscriptionFilter): Note!
}
```

**Comment by wtrocki** [comment]
The challenge here will be to asses the permission model. 
A typical scenario for the data processing is that user gets his projection of the data that can operate on and then this data is replicated to the server - thus why we have update, delete based on ID.

**Comment by craicoverflow** [comment]
Yes this could require a set of directives or annotations making the datamodel complex to manage.

**Comment by wtrocki** [comment]
This could work this way but it will also mean that we no longer can work with hasRole on the operation level and need some form of ACL that brings operation type and resource name into the game (which also can be tricky to replicate on the model)

This also complicates data sync implementation. 
I might sound trivial but we also should check what our other friends are doing in terms of those types of filtering and add more info here. 

Challenge here is to give users more features while not compromise other features or complicate entire implementation.

**Comment by craicoverflow** [comment]
I actually agree now that it was explained in these terms that our CRUD libraries should not be for handling complex CRUD conditionals.

**Comment by wtrocki** [comment]
I think this issue requires investigation of how other GraphQL tools written for different languages doing it. Ruby Python etc.

**Comment by craicoverflow** [comment]
With the possibility to extend CRUDServices it should become more advantageous to add more generic CRUD operations, since any concerns about things like Auth can be handled in the model-specific CRUDService extensions.

See https://github.com/aerogear/graphback/issues/1059

**Comment by wtrocki** [comment]
Yes!

**Comment by lastmjs** [comment]
Hey, I just wanted to chime in. I think it is crucial to have more powerful filtering capabilities. The basic CRUD operations are nice, but not sufficient for anything more than a trivial application that probably can't do much in a production situation. Prisma had a really nice set of basic filtering capabilities. I'm running into this problem right now with the app I'm building with graphback, and I'm going to have to leave graphback and drop down into raw SQL queries.

Imagine a model like this:

```graphql
type User {
  id: ID!
  age: Int!
}
```

I would expect to be able to filter users by age, like this:

```graphql
query {
  findUsers(fields: {
    age_gt: 18
  }) {
    id
  }
}
```
I would like to be able to do things like `age_gt`, `age_lt`, `age_eq`, `age_neq`, etc. 

I'm not sure why permissions are a critical concern here, since the schema that graphback generates is mostly orthogonal to permissions (or should be as I see it). Each permissions framework will need to figure out how to deal with whatever graphback generates, right? I just don't know if it's a good idea to limit graphback's design based on a singular implementation of a permissions framework, since there will be many.

**Comment by craicoverflow** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Graphback] New CRUD specification](https://trello.com/c/P9nwQRgz/62-graphback-new-crud-specification)

**Comment by wtrocki** [comment]
I have updated schema based on current progress.

**Comment by wtrocki** [comment]
MErged to master with release happening soon. 🎊

**Comment by craicoverflow** [comment]
Closing. Merged and will release along with new runtime API!
