### ISSUE TITLE
Support GraphQL v15

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1065]
It looks like Graphback has some incompatibilities with [GraphQL-JS v15](https://github.com/graphql/graphql-js/releases/tag/v15.0.0)

```
src/relationships/RelationshipMetadataBuilder.ts(115,9): error TS2739: Type '{ name: string; description: string; type: GraphQLNonNull<GraphQLNullableType>; args: undefined[]; extensions: undefined[]; }' is missing the following properties from type 'GraphQLField<any, any, { [key: string]: any; }>': isDeprecated, deprecationReason
src/relationships/RelationshipMetadataBuilder.ts(128,9): error TS2739: Type '{ name: string; description: string; type: GraphQLOutputType; args: undefined[]; extensions: undefined[]; }' is missing the following properties from type 'GraphQLField<any, any, { [key: string]: any; }>': isDeprecated, deprecationReason
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wtrocki** [comment]
v15 is breaking version and due to our cli containing the GraphQL, we should hold with updating until the wider industry adapts it. Actuall work is not blocked and we can create PR or investigate how to this it.

**Comment by craicoverflow** [comment]
Bumping this one. v15 is not compatible with how we build relationships but if that is all that is broken it should be easy enough to support v15

**Comment by wtrocki** [comment]
This is both urgent and both problematic. Flagging as topic for backlog refinement

**Comment by craicoverflow** [comment]
graphback-cli has `graphql` as a direct dependency. For the CLI, is it just a matter of making it a peerDependency and removing it as a direct dependency?

```json
"peerDependencies": {
  "graphql": "15.1.0"
}
```

**Comment by wtrocki** [comment]
Yes. We need to:

- Ensure that init works without graphql (I believe it does)
- Ensure that we can install cli without graphql 
- Ensure that cli will print info for the generate command if executed globally (not from the project)

**Comment by craicoverflow** [comment]
> Ensure that init works without graphql (I believe it does)

Yep it works fine without init.

The problem is that `init` is one subcommand of the CLI package - the `openapi` package uses `graphql`.

What we could do it split the CLI:

```sh
`@graphback-cli/init`
`@graphback-cli/openapi`
```

> Ensure that cli will print info for the generate command if executed globally (not from the project)

Hmm, are we keeping the `generate` command? Looks like it is broken also (depends on config file.

```sh
graphback generate
<b>Generation failed: ConfigNotFoundError: GraphQL Config file is not available in the provided config directory: /home/ephelan/code/playground
Please check the config directory.</b>
```

**Comment by wtrocki** [comment]
Let's remove OpenApi package then. It was done to demo stuff and it is not providing any value than using upstream OpenAPiToGraphql

**Comment by wtrocki** [comment]
Generate command needs to be there for the moment as we need to generate client side queries.

**Comment by craicoverflow** [comment]
> Generate command needs to be there for the moment as we need to generate client side queries (and we can still generate schema for the time being for preview purposes)

Ah yes - I will create an issue because it is broken.
