### ISSUE TITLE
Removing types in model does not have any effect in the generated schema

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1074]
Hey! I'm finally getting a chance to try graphback out on a project.

One of the first problems I am seeing is that if I comment out or entirely remove types in my model, those types are not removed from the generated schema.

I generated an initial model with the Note example. I then put in my own types and commented out the Note and Comment examples, and the schema did not change. I removed Note and Comment entirely and the schema still didn't change.

**Comment by lastmjs** [comment]
Also, I just found out that removing fields also has no effect

**Comment by wtrocki** [comment]
@lastmjs there must me something here that I do not understand. I tried example and in fact types are removed. In fact if they are not in the model where they could come from? 

We do not remove files we just override them with the new content so if config was changed then old schema and resolver files are still there

**Comment by wtrocki** [comment]
I do see this happening with client-side generated queries (where we decided to not remove any files that user might have put there so if there is something missing in model we do not know if devs added their own queries or it was generated so manual cleanup is needed.

**Comment by wtrocki** [comment]
I have done tests using the latest release and also the current master. Both cases schema has removed old objects as they are simply gone:
 
![Screenshot 2020-04-08 at 20 00 22](https://user-images.githubusercontent.com/981838/78822815-9b5f5d00-79d3-11ea-9cda-cf082404ad3c.png)

Removing `model` from specific type is going to remove all methods but still going to put this type inside result schema (which is valid)

**Comment by lastmjs** [comment]
I can confirm this behavior happens to me over and over again. I did change the locations of the model and schema, perhaps that has something to do with it? Here is my `.graphqlrc.yml`:

```graphql
## GraphQL Config Generated by Graphback
## Please review configuration and adjust it for your own project
schema: ./backend/schema/*.graphql
extensions:
  graphback:
    model: ./backend # TODO I am not sure why this is a directory, shouldn't it point to a file?
    crud: # TODO I wonder if these should all just be enabled by default?
      create: true
      update: true
      findAll: true
      find: true
      delete: false
      subCreate: false
      subUpdate: false
      subDelete: false
    plugins:
      graphback-schema:
        format: graphql
        outputPath: ./backend/schema
      graphback-resolvers:
        format: ts
        outputPath: ./backend/resolvers
  dbmigrations:
    client: pg
    connection:
      host: ${SS_DB_HOST}
      port: ${SS_DB_PORT}
      database: ${SS_DB_NAME}
      user: ${SS_DB_USERNAME}
      password: ${SS_DB_PASSWORD}
```
So I'm putting everything inside of a directory called `backend`. My model file is called `model.graphql`. Removing anything from `backend/model.graphql` does not change the schema file generated and stored in `backend/schema/schema.graphql`.

**Comment by wtrocki** [comment]
As pointed in other issues model is missconfigured. Current release requires model to point to folder that has only GraphQL files but not output schema

**Comment by wtrocki** [comment]
We did know that this field is confusing to people and improved it by explicitly adding regegexps to default config 

https://github.com/aerogear/graphback/pull/1067

**Comment by lastmjs** [comment]
Ah, okay. So I will be able to put the path to an explicit file? Even with being able to do that, it's confusing that putting the model in a directory that might have a schema somewhere in a child directory would cause removals to just not work

**Comment by wtrocki** [comment]
Generally model folder should not be changed unless you have some extra use cases.. All our templates contain model folder already and Graphback config generates model and the right config. The issue happens when model config will be missconfigured and also contain output schema - this will cause havoc as we will try to merge the same types. I think we can easily detect it and show error to user.

**Comment by lastmjs** [comment]
Awesome, thank you. Though I don't think the project should try to impose too many restrictions on the folder/file structure. I can see this leading to rigidity and things breaking, like we're seeing in this case. The freedom to place things where we want (within reason) I think is very important.

**Comment by wtrocki** [comment]
That is why we have model configuration (previously it was hardcoded model folder) that people can configure, however if somehow output schema will be put as input results could be disastrous (especially on the database front). 

While this is not critical issue (requires misconfiguration) we will definitely address it in the near future. Thank you so much for reaching out and improving Graphback!

**Comment by craicoverflow** [comment]
This is done
