### ISSUE TITLE
Allow overriding fields in model

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1075]
Here's my original model:

```graphql
""" @model """
type User {
  """@db.primary"""
  publicAddress: String!
}
```

I am trying to change it to the following:

```graphql
""" @model """
type User {
  """@db.primary"""
  publicAddress: ID!
}
```

Running `graphback generate` gives me the following error:

```bash
Generation failed: Error: Unable to merge GraphQL type "User": Field "publicAddress" already defined with a different type. Declared as "ID", but you tried to override with "String"
```

Overriding types is common and I think this should be supported. Also, the error itself seems incorrect. I believe I declared it as a `String!` first, but it says I declared it as `ID`.

**Comment by wtrocki** [comment]
Error is related to wrong config. I think we got inception where we trying to use output schema as input schema
```
model: ./backend # TODO I am not sure why this is 
```

This is the most important folder that points to the location of model. it should not be pointed to server as it will load your generated schema as well. This caused numerous issues with migrations you have seen

**Comment by lastmjs** [comment]
Yep! Closing this in favor of: https://github.com/aerogear/graphback/issues/1074
