### ISSUE TITLE
Performance suite for large schemas

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1080]
We need to build simple test that will measure performance impact of the large schema (more than 100 types generated by graphback).
What we looking for is just simple comparison of request times 

## Graphback test suite

Small schema (10types)
Large schema (100types)

Compare number of requests that application can made for this schemas. 

CC @martinhesko @mmusil

**Comment by danielrearden** [comment]
Ben Awad's [benchmarks repo](https://github.com/benawad/node-graphql-benchmarks) might be a good start for this. FWIW, I recently [forked](https://github.com/danielrearden/node-graphql-benchmarks) it and modified it so the benchmark schema could be extended with an arbitrary number of additional types. There's definitely a difference in latency, but even at 1000 types, I don't know if I would call it a big difference. I ran the benchmarks with both a small query (the original one in the repo) and a big one (same query but aliased 10 times). Results [here](https://pastebin.com/a8d3eLQ0). You can see that the query size is a much bigger factor in performance. Running it with 1000 extra Query fields also didn't see a huge impact.

**Comment by wtrocki** [comment]
I have seen that benchmark and do not particularly like how certain things were done there.

Our use cases are extreme in terms of the size of the objects that schema has that maps to complex InputTypes and generic queries that can evaluate on non indexed fields. 

Ideally, we will like to keep the benchmark in the repository as we do not need to compare it much with other solutions. 
If we will see significant impact on query sizes we will start compiling client side queries like Relay or Apollo suggests.

Data layer is mostly knex so that is not something that we might control that much - all depends on how many indexes will be applied on the schema

**Comment by martinhesko** [comment]
Any idea on what would be a good way to generate some mock data so I have something to query?

My first idea would be to just shoot POST requests at the server with `createX`mutations filled wtih some random data, but there's a probably a better way of going about it that I haven't figured out.

**Comment by wtrocki** [comment]
MongoDump/Restore can be used. Script that will populate it is better IMHO.
https://www.npmjs.com/search?q=mongorestore

**Comment by martinhesko** [comment]
Can anyone more experienced with graphQL give me advice on how to use a package such as [wait-on](https://www.npmjs.com/package/wait-on) to check if the server is ready to handle requests?

I feel like the majority of the work is done and the test-suite works if I have a server started beforehand, I'm just having trouble figuring out when it's started and ready to handle queries if I start it as a part of my test-suite.

**Comment by martinhesko** [comment]
Also here's a sneak peek of the results I got so far :smile: 
![image](https://user-images.githubusercontent.com/4204162/85714792-0f63f400-b6eb-11ea-8fb3-4408294c1d00.png)

**Comment by wtrocki** [comment]
Startup time is important as well. Can we measure time when server starts

**Comment by wtrocki** [comment]
As for waiton. This is not GraphQL specific. GraphQL is just yet another server middleware. Nodejs servers emit events

**Comment by wtrocki** [comment]
Throughput is quite low actually.

**Comment by martinhesko** [comment]
Quick update:
Current TODO is: 

- resolving errors that occur between postgres test cases
- adding startup time as a metric
- documentation and refactoring

You can check out my repo [here](https://github.com/martinhesko/node-graphql-benchmarks)

**Comment by wtrocki** [comment]
I'm getting amazing results on AWS cloud medium instance. 8-9mb/s. Startups bellow 1 second. 
This is slow comparing to golangs 46mb/s but it is also dependent on the database. 
We can start compiling queries, using fastify in example etc. to see the difference, but generally this is is acceptable and I do not see any bottleneck in the graphback so far. Looking forward for final results

Amazing work @martinhesko

**Comment by wtrocki** [comment]
Also worth to notice that I did seen significant difference with reduced selection set. This is compound result of @machi1990 selection set filtering and smaller documents that need to be parsed.

**Comment by martinhesko** [comment]
Today I added startup time measurement and generally the 10x increase in a number of types increases the startup time by 2-3x as you can see here.
![image](https://user-images.githubusercontent.com/4204162/87422978-dfb55700-c5d9-11ea-9408-b9c7ef393f72.png)

**Comment by wtrocki** [comment]
yep.. This is still acceptable (100 types is a lot) and we know that we can cache some of the model processing to make things faster. Mentioned by @craicoverflow 

Throughput makes me worried - this is the lowest compared to the other framework benchmarks we have seen. To have reference can you run plain Apollo benchmark from this repo to see how this works?

**Comment by wtrocki** [comment]
SQLMancer integration here can pull out more processing to generation phase so things could be faster etc.

**Comment by wtrocki** [comment]
Yes. As we see benchmark uses faker. I would love if we can create CRUDDataSource in memory the same way this guy created it here: https://youtu.be/JbV7MCeEPb8?t=283 and then compare throughput with plain APollo. This will give us overhead of graphback.

**Comment by wtrocki** [comment]
Initial performance suite was completed. Closing but feel free to reopen
