### ISSUE TITLE
Generation should base on CWD of the config file not current CWD

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1083]
When executing generate it can discover config file in the directory three.
If config specifies `outputPath:... ` in most of the cases we are going to take location of the current CWD instead of the location relative to the config file. 

Issue happens for plugins. Model works fine

**Comment by craicoverflow** [comment]
@wtrocki related to the suggestion of only allowing `graphback generate` to be executed in the same directory as the `.graphqlrc`.

That works well when the user has `graphback-cli` globally installed - but would require it to be installed at multiple levels if installing as a `devDependency` in the project. Although this does not affect the project build size, it does increase maintenance cost and lessens developer experience.

**Comment by wtrocki** [comment]
`yarn graphback generate` works on any level in https://github.com/aerogear/AtHomeCrisisCommunity. I will check NPM and let you know

**Comment by craicoverflow** [comment]
Probably because you happen to be using yarn workspaces?

**Comment by wtrocki** [comment]
Yep.. npm is not working. I can live with that.

**Comment by craicoverflow** [comment]
Can I close this? We won't be doing server generation anymore but there is still the client document generation. I understand this is moving.

**Comment by wtrocki** [comment]
Yes
