### ISSUE TITLE
Documentation for longer string types

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1093]
I can't find documentation on string types besides `String`. Apparently this is a `character varying(255)` in Postgres. Are there any longer string types available? I need to store more text than what will fit in the `String` type apparently, since I'm getting the error `value too long for type character varying(255)`.

**Comment by ssd71** [comment]
Have you tried [this](https://www.npmjs.com/package/graphql-migrations#custom-column-type)?

**Comment by wtrocki** [comment]
Yep. I think we can expose it little bit better: https://graphback.dev/docs/db/dbmigrations

**Comment by lastmjs** [comment]
Oh yes, I see now thank you. What I feel is lacking in the documentation is just one central place with all of the typing information, to see exactly what is available when creating my model

**Comment by machi1990** [comment]
This is documented here https://graphback.dev/docs/graphql-migrations/db-design#column-length
