### ISSUE TITLE
Non-model GraphQL types not included in final schema

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1112]
Mixing the datamodel with model and non-model GraphQL types loses non-model types in final schema.
If the data model contains some types that are not annotated with `@model` they are not added to the final schema.

All other custom types are lost - enums, interfaces, type extensions etc.

This model:

```gql
type User {
  id: ID!
  friends: [String!]!
}

"""
@model
"""
type UserModel {
  id: ID!
  name: String
}

interface Test {
  id: ID!
}

enum TEST {
  Test
}
```

Outputs this schema:

```gql
## NOTE: This schema was generated by Graphback and should not be changed manually

type Mutation {
  createUserModel(input: UserModelInput): UserModel!
  updateUserModel(input: UserModelInput): UserModel!
  deleteUserModel(input: UserModelInput): UserModel!
}

type Query {
  findAllUserModels(limit: Int, offset: Int): [UserModel]!
  findUserModels(fields: UserModelInput, limit: Int, offset: Int): [UserModel]!
}

type Subscription {
  newUserModel(input: UserModelInput): UserModel!
  updatedUserModel(input: UserModelInput): UserModel!
  deletedUserModel(input: UserModelInput): UserModel!
}

"""@model"""
type UserModel {
  id: ID!
  name: String
}

input UserModelInput {
  id: ID
  name: String
}

```

**Comment by craicoverflow** [comment]
After investigating this issue seems to be down to how we are using GraphQL-Compose to compose our schema.

We are using this to add extra based on our models. The only reason our models are getting added to the final schema is because the input type, queries etc contain a reference to the model types.

GraphQL-Compose generates a new schema but does not automatically merge with existing types.

See https://codesandbox.io/s/throbbing-sun-r8opj - the console log does not show the User type.

I think we can still use GraphQL-Compose, but we may need to combine it with graphql-toolkit's `mergeSchemas`.

cc @wtrocki

**Comment by wtrocki** [comment]
How about?
```
const { SchemaComposer} = require("graphql-compose");

// console.log(schema);

const schemaComposer = new SchemaComposer(  `type User {
  id: ID!
  friends: [String!]!
}
`);

console.log(schemaComposer.toSDL({ omitScalars: true }));

```
Works fine. Merge schemas other side effects. We should simply use composer effectively.

**Comment by wtrocki** [comment]
This is due to ast Vs objects problem. printSchema is actually an issue here as it bases on ast to print objects

**Comment by craicoverflow** [comment]
@wtrocki the example you provided did not work for me - unmodified custom types are not added to the schema.
