### ISSUE TITLE
Client side query generation is not working when custom requiremens are supplied

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1123]
We are generating queries by default supporting only level 2. 
Adding manually level 3 or removing level works but changes will be overridden silently later making it hard to work with client side generated content. 
We need to come up with the best way to do it.

AWS AppSync generates client-side queries - we can check how they doing it

**Comment by wtrocki** [comment]
Actually I have more into that. 
If we add more crud capabilities entire client side generation will basically stop making sense as there will be so many variation of the queries that they will need to be expressed by hand. 

I think that we might have 2 modes:
- Generate fragments only and let people use them
- Generate full crud queries (with some way to specify level per model (annotation?)

**Comment by wtrocki** [comment]
@Eunovo Would it be possible to see if we can control the instability of the queries?

**Comment by Eunovo** [comment]
> Actually I have more into that.
> If we add more crud capabilities entire client side generation will basically stop making sense as there will be so many variation of the queries that they will need to be expressed by hand.
> 
> I think that we might have 2 modes:
> 
> * Generate fragments only and let people use them
> * Generate full crud queries (with some way to specify level per model (annotation?)

What do you @wtrocki mean by "more crud capabilities"?

**Comment by wtrocki** [comment]
Hi

We are extending CRUD by adding Pagination etc.

**Comment by Eunovo** [comment]
> @Eunovo Would it be possible to see if we can control the nesting of the queries?
> I would love to see your opinion on how we can improve client side generator

We can indeed use per model annotations to specify nest levels but we can also add "include" or "skip" directives controlled by automatically generated variables to modify the structure of the query. Take a look at this example from https://graphql.org/learn/queries/

`query Hero($episode: Episode, $withFriends: Boolean!) {
  hero(episode: $episode) {
    name
    friends @include(if: $withFriends) {
      name
    }
  }
}`

**Comment by Eunovo** [comment]
So, we can use both techniques or we just use the second one and allow users to specify how deep they want to go. I'm worried about how big the query definitions will become though.

**Comment by wtrocki** [comment]
Is include supported by graphql-tag?

**Comment by Eunovo** [comment]
I conducted an experiment with @include directive

> Is include supported by graphql-tag?
yes
> Would this work on fragments?
yes
> If yes then sounds like good thing to try on.
Great! I'm also looking into the possibility of using a custom directive that accepts a variable that specifies query structure
> Our current approach is to generate 2 fragments one with no nested level and second with nested. We can ignore fragments and use inline defitionions but then it will not give much benefits for situations when you want to write queries yourself - we support fragment only mode as well. What will be the most flexible way to do so from your point of view? Let's think about it
The `@include` directive works on fragments. This allowed me to do this
```graphql
fragment NoteExpandedFields on Note {
   id
   title
   description
   comments @include(if: $withComments) {
      id
      text
      description
   }
} 

query findAllNotes($limit: Int, $offset: Int, $withComments: Boolean!) {
    findAllNotes(limit: $limit, offset: $offset, withComments: $withComments) {
      ...NoteExpandedFields
    }
 }
```
With this, I could query only notes or notes and comments with this
`allNotes.variables.withComments = true;`
The same thing could be done for custom queries, although they would have to add `$withComments` to their query definition.

**Comment by wtrocki** [comment]
@craicoverflow Any prefference on this. Include actually looks like amazing way to reduce amount of the code we will generate but it will require extra parameters when querying.

**Comment by craicoverflow** [comment]
In a realistic situation developers will probably write their own fragments anyway, because they will want some very specific fields. We can't cater for every possible combination when they will only end up using a subset of what gets generated.

Would it be possible to only generate single-level fragments and let users combine them as they they wish fore their requirements if they need go N levels deep?

```graphql
query findAllNotes($limit: Int, $offset: Int) {
  findAllNotes(limit: $limit, offset: $offset) {
    ...NoteFields
    comments {
      ...CommentFields
    }
  }
}
```

**Comment by Eunovo** [comment]
What about something like this
```ts
allNotes.variables.structure.withComments = { comments: true, someNestedModel: { anotherModel: true } };
```
This way query definition will look like this
```graphql
query someQuery($structure: NoteQuery) @customInclude {}
```
Doing this would require more generated types like `NoteQuery` and a custom directive. 
Also, some fragments could be included by default whichever system we use. For example `withComments` can be true by default.
@wtrocki What do you think?

**Comment by wtrocki** [comment]
There are a couple of things here. 
Generated fragments are actually the most useful here as they giving developers the ability to get quite lengthy queries under control. Sure you can change or remove fields that you do not need later. 

The problem here is the level of the relationships nesting and having ability to use generated client in some cases. 

I'm kinda going outside this issue, but there are couple issues with client side code in general:

1) If you made any change then next generate will silently wipe them out
2) Fragments are useful, queries when generic could be also quite useful (with the ability to make them more specialized later

If we use include we could technically give some of this out of the box by giving developers ability to include changes (not sure how we going to handle actual filtering for this data then as every relation would also gets paginated etc. 

When we expose that in one single generic find(...tons of arguments here like `withUser`, `withAddress`.. tons of filters for those relations that are parametrized. 

We know the capabilities, now it is just matter of what will be actually useful for people.

**Comment by Eunovo** [comment]
>We know the capabilities, now it is just matter of what will be actually useful for people.

We can anticipate the most common use cases and use defaults. For example, fields are currently extended to level 2; this will cover a lot of use cases. Using `include` we can include certain levels by default and make other non-essential parameters (pagination, filter, etc.) optional. 

>When we expose that in one single generic find(...tons of arguments here like withUser, withAddress.. tons of filters for those relations that are parametrized.

Are we ruling this format out?
```ts
allNotes.variables.params = { 
    comments: {
        offset?: Int, limit?: Int,  filter...
    } 
};
```

**Comment by wtrocki** [comment]
> Are we ruling this format out?

This looks like operating on compiled doc. This format will work with app but we providing framework and all we inject into client app are documents

**Comment by Eunovo** [comment]
So, what is the conclusion? Should I update the Client CRUD query generator to use `include` with all associated parameters in query definition?

**Comment by wtrocki** [comment]
Lets think about this over the weekend. I will ping you on other issues related to client side code and we will see how we can resolve that the best way

**Comment by wtrocki** [comment]
I think we need to approach it basing on crud methods.
Create, update and delete will be easy to generate. For find we can generate fairly generic findBy based on fragments.

**Comment by wtrocki** [comment]
https://github.com/aerogear/graphback/pull/1235

**Comment by craicoverflow** [comment]
Looks like this is closed, but feel free to reopen if I am wrong
