### ISSUE TITLE
Knex equvalent for MongoDB

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1129]
We are working directly with mongo driver and our code is missing basic features like indexes etc. Having some more top level interface will hide possible client incompatibilities and simplify maintenance

**Comment by wtrocki** [comment]
CC @ssd71

**Comment by wtrocki** [comment]
@ssd71 That could be very good thing to explore further

**Comment by ssd71** [comment]
[monk](https://www.npmjs.com/package/monk) also seems like a good alternative to just using mongodb-native although it lacks some of the sugar of mquery when it comes to making queries

**Comment by wtrocki** [comment]
hmm.. after exploring mquery we see that:

- it provides sugar syntax however crud handler is simple enough to handle it
- it doesn't have typings.
- it has some questionable ways to query stuff

Following some research I think we should use native mongo
