### ISSUE TITLE
Unify unit tests schema inputs

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1133]
Currently we using single mock file that is not great for general testing. We should have schema inline for each test

**Comment by craicoverflow** [comment]
https://github.com/aerogear/graphback/blob/dbc498831d241913fe9262449e1ae93a00045a1a/packages/graphback-core/tests/RelationshipMetadataBuilderTest.ts#L69

Here is an example of how we can do this cleanly with a setup method in the test file
