### ISSUE TITLE
Runtime API should have option to return `typeDefs`

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1157]
I have a usecase where I want to use `typeDefs` instead of a GraphQLSchema object in my GraphQL app.

The API returns `schema` and `resolvers`:

```ts
const { typeDefs, resolvers } = createRuntime();
```

If I want to use `makeExecutableSchema` from apollo-server I need `typeDefs`:

```ts
const { typeDefs, resolvers } = createRuntime();

const schema = makeExecutableSchema({
  typeDefs,
  resolvers
})
```

Given that the schema is completely in-memory it is important to offer this flexibility for various applications.

**Comment by wtrocki** [comment]
Even better. I do not see any use case where returning schema makes sense as it is not executable schema (it is missing directives and resolvers anyway)

**Comment by craicoverflow** [comment]
`createKnexPGCRUDRuntimeServices`

**Comment by wtrocki** [comment]
`although currently in runtime this is not attached to context it could be.`

What you mean by this?

**Comment by craicoverflow** [comment]
A user may want to use the services created by `createKnexPGCRUDRuntimeServices` in their own custom resolvers. For this they would want to attach the services to the resolver context so they would require a schema object to do this.

**Comment by wtrocki** [comment]
I think we have incorporated that. Reassigned that to yourself and closing but feel free to reopen if needed.

**Comment by craicoverflow** [comment]
Im going to keep this open until I get to it, I don't believe this is implemented.
