### ISSUE TITLE
Runtime template is incorrectly configured

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1158]
The runtime templates are using `printSchema` to convert the schema object to typeDefs:

```ts
const apolloConfig = {
  typeDefs: printSchema(schema),
  resolvers,
  playground: true,
  resolverValidationOptions: {
    requireResolversForResolveType: false
  }
}
```

`printSchema` removes directives from the schema. We should use the `schema` key instead:

```ts
const apolloConfig = {
  schema: schema
  ...
}
```

**Comment by craicoverflow** [comment]
Update: quickly swapping `typeDefs` for `schema` does not work - it looks like the resolvers are not created properly at all. Requires further thought.

Related to and possibly duplicated by https://github.com/aerogear/graphback/issues/1157

**Comment by wtrocki** [comment]
`Update: quickly swapping typeDefs for schema does not work`

Do you mean using typedefs instead of schema? 
We kinda using schema to get mapping information

**Comment by craicoverflow** [comment]
> `Update: quickly swapping typeDefs for schema does not work`
> 
> Do you mean using typedefs instead of schema?
> We kinda using schema to get mapping information so this could require some thoughts and it is not `good first issue` :)

When I created the issue I thought this could be a quick fix by replacing `typeDefs` with `schema` but that does not work.

**Comment by wtrocki** [comment]
Yes. Checked that now we need to address that by redefining how runtime works.

**Comment by wtrocki** [comment]
I think we have incorporated that. Reassigned that to yourself and closing but feel free to reopen if needed.
