### ISSUE TITLE
Runtime engine expects services as input before creating schema

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1159]
The current runtime architecture expects the dataservices to be created and passed to the engine BEFORE creating the schema.

```ts
const services = createKnexPGCRUDRuntimeServices(models, model, db, pubSub);
const runtime = runtimeEngine.buildRuntime(services);

const schema = runtime.schema;
```

This is flawed as you have to pass the initial datamodel to `createKnexPGCRUDRuntimeServices` which builds table-mapping information using the data model which could be missing key metadata or generated fields.

Relates to https://github.com/aerogear/graphback/issues/1071

**Comment by wtrocki** [comment]
I think we have incorporated that. Reasigned that to yourself and closing but feel free to reopen if needed.
