### ISSUE TITLE
Foreign keys missing?

### ISSUE THREAD

**Issue by Artimunor** [aerogear/graphback#1186]
After managing to create a valid graphql schema, and have it turned into a tableset when generating a postgres database i noticed the foreign keys are missing.
Would this not greatly impact performance in a negative way?

In order to illustrate this i have created a sample project, and checked the database with pgadmin, and made a screenshot of the constraints of the table:

![image](https://user-images.githubusercontent.com/6189700/80313677-c2e46100-87ec-11ea-8913-4fe3de91a5c9.png)

As you can see there are no foreign keys, or at least pgadmin does not detect them.

This sample project uses the same datamodel as in the previous Issue:

```typescript
""" @model """
type Library {
  id: ID!
  name: String!

  """
  @oneToMany field: 'library'
  """
  libraryBooks: [LibraryBooks]
}

""" @model """
type LibraryBooks {
  id: ID!
  numberOfBooks: Int!
}

""" @model """
type Book {
  id: ID!
  name: String!

  """
  @oneToMany field: 'book'
  """
  libraryBooks: [LibraryBooks]
}
```

**Comment by craicoverflow** [comment]
Hi @Artimunor, thanks for reporting this issue. Can I ask what version of Postgres you are using?

**Comment by wtrocki** [comment]
We need to bump templates to 0.11

**Comment by Artimunor** [comment]
> Hi @Artimunor, thanks for reporting this issue. Can I ask what version of Postgres you are using?
> 
> I tested this same data model using our fullstack template and the foreign keys are created. I am using PG 9.6
> 
> ![Screenshot from 2020-04-27 08-42-35](https://user-images.githubusercontent.com/11743717/80346920-74be7480-8863-11ea-95f9-1228b5cc04a8.png)

Hi @craicoverflow I am using version 12, will try to reproduce it with 9.6. But this seems likely the issue.

**Comment by craicoverflow** [comment]
Closing as this is resolved, foreign keys are created in Postgres 12
