### ISSUE TITLE
Update Docker PostgreSQL templates to use version 11.x

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1195]
Our Postgres Docker templates still use version 9.6. AFAIK migrations work in v11 but we should test this and bump our versions to v11.

Also, we should document what versions  of PG we support in migrations

https://graphback.dev/docs/db/dbintroduction

**Comment by machi1990** [comment]
I have not checked this part of the project yet. Interested to take this one up later today. WDYT? @craicoverflow @wtrocki

**Comment by wtrocki** [comment]
We know that this update will cause issues and also we need to know what version we have in the kube rh envs before we migrate to 12. There should be some mention on v12 on knex side that might be  blocked. This requires a lot of context to be done but it is nice to do some investigation etc.

**Comment by ThirumlaDevi** [comment]
@craicoverflow Thanks to the [contribution guidelines](https://github.com/aerogear/graphback/blob/master/CONTRIBUTING.md) I'll be able to make this change and test it. I would like to solve this issue as part of the hacktoberfest event, Can you please assign this task to me?

**Comment by craicoverflow** [comment]
Sure thing @ThirumlaDevi I have assigned you for now. Thanks!

**Comment by wtrocki** [comment]
https://github.com/sclorg/postgresql-container images to use

**Comment by ThirumlaDevi** [comment]
@wtrocki When i referred to the [link](https://github.com/sclorg/postgresql-container) PostgreSQL [versions](https://github.com/sclorg/postgresql-container#versions) other than 11.x version is supported by this repo. In reference to this [comment](https://github.com/aerogear/graphback/issues/1195#issuecomment-678235395), i believe i can still try and upgrade Postgres Docker templates to version 12.x as this version is supported by postgresql.

**Comment by wtrocki** [comment]
@ThirumlaDevi Ignore my coment use current docker image. We found that those images behave differently and it will require a lots of tests to get around.

**Comment by ThirumlaDevi** [comment]
@craicoverflow @wtrocki I have updated Docker PostgreSQL templates to use version 11.x and I have also tested the same.
I have explained this in detail in the below PR description ---> https://github.com/aerogear/graphback/pull/2154
Also can you please re-assign this task to me?

**Comment by craicoverflow** [comment]
Fixed in #2154 - thanks again @ThirumlaDevi
