### ISSUE TITLE
Production database migration

### ISSUE THREAD

**Issue by Artimunor** [aerogear/graphback#1197]
Is there a possibility to generate schema versions containing the alter table commands so that for dev and test the databases can auto-update (facilitating CI) but for production (or any env you desire) you can choose to have a set of commands generated into an SQL script instead of directly being executed on the database, so a person with deep DB knowledge can go over it and see what they like and don't like, make alterations to perhaps get in the desired database state in a more safe way.

This approach has proven very valuable in large enterprise projects, since something auto-generated is seldom unleashed on a production database containing large quantities high value information or on which many business processes depend directly.

Tools like Liquibase have been doing this with great success.
They generate a database schema based on your model, and also version it.
Then after the model changed, when you generate it a second time, it generates a second version of the database schema and in that version you can choose to generate only the commands required to go to it from a previous version.

It is also possible to generate a diff between your current code structure and the database itself. However this is considered bad practice and it is better to maintain the schema versions under version control so you don't have to compare with the database.

A good and challenging read regarding diffs is:
https://www.liquibase.org/2020/04/liquibase-diffs.html

_edit: made a more clear distinction between diffs of the model and the database versus being able to generate sql from versions and output it into a script_

**Comment by craicoverflow** [comment]
Going to close this as there was a Discord discussion at the time which I think cleared things up. Feel free to reopen!
