### ISSUE TITLE
Replace GraphQL Playground with GraphiQL in templates

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1207]
GraphQL Playground's features are being merged into GraphiQL and will only receive some maintenance and bug fix updates.

Our templates all use GraphQL Playground.

See https://github.com/prisma-labs/graphql-playground/issues/1143

Read the blog post announcing this: https://foundation.graphql.org/news/2020/04/03/web-based-graphql-ides-for-the-win-how-why-playground-graphiql-are-joining-forces/

**Comment by wtrocki** [comment]
We use Apollo Server Playground

**Comment by craicoverflow** [comment]
Ah okay :)
