### ISSUE TITLE
@defaultValue metadata to be able to specify field specific default values agnostic to database

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1241]
- the default value could be used in Input types 
- or for the `.create()` operation.

**Comment by wtrocki** [comment]
Postgress or Mongo? There is the default value for Postgres

**Comment by machi1990** [comment]
I think it should be DB agnostic. And Postgres does handle default value but I see your point hence my preference for it to be handle on the generated XxxInputType or on the resolver levels.

**Comment by craicoverflow** [comment]
I agree with you @machi1990 - this can be handled at resolver level (or CRUD layer but this might be going away).

I've documented a similar finding in https://github.com/aerogear/graphback/issues/1012#issuecomment-606562493

**Comment by machi1990** [comment]
> If this was handled at GraphQL level instead of the database it would only need to be implemented once and will work for any data source.

Agreed, thanks for the link to the comment. It is very detailed there.

**Comment by craicoverflow** [comment]
It can be db agnostic by setting the default value on the input type:

https://stackoverflow.com/a/51567429

**Comment by machi1990** [comment]
> It can be db agnostic by setting the default value on the input type:
> 
> https://stackoverflow.com/a/51567429

Yes, and it could be the clean appoach. An option I considered here https://github.com/aerogear/graphback/issues/1241#issuecomment-625375706.

**Comment by machi1990** [comment]
I'm thinking of taking this issue for a spin. 

We current have `@db.default`, should this be renamed to `@default` or `@defaultValue` following this  comment https://github.com/aerogear/graphback/pull/1396#discussion_r436640893? 

/cc @craicoverflow

**Comment by craicoverflow** [comment]
Sounds good @machi1990. I think it should be renamed to `@default(value: true)` because this is how the new metadata syntax expects the format to work. We could use `parseMarker` if you want to do `@default true`.

Although the latter is shorter, I think we should be sticking with a single annotation syntax for all metadata. This means users will not need to reference docs each time to see which one to use.

**Comment by machi1990** [comment]
> Sounds good @machi1990. I think it should be renamed to `@default(value: true)`. We could use `parseMarker` if you want to do `@default true`.
>
 
> Although the latter is shorter, I think we should be sticking with a single annotation syntax for all metadata. This means users will not need to reference docs each time to see which one to use.

+1 on sticking to one syntax. I'll give this a shot with `@default(value: <value here>)`

**Comment by craicoverflow** [comment]
Closed via #1450
