### ISSUE TITLE
Add a `notContains` filter expression

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1256]
We have a `contains` filter option, but should also add a `notContains` filter option.

The filter would look like this:

```
{
   "filter":{
      "title":{
         "notContains":"hello"
      }
   }
}
```

Relates to https://github.com/aerogear/graphback/issues/1031

**Comment by craicoverflow** [comment]
We have the `not` operator which satisfies this.

**Comment by machi1990** [comment]
> We have the `not` operator which satisfies this.

Yeap. The below examples can be of handy. 

# number not contained in the list of numbers

```graphql
{
  not: {
      id: {
        numberField: [1,3,4]
       }
    }
}
```

# string not contained in the list of strings

```graphql
{
  not: {
      stringField: {
        in: ["value","value-2","value-3"]
       }
    }
}
```


# string not containing another string 
```graphql
{
  not: {
      stringField: {
        contains: "value"
       }
    }
}
```
