### ISSUE TITLE
What I need to replace Prisma with Graphback

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1260]
I've mentioned some of these things before, but hopefully no one minds if I put them all right here. I am in the middle of a large refactor for my current employer. Prisma has caused some serious infrastructural issues, being needlessly complex. Graphback looks to be able to solve many if not all of the issues I've had with Prisma, while maintaining the benefits. The following are features that I need or want Graphback to support before being able to move away from Prisma entirely:

- [ ] Needs
  - [ ] very good performance with multiple joins (I need to test out graphback queries on production data)
  - [ ] filtering across relationships
      - [ ] https://github.com/aerogear/graphback/issues/1343
      - [ ] https://github.com/aerogear/graphback/issues/1338
      - [ ] https://github.com/graphqlcrud/spec/issues/10
  - [ ] batch updates
      - [ ] https://github.com/graphqlcrud/spec/issues/8
  - [ ] pagination and ordering for relationships in selection set
      - [ ] https://github.com/aerogear/graphback/issues/1317
      - [ ] https://github.com/graphqlcrud/spec/issues/9
  - [ ] fully functioning subscriptions, with at least simple filtering capabilities
      - [ ] https://github.com/aerogear/graphback/issues/1273
  - [x] Support existing databases without the need to run migrations (I need to use another migration system for the time being to support interop between our new system and our old Ruby on Rails system)
  - [x] More powerful CRUD (especially filtering)
    - [x] This is full CRUD support. I should only have to create custom queries or mutations in rare cases. I should be able to easily expose all of the generated CRUD queries and mutations to my frontend without graphback trying to limit me
  - [x] Many-to-many relationships (I might be able to just emulate this with a join table or something using one-to-many relationships)
- [ ] Wants
  - [ ] Subscriptions that can run on AWS Lambda (right now we have an entirely separate EC2 subsystem for subscriptions, I want to get rid of that entirely)
  - [ ] Date or DateTime type (I think I could just implement this myself for the time being)
  - [ ] Custom directives instead of annotations
  - [ ] Implicit relationships (no annotations or custom directives required)
  - [ ] Transactions
  - [ ] A plugin that implements permissions with custom directives (this one is on me)

**Comment by wtrocki** [comment]
Almost all of this is going to land in 2 next releases. Sadly we cannot let go annotations unless some strong limitation will be posted.

CRUD is going to land next release 0.14
Support for existing databases - 0.15
Many-To-Many - documented already - we going to provide more native support post 0.14
We have plugin that implements permissions already - Feel free to check this PR #1255 

We planning to do alpha release of 0.14 in comming days for testing. Really good times as all your points in 99% matching our roadmap if we forget about annotations.

Also in this release we moved from code generated resolvers to resolvers out of the box. the code ones could not be edited this were not that useful

**Comment by wtrocki** [comment]
Can I have separate issue about subscriptions - that sounds interesting and I would like to chat with the team about details. 

Technically we can disable subscriptions on one server by CRUD options and enable subscriptions but having lambda for this is something that we seen some community traction already

**Comment by lastmjs** [comment]
Serverless subscriptions issue: https://github.com/aerogear/graphback/issues/1261

**Comment by lastmjs** [comment]
I'm attempting to try out the new features with v0.14.0-dev3. I've installed graphback@0.14.0-dev3, and graphback-cli@0.14.0-dev3

Do I need to use graphback-cli@0.14.0-dev3? It doesn't seem to create an executable in the node_modules/.bin directory. When I run npx graphback-cli config, it looks like npm might be downloading and using the current released version of graphback-cli, so I'm not sure if my config is correct

**Comment by wtrocki** [comment]
We released first `0.14.0-alpha1` version today. It addresses your problems - 
- it will work with your own scalars in the project
- Brings flexible crud model (based https://graphqlcrud.org spec)

Note that we still testing and improving stuff for 0.14.0. 
We going to land things like transitions, createdAt fields etc. soon. 
Client side queries etc.

**Comment by wtrocki** [comment]
`npx graphback-cli config` is going to use released one. 

`npx graphback-cli@0.14.0-alpha1 config`

**Comment by lastmjs** [comment]
Things have been going very well for me today! I've started to incorporate graphback into a large project to get rid of Prisma.

One significant issue I am facing is a limitation with filtering. Prisma had a way to filter across relationships. This is especially useful when filtering across a one to many relationship.

I have a one-to-many relationship from an entity called Companies, to an entity called Invoices. Each company has many invoices. I want to be able to filter all companies based on fields in the invoices. For example, I would write something like this with Prisma:

```graphql
query($forMonth: String!) {
  companies(
    where: {
      canceled: false
      invoices_some: {
        for_month: $forMonth
      }
    }
  ) {
    id
}
```
This allows me to get all companies where at least one invoice is in the month I am searching for.

Can graphback support this type of filtering?

**Comment by lastmjs** [comment]
I've updated my list of missing features

**Comment by craicoverflow** [comment]
Thanks a lot for this issue! We have created several issues using this feedback so I will close this one.
