### ISSUE TITLE
www.graphback.dev not valid

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1270]
Only graphback.dev will work as a valid URL:

`NET::ERR_CERT_COMMON_NAME_INVALID`

Both www.graphback.dev and graphback.dev (in fact every subdomain should redirect to graphback.dev)

**Comment by wtrocki** [comment]
I have checked that. Github pages do not issue valid cert for www. They support only root. I tried to do redirect from www to graphback.dev but that do not work nicely for https (still ending with cert issue). 

Considering small impact of this change I will suggest to ignore this for the moment?

**Comment by craicoverflow** [comment]
Best thing would be to redirect www.graphback.dev to graphback.dev.

Let's close for now.

**Comment by wtrocki** [comment]
That is currently happening but it is not working due to https issues
