### ISSUE TITLE
Investigate and implement reliable subscriptions filtering

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1273]
Subscription filtering is curently disable due to the limitations of the mechanism. We should investigate other frameworks to see how we can apply basic filtering capabilities to subscriptions without sacrificing performance

**Comment by lastmjs** [comment]
So what is the state of subscriptions right now? Do they just work for all updates to an entity, all creates to an entity, or all deletes to an entity?

**Comment by wtrocki** [comment]
Subscriptions do not have filtering enabled. Every update to dataset will send update to client. We have filtering on the schema it is just to apply it so it will actually perform. 

Filtering described on subscription package is not production ready.

**Comment by wtrocki** [comment]
@lastmjs Looking for feedback. I'm trying to push some of the structure into subscriptions - adding docs first and collecting requirements.

Would you prefer different subscriptions per CRUD model - CREATE, DELETE, UPDATE 
or a single subscription that offers extra fields:

```graphql
_created: Boolean
_updated: Boolean
_deleted: Boolean
```

CC @craicoverflow @machi1990

**Comment by lastmjs** [comment]
Personally I would prefer separate subscriptions per CRUD model, similar to how it is now: `updatedUsers`, `createdUsers`, `deletedUsers`. This seems to match the mutations more directly, making the context switch simpler, and I imagine would allow the same or similar filters to be used on the subscription as in the mutations.

**Comment by craicoverflow** [comment]
Let's remove subscription filters from the schema for now since they are not fully implemented. It can be restored from https://github.com/aerogear/graphback/pull/1683 when required.

**Comment by wtrocki** [comment]
From my point this will cause couple issues related to offix and client side queries. If we have ability to not break client side API/typings while we can provide this feature under the hood after 0.14.0 with smooths and painless update. If we are worried about users being confused we can put warning for filtering

**Comment by craicoverflow** [comment]
Sure, I did not really consider how it would affect documentation. I will add it to docs.

**Comment by craicoverflow** [comment]
Added this to 0.15 milestone. Is that okay?

**Comment by wtrocki** [comment]
yep.. I have missed that ! Thank you

**Comment by machi1990** [comment]
Fixed by #1748.  We released [0.15.0-alpha1](https://github.com/aerogear/graphback/releases/tag/0.15.0-alpha1) containing this feature, with further updates to follow as part of https://github.com/aerogear/graphback/issues/1760
