### ISSUE TITLE
Mongo Projection to return necessary data for better performance?

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1281]
While checking the [MongoDBDataProver.ts](https://github.com/aerogear/graphback/blob/f7cefff40f5557f6e23c9d4ca2db52cb7ee6767a/packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts)

I noticed we have queries like the one below:

https://github.com/aerogear/graphback/blob/f7cefff40f5557f6e23c9d4ca2db52cb7ee6767a/packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts#L99

Which will basically return all the fields in the collection, is using https://docs.mongodb.com/manual/tutorial/optimize-query-performance-with-indexes-and-projections/#use-projections-to-return-only-necessary-data something that we have considered? 
I think it is interesting when working with existing databases where we typically will be looking at selecting only fields defined in the model and not all collection's fields. 

Same can be asked for the PG data provider even though I have not checked the resulting SQL query sent yet.

**Comment by wtrocki** [comment]
This is actually a very important issue that we have out there for a long time and wanted to address for 0.14.0 (although we still trying to get other things sorted first. 

https://github.com/aerogear/graphback/issues/793

**Comment by craicoverflow** [comment]
That is a great point. We do plan to integrate [graphql-query-mapper](https://github.com/aerogear/graphback/issues/793) at some point.

**Comment by machi1990** [comment]
Great, when I searched for `project`, `select *` or the likes no issue showed up which led me to opening this issue. If you do not mind, we can close this one as a duplicate in favour of #793. Thought?

**Comment by craicoverflow** [comment]
Sure, I will close it and will link it because you focus on MongoDB, which the other issue does not.
