### ISSUE TITLE
JSON scalar support

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1282]
PostgreSQL has JSON column type support, as does MongoDB.

Graphback should provide a JSON scalar to automatically map and handle parsing of JSON fields. 

Options:

- [graphql-type-json](https://github.com/taion/graphql-type-json)
- [graphql-scalars](https://github.com/Urigo/graphql-scalars)

## Tasks

- Add scalar mapping to graphql-migrations
- Add scalar to resolver

## Additional

This may not be required for MongoDB since developers can use embedded fields which would be mapped to a GraphQL type.

**Comment by wtrocki** [comment]
Scalars using that package so we might just bring it for people to use other scalars here

**Comment by craicoverflow** [comment]
> Scalars using that package so we might just bring it for people to use other scalars here

Are you talking about `graphql-scalars`? That package is 140 kB (20 times larger than `graphql-type-json`). I think we should add one or two important individual scalars people will want out of the box. Any additional ones that don't have a database type anyway can be handled in their custom resolvers maybe?

**Comment by wtrocki** [comment]
Agreed.
