### ISSUE TITLE
Simplify schema plugin API

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1283]
The barrier to custom plugin creation is too high and it is too complex.

1. Create a plugin module and publish it to NPMJS
2. Instal plugin as a dependency
2. Reference the plugin name in the config file. This would not work for namespaced plugins like `@myorg/graphback-plugin`
3. The plugin engine loads the plugin dynamically from the name.

Why not something like this?

```ts
const myPlugin: GraphbackPlugin = {
  transformSchema(...) { ... }
}

const plugins: GraphbackPlugin[] = [
  myPlugin
]

const { resolvers, typeDefs } = graphback(schema, {
 ...
 plugins: plugins
})
```

**Comment by wtrocki** [comment]
Worht to add - 
Plugins can move from declarative to code-based (as runtime). The only need for declarative plugins is an client side generation now.
