### ISSUE TITLE
Research data synchronization patterns 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1284]
# Issue covered in the GSOC proposal. 

We going to investigate following patterns:

- Soft Deletes
- Separate table with soft deletes
- Separate table with the CREATE, UPDATE and DELETE actions
- Others

**Comment by wtrocki** [comment]
Provide comments with description of the approaches.

**Comment by ssd71** [comment]
Soft deletes is the most basic form of datasync that we could implement, in which we would just mark items as `_deleted:true` and have an index on the deleted fields, We could also groom by TTL, and for mongo this could be done rather [easily](https://docs.mongodb.com/manual/core/index-ttl/)  if we store timestamps as Date objects. This is a rather barebones approach to datasync, where we won't use any extra tables for sync queries. Possible drawbacks:
- We can only get the last updated version, so somebody who just connected cannot get any of the past updates
- Sync queries could get very verbose and could become very slow as size of table/collection increases even with indexes

Soft Deletes with a separate delta table could effectively mitigate both of these drawbacks. This would normally involve a delta table for each collection/table in the database to keep the updated entry for every mutation to an entry in the collection/table

(All of this assuming in both of these cases we will be using createdAt and updatedAt)

I am not sure I understood the third option, it would be really helpful if you could elaborate a bit :smile: Did you mean transactions?

**Comment by wtrocki** [comment]
Awesome writeoff! I cannot agree more. 
I do think that 1,2 options could be quite good for giving people different capabilities. They come with their own pros and cons.

> I am not sure I understood the third option, it would be really helpful if you could elaborate a bit 😄 Did you mean transactions?

It is even driven approach - instead of data we save what happen. 
So action type here can be CREATED,UPDATED,DELETED

https://github.com/aerogear/datasync-starter/blob/data-sync-delta/server/src/tasks/schema.js#L178

We can use them to deliver subscription like payload to client.
Client requests what was changed instead of pure data. 

Then it needs to apply every add, update, delete to their store.
It has couple strange things - schema needs to be different and client needs to have custom logic to perform that.

**Comment by ssd71** [comment]
@wtrocki Are we going to use `updatedAt` to replace `version` in Offix or does `version` field stay?

**Comment by wtrocki** [comment]
we going to replace the version field with upadtedAt. We have this capability in offix so no worries.

**Comment by wtrocki** [comment]
CC @Eunovo @kingsleyzissou

**Comment by wtrocki** [comment]
Actually vesions will go away completely in offix. Graphback will simply need to cather for the consistency of the data by utilizing updatedAt field etc.

**Comment by kingsleyzissou** [comment]
Cool cool cool

**Comment by Eunovo** [comment]
Okay @wtrocki
