### ISSUE TITLE
Relationship support in schema and resolvers

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#130]
## Background
`graphback` version `0.3.1` creates database structure for relationships.

## TODO
Add relationships in `schema` and `resolvers`
For a model
```
type Note {
    id: ID!
    title: String!
    comments: [Comment!]!
}

type Comment {
    id: ID!
    content: String!
}
```
we can create the schema with types like
```
type Note {
    id: ID!
    title: String!
    comments: [Comment]!
}

type Comment {
    id: ID!
    content: String!
    noteId: ID!
}
```
Not sure how to work with n:m relations for now
Resolvers can be implemented using either
- Dataloader
- Graphql-query-mapper

@wtrocki What should be the methods we should provide for relationships? like `findXsOfY` for example.

**Comment by wtrocki** [comment]
>     noteId: ID!

That is not valid schema. It needs to refer to a single or array of a specific type.

**Comment by wtrocki** [comment]
> findCommentsOfNote  //for 1:m relation

None of those is needed. We should be able to query comments from `findAllNotes` etc. Please go thru learn.graphql.com for more info

**Comment by wtrocki** [comment]
> Dataloader
> Graphql-query-mapper

Ideally, we need both query mapper can be used to descope the range of query.
I would see query mapper doing more heavylifting so we can drive more requirements for this library. DataLoader is must for us.

We need to have both available as part of the strongly typed context so people can easily drop their code.
