### ISSUE TITLE
Unable to filter by DateTime scalar type

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1314]
With this change https://github.com/aerogear/OpenVolunteerPlatform/commit/eab3e73564c5fee5ef1733c0a5f38e680f6a51c7, I want to be able to filter by date: E.g I can issue a query like below to get the actions completed at a given day.

```
query {
  findVolunteerActions(filter: {
    completedAt: {
      ge: "2020-05-27T00:00:00.000Z"
      lt: "2020-05-28T00:00:00.000Z"
    }
  }) {
    items {
      id
      status
      createdAt
      completedAt
      assignedAt
    }
  }
}
```

But I always get an empty list of actions even if I had actions completed in a given date.

The issue would be coming from https://github.com/aerogear/OpenVolunteerPlatform/commit/eab3e73564c5fee5ef1733c0a5f38e680f6a51c7#diff-67d8b697bad205d8b8d5b5f6f0417b24R435 since the Filter Input type is a `StringInput` and not a `DateTimeInput`, meaning that the raw string is sent to mongo db and not a date type.

We should be able to infer scalar types and generated appropriate Inputs for filtering.

**Comment by wtrocki** [comment]
Critical. Funny story that we had talked about this very issue before lunch. If we send date as string is not going to be represented in the db.

We use date scalar on server it is just that input types are mapped to strings for the moment. Quick workaround would be to transform date from string to date on server

**Comment by wtrocki** [comment]
One way to fix it is to detect all types of scalar used in object and create filters for it. Not much job but it will be verbose

**Comment by machi1990** [comment]
> One way to fix it is to detect all types of scalar used in object and create filters for it. Not much job but it will be verbose

I am very much for this option and it could be generic enough for all scalar types.

**Comment by machi1990** [comment]
> We use date scalar on server it is just that input types are mapped to strings for the moment. Quick workaround would be to transform date from string to date on server

That'd be doing the job of `DateTimeResolver`.

Another workaround would be to use timestamps e.g instead of `DateTime`, use an `Int`. But I'd rather wait for this to be handled intelligently as I like a field type to tell what it is - Date :-)

**Comment by craicoverflow** [comment]
There is a plan to add Date scalars to Graphback and also generate filters. Hopefully we can add this soon.

See https://github.com/aerogear/graphback/issues/1095

**Comment by machi1990** [comment]
That could be nice. Is that planned for the next release?

**Comment by craicoverflow** [comment]
> There is a plan to add Date scalars to Graphback and also generate filters. Hopefully we can add this soon. It should be in before the next minor release anyway.
> 
> See #1095

Yep it should be in before we do next release. Working on improvements to the runtime API and when that is done we can revisit Date filtering.

**Comment by wtrocki** [comment]
> There is a plan to add Date scalars to Graphback and also generate filters. Hopefully we can add this soon. It should be in before the next minor release anyway.

This is not going to resolve much because there will be always other scalar to add. We need to generate FilterInputyType for each scalar that is added manually in the schema (it is actually very simple thing to do as we have already ones for String.


I see this as:

- @machi1990 Can spent 1 hour to do hacks on OVP to get this running
- @craicoverflow can do some pair programming with @machi1990 to resolve it it graphback in the same amount of time (not including test)

**Comment by wtrocki** [comment]
![](https://media.wired.com/photos/5c9ba67d1e34481170ef2bcd/2:1/w_1622,h_811,c_limit/Culture_Matrix_RedPillBluePill-1047403844.jpg)

**Comment by machi1990** [comment]
> We need to generate FilterInputyType for each scalar that is added manually in the schema (it is actually very simple thing to do as we have already ones for String.
 
+1.

> I see this as:
> 
> * @machi1990 Can spent 1 hour to do hacks on OVP to get this running

If we are going to work on point below, there is no need to spend time on hacking this on OVP side. 

> * @craicoverflow can do some pair programming with @machi1990 to resolve it it graphback in the same amount of time (not including test)

Thoughts:

- I think we could as well prepare a fix in graphback, add minimal tests, and then make a aplha release which we are going to use in OVP.

**Comment by wtrocki** [comment]
Initial PR created. @machi1990 will add enum support to fix this

**Comment by machi1990** [comment]
Fixed by https://github.com/aerogear/graphback/pull/1315
