### ISSUE TITLE
Subscription - using 3 different subscriptions vs single subscription per type

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1318]
We need to consider simplifying our subscription logic to improve support for the client side. Having 3 different subscriptions is not only problematic for the client (if you want to keep one view opened you need to have 3 types of subscriptions but it also impacts performance. 

This issue should be used as discussion for production ready subscriptions.

**Comment by craicoverflow** [comment]
Link this @craicoverflow @wtrocki
