### ISSUE TITLE
resolvers.ts file is hard to maintain

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#132]
Having a single resolvers file is probably a bad idea. We should be creating a resolvers ts file per type. Additionally, we can rename the genrated folder to simply resolvers. Users should be able to extend resolvers somehow.

What I think we can do is:

1) Generate resolvers per type

`/resolvers/note.ts`

2) Generate empty resolvers file that users can build themselves

`/resolvers/note.custom.ts`

3) Merge resolvers object together by overriding generated ones if possible
 
4) Wrap all into graphql module with schema for consistency

**Comment by wtrocki** [comment]
@darahayes @StephenCoady opinions?

**Comment by StephenCoady** [comment]
@wtrocki this seems like a reasonable idea to me. What about:

`/resolvers` for the top level
but then splitting them like this:
`/generated`
`/custom`

might make separation and development a bit cleaner.

**Comment by wtrocki** [comment]
This one will work as well

**Comment by ankitjena** [comment]
> @wtrocki this seems like a reasonable idea to me. What about:
> 
> `/resolvers` for the top level
> but then splitting them like this:
> `/generated`
> `/custom`
> 
> might make separation and development a bit cleaner.

And splitting those resolvers again for readability

**Comment by wtrocki** [comment]
This will also allow us to have some specific mappers inside resolvers folder and also extra stuff like Context types.

**Comment by ankitjena** [comment]
WDYT we drop the `generated` folder and go with this
```
|----src
      |----resolvers
            |----generated
            |----custom
      |----schema
            |----generated
            |----custom
```

**Comment by wtrocki** [comment]
+1 for resolves. I will keep schema in `./schema/generated.schema`

**Comment by wtrocki** [comment]
Manual integration test. Good to go
