### ISSUE TITLE
Rename db.primary to db.id for better visibility.

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1322]

**Comment by craicoverflow** [comment]
+1

Or just """@id"""

**Comment by machi1990** [comment]
Should we keep `db.primary` around and deprecate it to avoid breaking change?

**Comment by craicoverflow** [comment]
Yeah I guess so :)

**Comment by wtrocki** [comment]
Trick is to do as many braking changes as.possible until 1.0 so after that it will.be not needed and code will be easy to maintain

**Comment by machi1990** [comment]
So we can safely rename and add a breaking change note in the release notes?

**Comment by wtrocki** [comment]
Yep. It is couple min fix on user side anyway

**Comment by wtrocki** [comment]
0.14.0 is uber breaking so we can break as much we want

**Comment by machi1990** [comment]
Sure, I'll make it `@db.id`. So that it is under the `@db` namespace like the others.
