### ISSUE TITLE
Create API reference in docs listing all possible annotations available.

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1323]
Annotations are hard to work (as they require reference) 
Our docs do not have a reference for those (they are spread across different topics and hard to find.

Adding new annotation brings mental challenge (where to add this)

**Comment by machi1990** [comment]
We have this https://github.com/aerogear/graphback/blob/master/docs/metadata.md that's a step closer to this goal. Also we this issue https://github.com/aerogear/graphback/issues/1526 to work on docs generally. Can this be closed?
/cc @craicoverflow @wtrocki

**Comment by craicoverflow** [comment]
Yep, this can be closed thanks to the proactive work by @ssd71
