### ISSUE TITLE
[Discussion] Generating Mutations for Offix support

### ISSUE THREAD

**Issue by Eunovo** [aerogear/graphback#1336]
Offix requires `version` to be sent with mutations. Currently, mutations are generated by schema plugin. We need offix plugin to generate the mutations instead so it can add the `version` parameter. 

One way to do this is to place the offix plugin before the schema plugin. The offix plugin will generate the mutations and disable mutation crud options for all models so the schema doesn't generate mutations.

Another way is to have the offix plugin only generate the mutation input types and allow the schema plugin to just generate the mutations. Here, we would need a way to disable mutation input type generation in schema plugin.

cc @wtrocki

**Comment by wtrocki** [comment]
Yes.. There is couple other details like instead of version we will use lastUpdated value etc. but generally tgat will be it

**Comment by wtrocki** [comment]
Idea is that.. People add `@versioned` annotation and get these fields. 
See #1301 for more details. 

As for conflict resolution - that will be done as part of the work we do for the datasync. We will follow the conflict protocol that is being documented in offix.

> Because the schema plugin is not "aware" of offix,

There is offix plugin we will work on. 

> If we change how offix works, we might have to modify the schema plugin to add more details. Shouldn't the offix plugin be in charge of adding the details necessary for offix to work?

No. This is not how our plugins work. Our schema plugin has nothing to do with Offix. If you want to change schema you will need separate plugin etc.
At this point we will use some of the digging capabilities to deliver data changes and the only thing that offix will know or be aware of is the format of the delta schema that will be documented etc.

**Comment by Eunovo** [comment]
All right. Thanks
