### ISSUE TITLE
Cross filtering on both sides of relationship.

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1338]
We are able to support filtering on `@oneToMany` relationships but not the inverse, making a query like below (ignore the SQL syntax ;-)): 

```
Select id, barId from FOO where barId in (select id from BAR where BAR.xxx =yyy)
```

requiring workaround to perform. 

A query like the one above is very common in most applications, open an issue to evaluate if we support it or not.

**Comment by lastmjs** [comment]
I would really like to see this use case, I'm going to have to do some nasty workarounds for this

**Comment by craicoverflow** [comment]
Closing in favour of duplicate https://github.com/aerogear/graphback/issues/1343
