### ISSUE TITLE
Build graphql js template

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#134]
GraphQL js template will be the same as apollo but using graphqljs instead.

**Comment by ankitjena** [comment]
Currently for apollo we are generating resolvers in the following format
```
const resolvers = {
    Query: {
        findNotes: {},
     },
     Mutation: {
         createNote: {} 
     }
}
```
But express-graphql accepts `rootvalue`, which is like
```
findNotes: {},
createNote: {}
```

So we have to change resolver generation process with various types of resolver output. We can keep this in the `config.json` and the `generate` command will use that to generate respective resolvers.

Plus we have to discuss with the approach of splitting resolvers that you suggested.

**Comment by wtrocki** [comment]
This is exactly what I wanted you to found out! We need 2 templates to catch those problems. This means that we need to have our generator changed to output something that then can be reformatted inside the template. WDYT? 

Having 2 types of libraries will really help us to make this generic.

Ok.. I did not found that myself - just people asked how this will work with graphql-js :)

**Comment by wtrocki** [comment]
@ankitjena I think this will be also very important to architecture together with #132

**Comment by ankitjena** [comment]
@wtrocki Yes let's first address #132, I think this will be really quick after that
