### ISSUE TITLE
OffixMongoDBDataProviderTest is missing test?

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1360]
The file https://github.com/aerogear/graphback/blame/ed6a766f15fa7dbacd2f1f0070799ec90dcab5aa/packages/graphback-runtime-mongodb/tests/OffixMongoDBDataProviderTest.ts

does not actually have any test. 

Should we keep it by adding more test or remove it? 
/cc @ssd71 @wtrocki @craicoverflow

**Comment by wtrocki** [comment]
Good timing. We will move all offix specific stuff (and rename it to datasync package). Trick is to not polite Graphback core with the datasync so initially I wanted to see if we want:

- 3 packages - DataSync plugin, DataSync-mongo, DataSync-Client-plugin
- 2 packages - DataSync plugin, DataSync-mongo,
- 1 package - @graphback/datasync

My preference will be to have just one package that will change schema provide data source and even some client side generation capabilities.

**Comment by ssd71** [comment]
+1 for only one package.

Having 2 or more packages as it currently has, sounds like loose coupling, which could have advantages but tbh I cannot see any here.

How would we use one package both as plugin and as data source though?

I think it would be really cool to have datasync added in just one step but I don't think it is possible with current API

**Comment by wtrocki** [comment]
We have desined things this way before that package can be plugin and also expose other elements. Graphback packages that are plugins need to expose `Plugin` namespace. Rest of the stuff is bonus and can be used anywhere - for example to create runtime. 

We going to refine runtime in #1324 so hopefully it will be easier to see how this will work. I guess if we have decision and we have deprecated offix plugin we are free now to rename offix package to datasync package.

**Comment by ssd71** [comment]
Yep, sounds great!

**Comment by ssd71** [comment]
Also this might be a stretch, but is it okay to enforce only using datasync providers when  useing datasync schema plugin and vice versa?

**Comment by wtrocki** [comment]
@ssd71 that will be the plan - separate method to create graphback and graphback-datasync runtime

**Comment by machi1990** [comment]
Thanks lads @wtrocki @ssd71

**Comment by craicoverflow** [comment]
Offix providers are no longer used right? I guess they should be removed soon.

**Comment by wtrocki** [comment]
This is outdated. Closing

**Comment by craicoverflow** [comment]
Yeah I agree that it is outdated - it's just we still have the Offix files in the repo which should be removed at some point.

**Comment by machi1990** [comment]
> Yeah I agree that it is outdated - it's just we still have the Offix files in the repo which should be removed at some point.

+1

**Comment by wtrocki** [comment]
Again - my bad. I though we removed offix package and tests.
@ssd71 would you be able to clean this up

**Comment by wtrocki** [comment]
Actually this should happen post official release so we will update readme on NPM etc.

**Comment by ssd71** [comment]
> @ssd71 would you be able to clean this up ?

Sure, I'll put in a PR after a 0.14.0 release

**Comment by wtrocki** [comment]
I can try to get rid of this sooner but suppress it on the datasync-starter repo. All good
