### ISSUE TITLE
Can't access relation in selection set of created subscription

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1373]
I have this model:

```graphql
""" @model """
type Duration_events {
    id: ID!
    created_at: String!
    updated_at: String!
    description: DURATION_EVENT_DESCRIPTION!
    timestamp: String!
    type: DURATION_EVENT_TYPE!
}
```
I am doing this subscription on my client:

```graphql
subscription {
  newDuration_events {
    user {
      id
    }
  }
}
```
I keep getting this error in the websocket message whenever I add a new Duration_events:

```javascript
No result from database: Cannot find a result for users with filter: {}
```
When I intercept the payload in the resolver for this subscription using the `resolve` function, I get the following payload:

```javascript
{
   newDuration_events: {
     id: '89',
     type: 'START',
     timestamp: '2020-06-03T23:19:42.373Z',
     call_id: null,
     user_id: 2,
     created_at: '2020-06-03T23:19:42.373Z',
     updated_at: '2020-06-03T23:19:42.373Z',
     description: 'CALL_START',
     valid: true
   }
 }
```
So I'm not sure why this issue occurs

**Comment by lastmjs** [comment]
Oh wait, it's because I don't have `user: Users!` defined in my `Duration_events` type. It's working now, though that error wasn't very helpful

**Comment by craicoverflow** [comment]
Thanks for logging this issue! I'll close this as it looks like the issue was resolved.
