### ISSUE TITLE
Delta sync

### ISSUE THREAD

**Issue by ntziolis** [aerogear/graphback#1382]
A generalized way to handle changes in data on the server while client was offline without refetching all data after reconnect as well as transparently execute initial data loading without requiring user to have all data locally already for app to function.

I completely understand that this is not a client only feature but this library seemed to be the best place to start a discussion on how we would go about establishing a standardized way to achieve this capability (server to client data replication) when leveraging a graphql backend

**Describe the solution you'd like**
- Client side API that allows to specify which data should be delta synced from the server to the client and how in a non boilerplate manner
- Server side requirements to support delta sync
- Establish overridable conventions

**Describe alternatives you've considered**
- AWSAppSync
  - Its AWS only
  - No support for apollo >2.5 local state management and local resolvers
- Custom built on graphql
  - Well ... it would be custom building a central component of what a lot of folks need
- custom build on top of puchdb
  -  requires couchdb compatible db on server vs graphql endpoint

**Comment by wtrocki** [comment]
@ssd71 This is the top level issue that we have moved from offix that covers the work you are doing. As you see this is very old requirement coming from community and it is really exciting to see us finally moving that forward (on different repo). I have added it to post top level progress on the work we have done

**Comment by wtrocki** [comment]
Graphback.dev now supports datasynchronization in beta phase. Please check our documentation
