### ISSUE TITLE
Default ordering

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1383]
What is the default order when returning results? It seems kind of random. What if by default all queries returned ordered by the id?

**Comment by wtrocki** [comment]
Postgress or Mongo? I have checked SQL is executed without order for the both cases which is generic Mongo and Postgress question.

For PG:
```
Rows are returned in an unspecified order, per sql specs, unless you add an order by clause. In Postgres, that means you'll get rows in, basically, the order that live rows read on the disk.
```

**Comment by lastmjs** [comment]
Alright, I'm using Postgres. I guess if that's the spec then we're good
