### ISSUE TITLE
CallsResultList count is null

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1384]
The count field in the selection set for any `CallsResultList`'s that I try to get is always null

**Comment by wtrocki** [comment]
We need count to be calculated on demand and we still did not implemented that. That is why we still are alpha. Sorry for inconvenience.

**Comment by lastmjs** [comment]
No problem

**Comment by machi1990** [comment]
Fixed by https://github.com/aerogear/graphback/pull/1533
