### ISSUE TITLE
getPrimaryKey is undeterministic

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1401]
The 
 function https://github.com/aerogear/graphback/blob/e978b99cf4ae126452f196c243062ae53737d888/packages/graphback-core/src/db/getPrimaryKey.ts#L11
 is not deterministic where for this model:
```
    """ @model """
    type User {
        """
        @id
        """
        email: String!
        id: ID!
    }
```

it returns `id` as primary key and for this model below
```
    """ @model """
    type User {
        id: ID!
        """
        @id
        """
        email: String!
    }
```
 it returns `email` as primary key. 

I think it should return `email` in both cases.

**Comment by wtrocki** [comment]
+1
