### ISSUE TITLE
DatasyncPlugin should not require an `outputPath` config option

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1407]
Since resolver generation is removed, we no longer persist anything to files, so this option should be completely removed

**Comment by ssd71** [comment]
Since the express objective of datasync is now to provide delta queries, I am thinking we also do not need the other options:
https://github.com/aerogear/graphback/blob/a48e8f432bca9a3404f9a3956fb0b8982b109daa/packages/graphback-datasync/src/DataSyncPlugin.ts#L11-L28

WDYT?

**Comment by wtrocki** [comment]
No. We do not need them

**Comment by craicoverflow** [comment]
Agreed

**Comment by ssd71** [comment]
I was also thinking should we have a stub `strategy` option for selecting datasync strategies or is it too early to decide?

**Comment by wtrocki** [comment]
Hmm.. strategy will be just different provider set. plugin always add the same schema etc.
