### ISSUE TITLE
Cannot use sync from DataSync

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1411]
On trying the 'sync' query:
```
Please use DataSync provider for delta queries
```

It seems the sync resolver is not actually returning anything:
https://github.com/aerogear/graphback/blob/b7c74ed0515d9e3e1771cbf9cb8db47732ddb98c/packages/graphback-runtime/src/resolvers/LayeredRuntimeResolverCreator.ts#L89-L100

Was this removed to discuss further ways of adding this resolver outside of @graphback/runtime :thinking: ?

I think this is a good opportunity regardless, do let me know what you think :)

**Comment by ssd71** [comment]
CC @craicoverflow

**Comment by wtrocki** [comment]
Yep. We need to have chat about this
Generally it is pointless for us to have separate package with datastore if we have embedded DataSync in resolvers.

**Comment by ssd71** [comment]
I was thinking if it would be useful to be able to add resolvers from a plugin (or something similar).
In current state the plugins can only modify the schema, leaving graphback to fill in the gaps, therefore there is not much point to other people building plugins if they cannot do anything other than modify schema without adding any extra resolvers. Correct me if I am wrong, if plugins can add more resolvers, doesn't that also mean we could add custom scalars with a plugin? Sounds overkill I guess but just wanted to poke around and discuss about this

**Comment by wtrocki** [comment]
You are right. We kinda need that. Previously we had plugins generate files that could be resolvers now we have this runtime resolver creator that do not have ir

**Comment by craicoverflow** [comment]
> It seems the sync resolver is not actually returning anything:

That was a mistake by me, when merging conflicts! Sorry about that.

**Comment by ssd71** [comment]
> > It seems the sync resolver is not actually returning anything:
> 
> That was a mistake by me, when merging conflicts! Sorry about that.

Ah cool :smile: , though what do you think about the rest of the discussion above

**Comment by craicoverflow** [comment]
I do believe we need some form of plugin for resolvers. I was originally thinking this might require a new plugin engine specifically for resolvers, but it should work just fine in the regular plugins. 

`GraphQLSchema` object can contain all resolver methods. I've just tested the following example in `SchemaCRUDPlugin` and it works.

```
schemaComposer.addResolveMethods({
  Query: {
    hello: (source: any, args: object, context: unknown, info: any) => {
      return 'Hello world!'
    }
  }
})

const resolvers = schemaComposer.getResolveMethods()
```

This could actually be a much more centralised/extensible approach to building the Graphback API - and nothing architecture-wise has to change!

Currently we return `typeDefs` and `schema` - but `schema` does not have resolver methods, only type definitions so it is pretty much useless.

**Comment by wtrocki** [comment]
I put some thoughts and I think extending current plugin format will be rather simple and effortless.

What we need is plugin to add or edit resolvers object directly - it will mean that schema plugin will need to take all the responsibility of the LayeredRuntimeResolverCreator which was artificially put into runtime package. 

I can explain more if needed.
WDYT?

**Comment by wtrocki** [comment]
We probably looking to add new method into abstract plugin:

```
abstract addResolvers(resolverObject: any){
	return resolverObject;
}

**Comment by craicoverflow** [comment]
> We probably looking to add new method into abstract plugin:
> 
> ```
> abstract addResolvers(resolverObject: any){
> 	return resolverObject;
> }
> ```

No need IMO - Resolvers can be added to schema object and separated at any point outside the plugin.

**Comment by craicoverflow** [comment]
I'm going to spin a new issue from this about resolver generation in plugins.
