### ISSUE TITLE
Move @crud annotation config into @model annotation

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1424]
It would make a lot more sense to combine `@model` and `@crud` annotations so that we no longer need `@crud`.

```graphql
"""
@model(
  create: true,
  delete: false
)
"""
type User {
 ...
}
```

**Comment by machi1990** [comment]
A huge +1 for this.

**Comment by craicoverflow** [comment]
This will be breaking, good to get in before 0.14.0 stable, will start it.

**Comment by wtrocki** [comment]
I think there is no need for us to rush with 0.14.0.
We need to make it uber breaking but this time it will be the vision for the tool we really want.

**Comment by craicoverflow** [comment]
yep agreed - I am doing this one as it is small and quick win on a Friday

**Comment by craicoverflow** [comment]
https://github.com/aerogear/graphback/issues/1418 is more important but we should discuss it next week

**Comment by machi1990** [comment]
> #1418 is more important but we should discuss it next week

Yeap.
