### ISSUE TITLE
Knex pooling

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1431]
Hey, I'm getting this error from a lambda function:

```
errors: [
    KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
        at Client_PG.acquireConnection (/var/task/node_modules/knex/lib/client.js:349:26) {
      locations: [Array],
      path: [Array]
    }
  ],
  data: null
}
```
How is pooling of connections to the database being handled? Is there anything special that I need to do, are there any configuration options for this?

I'm using graphback with knex, and I'm also using node-postgres for some raw sql queries, which has its own pooling.

**Comment by wtrocki** [comment]
Knex should be initialized on the application side (your app) with config that has `pool: { min: 5, max: 30 }` 

See http://knexjs.org/#Installation-pooling

Our sample app did not have pooling so I will keep that open to provide some.

**Comment by lastmjs** [comment]
I am able to configure the pooling, I think this might be a problem with my redis connection actually

**Comment by lastmjs** [comment]
This was just me not configuring my AWS security groups correctly. Close when you want, thanks!

**Comment by craicoverflow** [comment]
Hi @martinhesko - we need some default pooling config for Knex - assigning to you
