### ISSUE TITLE
Can't add custom field with custom type to model type

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1432]
I am trying to add a custom field to one of my models. The custom field maps to a custom type, which is not a model. I'm going to implement the resolver myself, which won't have anything to do with my database. I keep getting this error when trying to do so:

```Generation failed: TypeError: Cannot read property 'name' of undefined```

For example:

```graphql
""" @model """
type Invoices {
  id: ID!
  stripe_invoice: StripeInvoice
}

type StripeInvoice {
  totalPaid: Int!
  totalCharged: Int!
}
```

The `Invoices` type is a model and has fields in the database, but the `stripe_invoice` field will have a custom resolver that actually hits the Stripe API. I can't seem to do this right now because of the error during generation.

**Comment by wtrocki** [comment]
Hi

We are aware of the issue and going to resolve it as soon as possible in the next alpha.

**Comment by machi1990** [comment]
I'll have a look.

**Comment by wtrocki** [comment]
This has been addressed

**Comment by wtrocki** [comment]
Going to land in alpha4
