### ISSUE TITLE
Stray generated schema in template?

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1435]
I found this file in the postgres template:
https://github.com/aerogear/graphback/blob/templates-0.14.0/templates/ts-apollo-postgres-backend/src/schema/schema.graphql

Is this a generated schema? A bit confused if this is intentional :smile:

**Comment by machi1990** [comment]
I think this file should not be there, right? @wtrocki

**Comment by wtrocki** [comment]
not needed now

**Comment by craicoverflow** [comment]
Assigning to you @ssd71 - mind doing this when you get a chance?

**Comment by ssd71** [comment]
By all means :smile:

**Comment by ssd71** [comment]
The file is not there on master, should we update templates branch or do I open a PR to templates branch?

**Comment by wtrocki** [comment]
Hmm.. we need to push to that branch from master that is all. Closing

**Comment by machi1990** [comment]
Maybe it will be good to add these schema.graphql file in  .gitignore file? WDYT?

**Comment by wtrocki** [comment]
I think that is worth to generate it still if you want to have it phisically in repo
