### ISSUE TITLE
Single annotation to rule them all

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1444]
Instead of using `model, versioned and delta` we can use `datasync` to imply all 3 of them.

**Comment by craicoverflow** [comment]
Misleading title, I thought you meant one namespace for ALL metadata.

I still think `@model` should be separate, using `@datasync` will cause issues in migrations and everywhere that depends on `@model` to build metadata for plugins etc.

**Comment by wtrocki** [comment]
Agreed!
