### ISSUE TITLE
Investigate conflict resolution capabilities on top of the delta store

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1445]
When building delta store (separate table for deltas) we should take into consideration abilities to provide conflict resolution based on history etc.

**Comment by ssd71** [comment]
If we would need a separate delta store anyway, what do you think about using debezium for this, I would need to look around a bit to see if it is viable for our needs. The way I see it is that if we are going to do a separate delta store when we use datasync with postgres, I wonder if it could be worthwhile to use debezium in place of that

**Comment by wtrocki** [comment]
Trick is to have:
1) one constant delta schema standard that works
2) Default implementation for DataSync involving versioned
3) ability to plug in different field or strategy

We have 1 and 2 at the moment

**Comment by wtrocki** [comment]
Datastore is different to using different field for specific datastore/strategy. You can use soft deletes but still use version field to ensure consistency and different field to partition data

**Comment by ssd71** [comment]
Hi, sorry for being late here, but I think I see what you mean: It is entirely different thing, so I should focus on soft deletes for now, is that it?

**Comment by wtrocki** [comment]
Not sure what you mean. We need to be able to control consistency field for soft deletes. Let's create issue

**Comment by ssd71** [comment]
Yes, done #1524

**Comment by wtrocki** [comment]
Also worth to mention. WE had this really early versions of the other strategies that involve different tables. More info here:

https://github.com/aerogear/datasync/issues/46
https://github.com/aerogear/datasync/pull/45/files

**Comment by machi1990** [comment]
@ssd71 what's the update on this one, is the investigation concluded with https://github.com/aerogear/graphback/issues/1738 ?

**Comment by ssd71** [comment]
@machi1990 We do not yet have the ability to specify a different kind of State management(we only check `_version`) (drawing parallels from [here](https://github.com/aerogear/offix/blob/master/packages/offix/conflicts-server/src/api/ObjectState.ts)), but I believe that needs another issue?

**Comment by wtrocki** [comment]
Let's close this
