### ISSUE TITLE
`printSchemaHandler` still uses GraphbackRuntime

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1448]
[printSchemaHandler](https://github.com/aerogear/graphback/blob/18b80864290803c7d86736c36e8626de60cbddbd/packages/graphql-serve/src/components/printSchemaHandler.ts#L12) from graphql-serve needs to be updated to use the new runtime API, then we can remove GraphbackRuntime.

When GraphbackRuntime is removed, `LayeredRuntimeResolverCreator` and any related unused files should be removed too.

**Comment by craicoverflow** [comment]
graphql-serve can dynamically load Graphback plugins from the `.graphqlrc` file, whereas our new API uses code-loaded plugins.

These approaches are still compatible, however I know that `graphback-datasync` plugin will not work loaded from a config file because Graphback rewrites `graphback` prefixed plugins to `graphback-codegen-x`.

All we need to do is remove `codegen` from the renaming in [loadPlugins#L10](https://github.com/aerogear/graphback/blob/21d8cbf02efd6b72cee51d10565534f605de168e/packages/graphback/src/loadPlugins.ts#L10) and it should work.

**Comment by wtrocki** [comment]
Nice!

**Comment by machi1990** [comment]
> graphql-serve can dynamically load Graphback plugins from the `.graphqlrc` file, whereas our new API uses code-loaded plugins.
> 
> These approaches are still compatible, however I know that `graphback-datasync` plugin will not work loaded from a config file because Graphback rewrites `graphback` prefixed plugins to `graphback-codegen-x`.
> 
> All we need to do is remove `codegen` from the renaming in [loadPlugins#L10](https://github.com/aerogear/graphback/blob/21d8cbf02efd6b72cee51d10565534f605de168e/packages/graphback/src/loadPlugins.ts#L10) and it should work.

If we drop `codegen` from the renaming, it will mean having to change configurations like this https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/server/.graphqlrc.yml#L17 to add the codegen?

**Comment by craicoverflow** [comment]
> If we drop `codegen` from the renaming, it will mean having to change configurations like this [aerogear/OpenVolunteerPlatform:platform/server/.graphqlrc.yml@`master`#L17](https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/server/.graphqlrc.yml?rgh-link-date=2020-06-18T12%3A57%3A08Z#L17) to add the codegen?

Yes it does mean this.

```yaml
plugins:
  graphback-codegen-schema:
    format: graphql
    outputPath: ./src/schema
```

Unless we were to deprecated `@graphback/codegen-schema` and republish it as `@graphback/schema`, since technically codegen is optional and not so important anymore, so it might not make sense to call it that.

**Comment by craicoverflow** [comment]
Also - we rename `@graphback` scoped packages as hack of sorts because YAML does not let you write `@graphback/codegen-schema` as a key. This hack will not work for non-graphback scoped plugins from different organisations, such as `@my-cool-org/awesome-graphback-plugin`.

**Comment by machi1990** [comment]
> Also - we rename `@graphback` scoped packages as hack of sorts because YAML does not let you write `@graphback/codegen-schema` as a key. This hack will not work for non-graphback scoped plugins from different organisations, such as `@my-cool-org/awesome-graphback-plugin`.

I see now. The workaround is for users have to use the programmatic API (new runtime api) to define plugins?

**Comment by craicoverflow** [comment]
> The workaround is for users have to use the programmatic API (new runtime api) to define plugins?

This will work for most scenarios but it means we can't use plugins with graphql-serve, since there is no code to programatically define plugins it needs to rely on something like graphql-config.

Unless we changed how plugins need to be defined in graphql-config to:

Of course, graphql-config files can be defined in JSON too which would fix this, but ideally we should not force people to use JSON/JS when YAML seems to be the popular choice.

**Comment by machi1990** [comment]
> > If we drop `codegen` from the renaming, it will mean having to change configurations like this [aerogear/OpenVolunteerPlatform:platform/server/.graphqlrc.yml@`master`#L17](https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/server/.graphqlrc.yml?rgh-link-date=2020-06-18T12%3A57%3A08Z#L17) to add the codegen?
> 
> Yes it does mean this.
> 
> ```yaml
> plugins:
>   graphback-codegen-schema:
>     format: graphql
>     outputPath: ./src/schema
> ```
> 

+1 with dropping `codegen`.

**Comment by wtrocki** [comment]
![45jqk9](https://user-images.githubusercontent.com/981838/85027339-b687df00-b171-11ea-8adb-8a3c560c4df8.jpg)
