### ISSUE TITLE
DeltaSync - support relationships

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1456]
When requesting element with relationship we get his delta, but then all relationships involved will be not filtered by delta itself. 

Opening for the conversation as not sure if we should do more than just document it or remove relationships completely from delta return types.

**Comment by wtrocki** [comment]
Generally, it feels like we going to use delta queries directly in datastore (cc @Eunovo) which means that we might not mean to fetch any relationships.

Generating special type seems too excessive. I think I will prefer document it.

**Comment by Eunovo** [comment]
>Generally, it feels like we going to use delta queries directly in datastore (cc @Eunovo) which means that we might not mean to fetch any relationships.

@wtrocki  yes, I don't think we will need to fetch relationships. We fetch all user data anyway so we don't need nested queries. If we used nested queries we would have to normalize the data when received. Right now, I think it would be easier to just get the changes for each table/collection e.t.c

>Generating special type seems too excessive.

What special type?

**Comment by wtrocki** [comment]
Great discussion. Feeling the same as other lib does this as well. Leaving for docs

**Comment by wtrocki** [comment]
We have delta type. Check schema when running exams server..Closing as this is easy to apply
