### ISSUE TITLE
Remove existing conflict resolution from datasync offix

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1460]
We need to remove or temporary disable version based conflict resolution.
Alternatively we can add early conflict by requiring update and delete function to specify lastUpdated.

@ssd71 Whatever way you prefer. We will need to restore this later anyway.

**Comment by ssd71** [comment]
I think this issue has been addressed, we can research conflict resolution in #1445 wdyt

**Comment by wtrocki** [comment]
Would we use timestamp now instead of version?

**Comment by wtrocki** [comment]
The other issue is for delta store.
We haven't made this change and it is kinda making entire implementation unusable. See: 
https://github.com/aerogear/graphback/blob/ed6a766f15fa7dbacd2f1f0070799ec90dcab5aa/packages/graphback-runtime-mongodb/src/OffixMongoDBDataProvider.ts
