### ISSUE TITLE
Enums and filters

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1461]
I've come across some issues with enums and filters. The filters for fields only take strings. It would be nice if they could also take enums, or the typing gets kind of confusing. Look at this example query:

```graphql
        query ($dayOfWeek: DAY_OF_WEEK!) {
            findBusiness_hours(filter: {
                dayOfWeek: {
                    eq: $dayOfWeek
                }
            }) {
                items {
                    open
                    close
                }
            }
        }
```
This gives me the following error: `Variable "$dayOfWeek" of type "DAY_OF_WEEK!" used in position expecting type "String"`. Now I will have to change DAY_OF_WEEK to String, thus losing valuable type information.

**Comment by wtrocki** [comment]
Amazing feedback! We were discussing pros and cons in one of the issues (cannot find it now) and settled with the string (and generated queries reflect that), but we should really use original enums.

**Comment by craicoverflow** [comment]
ping @wtrocki

**Comment by wtrocki** [comment]
I have tried this and we have used strings for enum filtering helping us to save unneeded complexity of the schema - we will need to generate filter for every enum value which will be very very verbose.

I will see if we can generate queries that will accept enums as variable but pass them as string value (which will be correct.)
https://stackoverflow.com/questions/55113542/how-to-have-graphql-enum-resolve-strings

**Comment by machi1990** [comment]
> I will see if we can generate queries that will accept enums as variable but pass them as string value (which will be correct.)
> https://stackoverflow.com/questions/55113542/how-to-have-graphql-enum-resolve-strings

@wtrocki what's the outcome on this?

**Comment by wtrocki** [comment]
```
All that aside, if you're using Apollo as a client, whether you have to include the quotation marks or not should be irrelevant -- if you need to substitute the value for the mode input field, you should be using variables to do so, in which case (as shown above), you would be passing in a string value regardless.
```

What you will miss is tooling for strong typings and validation but result is exactly the same. Adding input type to filter every enum seems overkill. 

Mapping string / enum can be done in client side generator but most of the folks might not use that.

It is the tough choice - but if you would like some easy fast answer I would say this is docs issue

**Comment by machi1990** [comment]
> Mapping string / enum can be done in client side generator but most of the folks might not use that.

+1. 

We won't be generating filter for every enum for now as it overly verbose and overkill. However this can be revisited later I'd say.
