### ISSUE TITLE
All queries broken after upgrade to alpha 4

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1463]
Everything was working fine with alpha 1, then I decided to upgrade to alpha 4. I believe I have refactored appropriately. My model graphql schema is unchanged.

```graphql
    const { typeDefs, resolvers, services } = buildGraphbackAPI(model, {
        serviceCreator: createCRUDService({
            pubSub
        }),
        dataProviderCreator: createKnexDbProvider(db)
    });
```
Now I'm using the above. My question is, and this isn't shown anywhere in the docs that I can tell, but where is the `model` variable supposed to come from? Is it my generated schema or my model? Either way, whenever I run a query now I get something like `Cannot read property 'Users' of undefined` or `Missing service for Users`.

```graphql
query {
  getUsers(id: 1) {
    id
  }
}
```
Gives me the error: `Missing service for Users`.

```graphql
query {
  findUsers {
    items {
      id
    }
  }
}
```
Gives me the error: `Cannot read property 'Users' of undefined`.

Have I missed something obvious with my configuration?

**Comment by ssd71** [comment]
The model variable for buildGraphbackAPI is the model graphql schema.
The runtime API has changed dramatically, you have to now do the following:
```typescript
const { typeDefs, resolvers, contextCreator } = buildGraphbackAPI(modelDefs, {
  serviceCreator: createCRUDService({
      pubSub
  }),
  dataProviderCreator: createKnexDbProvider(db)
});

const apolloServer = new ApolloServer({
  typeDefs,
  resolvers,
  context: contextCreator
})
```
I believe you have to  use `contextCreator` now

**Comment by wtrocki** [comment]
Thanks @ssd71. Yep - we put breaking changes in release notes

**Comment by wtrocki** [comment]
Closing as this was api incompatibility, but feel free to reopen.

**Comment by lastmjs** [comment]
Do I need to use the `contextCreator`? I didn't have to change my context when setting up an Apollo Server before, do I need to do this now? The release notes don't make this point clear

**Comment by wtrocki** [comment]
https://github.com/aerogear/graphback/blob/master/docs/intro/serverless.md#adding-runtime-layer-to-your-application

We have docs for this
contextCreator is composable - you can call it from your function that creates context.
It can be used as function or return object to be merged with your context 
`context: {...contextCreator(context)}`
We have created it to have control how we mount services into context and have this composability for the auth, metrics logging wrappers etc.

So services will be not available using context.graphback.YourModel etc..

**Comment by wtrocki** [comment]
I will leave this to make this clear in docs

**Comment by wtrocki** [comment]
I really want to apologize for breaking API in latest versions. We are hoping to resolve all issues logged and create RC5 that should not require any change. From there we will be looking for swift release of 0.14.0 and we will try to avoid any top level API changes

**Comment by lastmjs** [comment]
It's okay, I completely understand, and the new API is getting simpler, which I really like.

I do have a concern with requiring the context though, since it adds more complexity to whatever API tool you are using to consume and resolve queries. It looks like I've got my Apollo Server working, but now using the `graphql` function from `graphql-js` is broken, with this error:

```
{"errors":[{"message":"Cannot read property 'graphback' of null","locations":[{"line":3,"column":13}],"path":["findUsers"]}],"data":null}
```

Is there something I need to do there with the context or services? Before my Apollo Server and `graphql` function just worked with the schema and resolvers (I had to make an executable schema for the `graphql` function), which was very nice and not graphback-specific.

**Comment by wtrocki** [comment]
`contextCreator(context)` require context to be passed. You can pass empty obj if needed.
We plan to separate schema creation from executable - using graphql-tools so this will make things work everywhere

**Comment by lastmjs** [comment]
How can I get the `graphql` function from `graphql-js` to work now?

**Comment by lastmjs** [comment]
I have this:

```typescript
import { graphql } from 'graphql';
// I left out other imports

const { typeDefs, resolvers, contextCreator } = buildGraphbackAPI(model, {
        serviceCreator: createCRUDService({
            pubSub
        }),
        dataProviderCreator: createKnexDbProvider(db)
    });

    const executableSchema = makeExecutableSchema({
        typeDefs,
        resolvers,
        resolverValidationOptions: {
            requireResolversForResolveType: false
        }
    });

// example

const result = await graphql(executableSchema, query, null, null, variables);
```

**Comment by wtrocki** [comment]
https://github.com/ardatan/graphql-tools

6.x GraphQL tools make executable schema will work

**Comment by wtrocki** [comment]
Also you might use GraphQL express. I will build GraphQL.js example tommorow.

**Comment by lastmjs** [comment]
Sounds good. The reason I'm using `graphql` is for my application GraphQL server. That server is executing queries against my schema that Graphback generates, so I don't want to put an http server like express in front of that, I just want a server-side API like `graphql`

**Comment by wtrocki** [comment]
Check GraphQL express API

https://graphql.org/graphql-js/express-graphql/

Context in your case is null but should be graphback one

**Comment by lastmjs** [comment]
Thanks so much, I finally see that `graphql` from `graphql-js` takes a context parameter, got it working now.

**Comment by wtrocki** [comment]
We have released official version. Feel free to reopen if you still see this issue.
