### ISSUE TITLE
[DataSync] Broken delete operation 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1465]
It looks like deletion and edit input types are not properly created.
They not accepting the updatedAt field which is critical for the conflict resolution.

Relates to #1460 

Error
```
message: "Variable "$input" got invalid value { id: "5ee7a844cfd59c84cd672d25", title: "123", description: "123", version: null, status: "OPEN", type: null, priority: null, public: null, startDate: "2020-06-15T16:56:29.258Z", payload: null, createdAt: "1592240196780", updatedAt: "1592240196780" }; Field "createdAt" is not defined by type MutateTaskInput."
1: {,…}
```

**Comment by wtrocki** [comment]
FYI @ssd71

**Comment by ssd71** [comment]
@wtrocki I think we need another issue for conflict or can we discuss here?

**Comment by wtrocki** [comment]
see linked issue above. Requires update

**Comment by wtrocki** [comment]
@ssd71 Any work needed here?

**Comment by ssd71** [comment]
It does accept the updatedAt field now, I think not

**Comment by wtrocki** [comment]
Closing then. Good job!
