### ISSUE TITLE
graphql-serve CRUD service not attached

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/graphback#1468]
Trying to use the latest alpha release of graphql-serve, I get the following error message when trying to run queries and mutations:
`"message": "Missing service for Todo",`

#1453 needs to be added to graphql-serve

**Comment by machi1990** [comment]
Is related to https://github.com/aerogear/graphback/issues/1448? @craicoverflow

**Comment by craicoverflow** [comment]
It is a separate issue that existed before #1453
