### ISSUE TITLE
Loading of the model files is dependent of the working directory.

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1470]
See: 
https://github.com/aerogear/graphback/pull/1469

**Comment by craicoverflow** [comment]
Why not use `__dirname` to set the template index file as the relative path to work from?

**Comment by wtrocki** [comment]
Because it is different when working with ts-node or dist (dist has all in root)

**Comment by machi1990** [comment]
`process.cwd()` could work here, assuming that the `model` is always on current working directory (where the process is launch).

**Comment by wtrocki** [comment]
It is not. Model should be part of the imports or even as TS file

**Comment by craicoverflow** [comment]
You could start the server from any directory, even `$HOME` - So `process.cwd()` would equal to `$HOME`.

Good point. Importing a ts file makes sense then, or maybe something like [graphql-import-node](https://github.com/ardatan/graphql-import-node) might work.

**Comment by craicoverflow** [comment]
Do we still see this as an issue? The obvious solution is to load the model as TS files.

**Comment by wtrocki** [comment]
> The obvious (easiest) solution is to load the model as TS files.

Not possible due to offlix cli integration, forms integration (entire client side stuff that uses graphback) but it is not visible to grahback maintainers.
