### ISSUE TITLE
[DataSync] Add TTL index for soft deletion

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1472]

**Comment by wtrocki** [comment]
Wondering what TTL has to do to the GraphQL schema? Do you think users should configure it using GraphQL mutations?

I thought I will be set internally by some config and managed internally by some Cron job etc.

**Comment by ssd71** [comment]
My bad, I should provide some context.

>Wondering what TTL has to do to the GraphQL schema? Do you think users should configure it using GraphQL mutations?

Not really, I was thinking about setting it internally.

> I thought I will be set internally by some config and managed internally by some Cron job etc. DateTime is supported on mongo so we have all enabled

I have some thoughts about this:
MongoDB has a feature called TTL Indexes which only works on Date values [<sup>1</sup>](https://stackoverflow.com/questions/53766763/how-to-create-ttl-index-on-long-timestamp-in-mongodb), if we were to use this feature, we would need to store the timestamps as Date values in the database. This wouldn't normally be a problem except when a query returns a Date value, it will show up as an ISO Datestring in the response of the query and not as a timestamp.

Of course, this feature is not very extensible because we will obviously need a completely different approach for Knex data sources, so I am open to using cron or some equivalent approach.

**Comment by wtrocki** [comment]
Persistent Cron jobs would be the key. TTL is internal - no need to return it

**Comment by ssd71** [comment]
Cool! I'll update the issue!

**Comment by ssd71** [comment]
I have been ruminating quite a bit about this(quite honestly a bit lost here :D) and I'd love it if you could just give some feedback about this:

1.  A place I could see cron jobs happening is putting a script in templates or something similar so there is a separate 'entity' that only manages the database, wdyt? Does this sound wasteful?

> TTL is internal

2. Do you mean that we should have a TTL field in documents that says when to expire documents?

**Comment by wtrocki** [comment]
`Soft deletes` do not delete data from the collection. For some use cases that is ok, but in cases where data is deleted frequently, it can be a problem. If we keep deleted data indefinitely it can lead to overgrown database and increased memory usage. To prevent from that we can enable configurable job (for example once a week will delete week old `soft deletes`). There are numerous npm libraries that support this use case (it is very common to prune some data on timely basis). I do not want to give you solution on silver platter but this should be relatively simple to do with some library

**Comment by ssd71** [comment]
Yep, I was a bit concerned about concurrency troubles you see :D, I will spike and ping you on it later today, thanks!

**Comment by wtrocki** [comment]
Concurrency troubles? please elaborate

**Comment by ssd71** [comment]
I was wondering if we would have issues when scaling up: like multiple cron jobs would be running for doing the same thing

**Comment by wtrocki** [comment]
Check npm - there will be no issues with scaling as most Cron jobs have protection against that by storing metadata in dB :)

**Comment by machi1990** [comment]
Closing as this was this fixed by #1883 which superseded #1525
