### ISSUE TITLE
Keycloak/authz breaking Subscription mechanism. 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1474]
Subscription topic is not being enabled properly.
There is no possibly to override topic to something like

`graphql/${objectName}-${triggerType}`

**Comment by wtrocki** [comment]
authz package should be rebuild to work better with the latest runtime. 
Critical issue.

**Comment by machi1990** [comment]
@wtrocki feels like https://github.com/aerogear/graphback/pull/1508 and https://github.com/aerogear/graphback/pull/1529 addressed this?

**Comment by wtrocki** [comment]
Waiting ing for release to confirm

**Comment by wtrocki** [comment]
Fixed. Subscriptions are now enabled and topics are sent to the right place.

CC @craicoverflow

**Comment by machi1990** [comment]
> Fixed. Subscriptions are now enabled and topics are sent to the right place.

@wtrocki thanks for reporting back. Can the issue be closed?

**Comment by wtrocki** [comment]
Tested
