### ISSUE TITLE
npm audit: lots of security vulnerabilities

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1480]
Running on npm audit with `0.14.0-alpha4` of `graphback`, `graphback-cli` and `@graphback/runtime-knex` prints a lot of vulnerabilities.

It looks like the main culprits are `yargs-parser`, `safe-eval`, and `kind-of`.

**Comment by wtrocki** [comment]
Yes. This is exactly on our radar. You can pin vulnerabilities in your lock file for the moment

**Comment by wtrocki** [comment]
We have released 0.14.0 with the latest versions available. Some of the vulnerabilities were resolved
