### ISSUE TITLE
not in filter

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1495]
I think there might be an issue for this already, but we have `in` for filtering based on arrays, it would be nice to have `not in` as well.

**Comment by wtrocki** [comment]
not is grouping operator and I believe that this is already possible:

`not: { in: [] }`

However, I have no way to test it at the moment and do not see unit tests for this use case.

**Comment by machi1990** [comment]
> `not` is grouping operator and I believe that this is already possible:
> 
> `not: { in: ['whatever'] }`
> 
> However, I have no way to test it at the moment and do not see unit tests for this use case.

Yes, the suggestion should work. I've added a few tests in https://github.com/aerogear/graphback/pull/1733
