### ISSUE TITLE
Draft directives used for generation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#151]
We need to have discussion about directives that can be used for generation. 
We can use `@Model` or directive per each operation. Additionally, we might need to have Data model directives that will define how database is created. 

We could also do @REST directive for generating restful API calls.

Did I missed anything

**Comment by ankitjena** [comment]
I think we should provide only some key directives, like `@sub` or `@paginate`(in future) for example. And read the others crud operations through the generator config in `config.json`

Will the `@rest` directive allow for integration with sofa.

**Comment by wtrocki** [comment]
Sofa will be integrated automatically. 

>  And read the others crud operations through the generator config in config.json

This will now allow type specific generation. Config.json is global only so id you do not want to have things done globally you will not need to apply it to every possible type.

**Comment by ankitjena** [comment]
> This will now allow type specific generation. Config.json is global only so id you do not want to have things done globally you will not need to apply it to every possible type.
Ah right, missed that.

Then this will be the default for both the types and if we want to alter any other type then directives. Seems good.

**Comment by ankitjena** [comment]
Have dropped the @Model and created individual directives

**Comment by wtrocki** [comment]
Docs?

**Comment by ankitjena** [comment]
Added in pr #180
