### ISSUE TITLE
graphback-schema plugin outputPath specify filename

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1512]
As far as I can tell, the `outputPath` for the `graphback-schema` plugin only allows me to specify a path, and not a filename. I would like the option to specify an exact filename, and not have it necessitate creating a directory. Right now I have to have the generated schema in its own directory. Ideally for me, I want my model and generated schema files in the same directory as siblings

**Comment by wtrocki** [comment]
Makes sense for me. We going to change that soon. 

Worth to mention that for runtime we no longer need schema as file, but we giving devs this capability for simplicity and integration with other tools.

**Comment by craicoverflow** [comment]
You can achieve this with the `outputFileName` plugin config:

```ts
new SchemaCRUDPlugin({
  outputFileName: 'mySchema',
  outputPath: './src/schema-dir',
  format: 'graphql'
})
```

https://graphback.dev/docs/plugins/crud-schema#plugin-config

**Comment by wtrocki** [comment]
Still. There is always single file output so we should use single variable instead
