### ISSUE TITLE
Missing mutation input fields for embedded relationships

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1540]
If we supported embedded relationships on non-model GraphQL types, there should also be a way to insert that field or filter on it.

```gql
""" @model """
type Task {
  id: ID!
  version: Int
  title: String!
  description: String!
  status: String!
  """
  @db(type: 'json')
  """
  creationMetadata: CreationMetadata
}

type CreationMetadata {
  createdDate: String
  createdBy: User
}
```

There are no input fields for this embedded relationship.

```gql
input CreateTaskInput {
  id: ID
  version: Int
  title: String!
  description: String!
  status: String!
  creationMetadata: CreationMetadata # Let's add this
}
```

**Comment by wtrocki** [comment]
Awesome! Is that blocking?

**Comment by craicoverflow** [comment]
Alpha release - no
0.14.0 - maybe. It depends on how much of a priority it is.

It is not a common use case in Postgres (still good to support it)
But I can see it being commonly needed in Mongo.

The data can be retrieved if it already exists, but if it cannot be inserted then it is almostr useless to have it as a feature.

Relates to https://github.com/aerogear/graphback/issues/1432

**Comment by craicoverflow** [comment]
This is needed in 0.14.0 otherwise it is useless to have embedded relationships.
