### ISSUE TITLE
Migrations and scalars

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1552]
I just started trying out the migrations, unfortunately they didn't work perfectly. Perhaps I don't understand how to use scalars properly. For example, I'll need to have Date or DateTime types, BigInt, etc that should map to underlying postgres types directly. Is that what the `scalarMap` option is in graphql-migrations?

**Comment by machi1990** [comment]
Hi @lastmjs there are two ways to provide custom db type:
- By using the `@db(type: 'date')` annotation on your field
- By using the `scalarMap` options, which is a function that takes three arguments `(field: GraphQLField, fieldType: GraphQLScalarType,, dbAnnotation: any)`, depending on the field type you could return the [`TableColumnTypeDescriptor`](https://github.com/aerogear/graphback/blob/fa62e1a5995372bd9baa519e29157365d9bd8a53/packages/graphql-migrations/src/abstract/getColumnTypeFromScalar.ts#L5)
A good example of this function is https://github.com/aerogear/graphback/blob/fa62e1a5995372bd9baa519e29157365d9bd8a53/packages/graphql-migrations/src/abstract/getColumnTypeFromScalar.ts#L18-L129

**Comment by machi1990** [comment]
Hi @lastmjs, thanks for opening the issue, the solution suggested above should work and we have gone a step further into documenting the [`scalarMap`](https://graphback.dev/docs/next/graphql-migrations/api#scalar-mapping) option as part of our next release.
