### ISSUE TITLE
Cannot use existing update, delete queries as we require "lastUpdatedAt" field that is not in query

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1573]
Cannot use existing update, delete queries as we require lastUpdated at field that is not in query
Query should have this in Clint side plugin..

This happens for datasync but it might be also for delta

CC @ssd71

**Comment by ssd71** [comment]
Is this about being unable to update existing documents which do not have `updatedAt`?

**Comment by wtrocki** [comment]
This is about client side plugin that generates client side queries. Those queries do not have updated at field that is required.

**Comment by machi1990** [comment]
> Is this about being unable to update existing documents which do not have `updatedAt`?

I guess we'll need a separate issue for this then?

**Comment by wtrocki** [comment]
@ssd71 This is probably fixed

**Comment by machi1990** [comment]
> @ssd71 This is probably fixed

@ssd71 is this issue fixed?

**Comment by ssd71** [comment]
> @ssd71 is this issue fixed?
@machi1990 `updatedAt` field will no longer be required by update mutations in datasync after  #1771 , that is what this specific issue was about

But after conflicts are added, this issue will arise again with a different field (`_version`)

AFAIK we still don't generate sync queries(or anything for datasync) in client side generator plugin so maybe we should discuss if we should be doing that?

**Comment by machi1990** [comment]
> > @ssd71 is this issue fixed?
> > @machi1990 `updatedAt` field will no longer be required by update mutations in datasync after  #1771 , that is what this specific issue was about
> 
> But after conflicts are added, this issue will arise again with a different field (`_version`)
> 
> AFAIK we still don't generate sync queries(or anything for datasync) in client side generator plugin so maybe we should discuss if we should be doing that?

The issue mentions about the inability to use `delete / update` mutations, so I am wondering if https://github.com/aerogear/graphback/blob/master/packages/graphback-datasync/src/DataSyncPlugin.ts#L81 is not enough to make the conflict field generated.

**Comment by wtrocki** [comment]
Actually this issue will be resolved as

Adding just datasync will no longer require version on edits. We do not use graphback for client side queries in offix - we have our own generation.

Leaving for @ssd71 to close or ask questions
