### ISSUE TITLE
More reliable way of extending CRUDService?

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1582]
The current way we extend CRUDService for DataSync for example is subclass it and add more methods (sync method for DataSync), Does this feel kinda janky to you guys? I was wondering if there was some better way to do this?

For example, using DataSync with `@graphback/keycloak-authz` becomes kinda difficult because of the way [GraphbackProxyService](https://github.com/aerogear/graphback/blob/master/packages/graphback-core/src/runtime/GraphbackProxyService.ts) works (looking at datasync-starter)

Feel free to close if this is already under discussion or seems redundant

I also wonder if there is some broader usecase for this that would make it worth developing for (Do we see people making custom services? :thinking:)

**Comment by wtrocki** [comment]
I actually though that proxy service would be much easier here. Idea is that you can create service by extending it and chain them, but this is still not simple

**Comment by machi1990** [comment]
What's the status on this? 

/cc @ssd71

**Comment by ssd71** [comment]
@machi1990 I don't believe that this issue has been addressed afaik

**Comment by machi1990** [comment]
> @machi1990 I don't believe that this issue has been addressed afaik

Ah totally missed this in the pile of notifications I receive. Sorry for the late reply. 

@ssd71 would you have a suggestion? A snippet code maybe that can drive the discussion?

**Comment by ssd71** [comment]
@machi1990 
I remember being lost on this and haven't thought about it since, sorry :P

**Comment by machi1990** [comment]
> @machi1990
> I remember being lost on this and haven't thought about it since, sorry :P

Hi @ssd71 good to read from you. Thanks for chiming in. 
Okay, I'll let you decide the best course of action regarding this issue ;-)

**Comment by wtrocki** [comment]
Closing. While it is ackward to extend stuff we are feature complete on it. Any change will affect user API so best to keep it this way
