### ISSUE TITLE
Schema output path is not working properly with folders

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1593]
/graphback generate
<b>Generation failed: Error: ENOENT: no such file or directory, open '/server/src/schema/schema.graphql'</b>

**Comment by craicoverflow** [comment]
To help resolve this faster, could you tell me what version of Graphback you are using?

**open '/server/src/schema/schema.graphql'**

That to me looks like an absolute path to nowhere.

**Comment by wtrocki** [comment]
Obfuscating my path structure when dumping logs. this is absolute path

**Comment by craicoverflow** [comment]
It looks to me like you are using the ClientCRUDPlugin which is trying to open `$CODE/server/src/schema/schema.graphql'` but this does not exist.

Are you sure the file exists?

**Comment by wtrocki** [comment]
I have tried it again. It looks like there was some problem with location where I executed command - I have multiple configs :(

**Comment by craicoverflow** [comment]
Still a bug then, but probably covered by https://github.com/aerogear/graphback/issues/1470
