### ISSUE TITLE
When no relationship annotation is defined, invalid input fields are added to input type

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1604]
From https://github.com/aerogear/graphback/pull/1574#pullrequestreview-438421423

Defining this model will create a non-model input type for Note:

```gql
""" @model """
type Note {
  id: ID!
  title: String!
  description: String
  comments: [Comment]!
}

""" @model """
type Comment {
  id: ID!
  text: String
  description: String
}
```

Created an input type 
```
input MutateNoteInput {
  id: ID!
  title: String
  description: String
  comments: ID
}
```

This should either:

a) throw an error because there is no relationship annotation on `Note.comments`
b) Detect an implicit relationship and only create model input types.

**Comment by machi1990** [comment]
Option (a) sounds more reliable to me. The thing about (b) is it is hard to know what kind of relationship it is.

E.g when you have a model like this:
```graphql
""" @model """
type First {
  id: ID!
  second: Second
}

""" @model """
type Second {
  id: ID!
}
```  

Is it a `@oneToOne` relationship with `First` as the relationship owner or `@onToMany` relationship with `Second` as the owner of the relationship? 

Having said that, auto detection of relationship will be a killer feature and certainly worth a separate issue till everything has been figured, for now I'd say we go with (a).
  
/cc @craicoverflow @wtrocki WDYT?

**Comment by craicoverflow** [comment]
For now at least, we should go with **a** I think. As you said implicit relationships with be a brilliant feature but difficult to get right without unintended consequences, and right now we are targeting stability. Another thing about **b** is it would be challenging to map multiple relationship fields between two models, because at least one of these would require an annotation. This would require extra validation. The fact that every relationship requires an annotation means the user supplies mapping information.

On these grounds, let's go with **a** :smile:
