### ISSUE TITLE
Move `init` command to new micro-CLI `create-graphback`

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1624]
`graphback-cli` requires a peer dependency of `graphql` to execute the generate command, which is used to generate GraphQL resources such as queries, and schema.

The CLI also executes `init`, which would typically be executed outside of a folder with any grapHQL dependency. This causes #1530 to happen.

These two commands are incompatible to have in the same CLI package. It makes sense to move the `init` command to a different package which will not require `graphql` to be installed.

Let's move the `init` command/code to [aerogear/create-graphql](https://github.com/aerogear/create-graphql)

**Comment by craicoverflow** [comment]
This will fix #1530

**Comment by craicoverflow** [comment]
`create-graphql` does a lot of cool file generation with Yeoman. It would be a lot of work to retrofit this to use Graphback.

What about extracting the init command code to a package `create-graphback-app`?

Then you can do: 

```bash
npm init create-graphback-app my-cool-project
```

Or

```bash
npx create-graphback-app my-cool-project
```

Then work could be done on create-graphql post v1 release to make it compatible with Graphback while staying true to its original file generation.

**Comment by wtrocki** [comment]
I have no strong opinion, but this is going to create yet another CLI. 
Less then better IMHO. Can we just add graphback to existing stuff?

**Comment by craicoverflow** [comment]
Are we prepared to also support what currently exists in create-graphql?
Or is the plan to remove it all and just have Graphback options like from Graphback CLI?

I know create-graphql does not get much current usage, so maybe it is fine to scrap it all.

**Comment by wtrocki** [comment]
> Or is the plan to remove it all and just have Graphback options like from Graphback CLI?

We give the same features by different way. Cli also generates resolves.. 
I would simply copy paste our current CLI and remove non init stuff there. 
That is all.

**Comment by craicoverflow** [comment]
> We give the same features by different way. CLI also generates resolves..

The Graphback CLI does not currently generate resolvers.

create-graphql does not generate a schema file, it generates several JavaScript files that export `GraphQLObjectType` with mutation and queries as fields on the object (not separate like the format from graphql-tools).

Check its commands for more: https://github.com/aerogear/create-graphql/blob/master/docs/Commands.md

Also, I could not find anything to suggest that it currently generates TypeScript files - only JS.

**Comment by wtrocki** [comment]
Agrement - No create-graphql for 0.14.0. We can have create-graphback for the moment
