### ISSUE TITLE
Filters on "id: ID" field not working for mongo db

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1625]
I have a use case where I want to perform a not in filter:

```
query {
  findVolunteers(
    filter: { not: { id: { in: ["5ef626c190701a3b90ebb24f", "5ef9c631da553f262c7a95dc"] } } }
  ) {
    items {
      id
    }
    count
  }
}
```

Which should return all volunteers whose id is in not equal to the one passed in the array. 

But this returns 
```
{
  "data": {
    "findVolunteers": {
      "items": [
        {
          "id": "5ef6262d90701a3b90ebb227"
        },
        {
          "id": "5ef6266890701a3b90ebb237"
        },
        {
          "id": "5ef6269490701a3b90ebb245"
        },
        {
          "id": "5ef626c190701a3b90ebb24f"
        },
        {
          "id": "5ef626e690701a3b90ebb25b"
        },
        {
          "id": "5ef6271a90701a3b90ebb26a"
        },
        {
          "id": "5ef9c631da553f262c7a95dc"
        }
      ],
      "count": 7
    }
  }
}
```

With the `5ef626c190701a3b90ebb24f` and `5ef9c631da553f262c7a95dc` present while they should have been filtered out.

/cc @craicoverflow @wtrocki

**Comment by machi1990** [comment]
I guess it comes from the transformation of `id` to `_id`. 

Because even the `eq` is failing.

```graphql
query {
   all: findVolunteers {
    items {
      id
    }
    count
  }
  in: findVolunteers(
    filter: { id: {
      in:  ["5ef626c190701a3b90ebb24f", "5ef9c631da553f262c7a95dc"]
    }}
  ) {
    items {
      id
    }
    count
  }
  
  eqFirst: findVolunteers(
    filter: { id: {
      eq:  "5ef626c190701a3b90ebb24f"
    }}
  ) {
    items {
      id
    }
    count
  }
  
  eqSecond: findVolunteers(
    filter: { id: {
      eq:  "5ef9c631da553f262c7a95dc"
    }}
  ) {
    items {
      id
    }
    count
  }
}
```

gives 
```json
{
  "data": {
    "all": {
      "items": [
        {
          "id": "5ef6262d90701a3b90ebb227"
        },
        {
          "id": "5ef6266890701a3b90ebb237"
        },
        {
          "id": "5ef6269490701a3b90ebb245"
        },
        {
          "id": "5ef626c190701a3b90ebb24f"
        },
        {
          "id": "5ef626e690701a3b90ebb25b"
        },
        {
          "id": "5ef6271a90701a3b90ebb26a"
        },
        {
          "id": "5ef9c631da553f262c7a95dc"
        }
      ],
      "count": 7
    },
    "in": {
      "items": [],
      "count": 0
    },
    "eqFirst": {
      "items": [],
      "count": 0
    },
    "eqSecond": {
      "items": [],
      "count": 0
    }
  }
}
```

**Comment by machi1990** [comment]
In what we were trying to achieve at OVP we have this workaround:  
https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/server/src/resolvers/custom-resolvers.ts#L157

The actual value is build here:
Using https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/server/src/resolvers/custom-resolvers.ts#L25


Example query is here. https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/server/src/resolvers/custom-resolvers.ts#L30

**Comment by machi1990** [comment]
@craicoverflow @wtrocki renamed this issue to capture what is really not working. 

see the above workaround used to get it working in OVP.

**Comment by machi1990** [comment]
For `filtering on primary key` to work seamless in MongoDB we need to either:

- Do an update right after insertion in the `MongoDBDataProvider` to make sure that the "`id`" is set - https://github.com/aerogear/graphback/blob/master/packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts#L48. The advantage of this is that the id field will always be set and we can filter against it. The disadvantage of this solution is an extra dangling "`id`" field in the document. Also, having to perform two operations just for the creation. I've tried this by manually editing the MongoDBDataProvider to add the update line and this works. 

- Always requiring it to be `_id: ObjectID`, and automatically providing the ObjectID scalar for it. I've done this in my test by manually changing the model and creating the ObjectId resolver. And it works but seems like a lot of work for the user, ideally we should be creating the resolver ourselves and have it as part of the resolvers created by our schema.  There is a very good discussion about doing this here https://github.com/aerogear/graphback/issues/1547.

**Comment by wtrocki** [comment]
>  And it works but seems like a lot of work for the user, ideally we should be creating the resolver ourselves and have it as part of the resolvers created by our schema.

Yes. That should be the thing. 
There are couple big changes for this:

- Embedded scalar support
- MongoDB working only with _id

All of those are 0.15.0 targets.
My proposal will be to move this to 0.15.0 target as it is not possible to fix that without significant amount of work or hacks that will be invalidated in 0.15.0.

Target for us would be to not let community to wait so long for 0.15.0 so we can document this as well known limitation (link this particular bug)

**Comment by machi1990** [comment]
> > And it works but seems like a lot of work for the user, ideally we should be creating the resolver ourselves and have it as part of the resolvers created by our schema.
> 
> Yes. That should be the thing.
> There are couple big changes to resolve this problem:
> 
> * Embedded scalar support
> * MongoDB working only with _id

Yes, this will require solving this issue https://github.com/aerogear/graphback/issues/1547 at least.
 
> All of those are 0.15.0 targets.
> My proposal will be to move this to 0.15.0 target as it is not possible to fix that without significant amount of work or hacks that will be invalidated in 0.15.0.

> Target for us would be to not let community to wait so long for 0.15.0 so we can document this as well known limitation (link this particular bug)

The proposal makes sense and I was thinking the same.
