### ISSUE TITLE
Should Knex be a peerDependency on `@graphback/runtime-knex`?

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1640]
Knex is required to be installed into the template to create the database. Knex is also installed as a dependency of `@graphback/runtime-knex`.

This might make it difficult for users to add Graphback to their existing project if they already use a different version of Knex to our libraries. 

Would there be a benefit of letting this be acquired as a peerDependency from the template?

**Comment by wtrocki** [comment]
Hard topic because knex typings are.. not great and what you mentioning works only in theory. Let's discuss

**Comment by craicoverflow** [comment]
Yeah that is the one thing that could make this unreliable. From my recollection however, Knex typing issue only happens when there is a difference between `knex` and `@types/knex` versions.

...


Actually it looks like `@types/knex` is not needed any more and it has actually been removed:

https://github.com/aerogear/graphback/blob/7eecb246b6d4fc54c5f97e29ddb8d78f73adf153/packages/graphback-runtime-knex/package.json#L41

https://www.npmjs.com/package/@knex/types

I tried to install it to see what happens and got this:

```
This is a stub types definition. knex provides its own type definitions, so you do not need this installed.
```

**Comment by wtrocki** [comment]
Yes. We haven't used knex types for long time. This do not change.fact that types there are.. not great and patch updates are breaking stuff

**Comment by machi1990** [comment]
@craicoverflow Is this still up for discussion or we can close it for now?

**Comment by craicoverflow** [comment]
By not having this we are actually limiting the developer's Node.js server application to use exactly the same version of Knex as Graphback uses. 

I tested it out and setting Knex as a peer dependency works fine. What do yo you think about us adding this @machi1990 @wtrocki ?

**Comment by machi1990** [comment]
> By not having this we are actually limiting the developer's Node.js server application to use exactly the same version of Knex as Graphback uses.
> 
> I tested it out and setting Knex as a peer dependency works fine. What do yo you think about us adding this @machi1990 @wtrocki ?

I have no strong opinion on this. If the typing issues that were there previously are no longer outstanding, what you are saying makes sense. So +1.

**Comment by craicoverflow** [comment]
Yes, those typings issues are gone since `@types/knex` is gone and types are part of the main library.

**Comment by machi1990** [comment]
Great. You've me onboard.

**Comment by wtrocki** [comment]
peerDependency.. but remember..

# THIS IS BREAKING CHANGE

**Comment by craicoverflow** [comment]
Is it? Nothing changes from the user side - they have to have knex as a dependeny regardless.

**Comment by wtrocki** [comment]
> `they have to have knex as a dependency in current release`

Ok. I was thinking that they will be just use knex that we provide.

**Comment by craicoverflow** [comment]
Nope, it has to be installed in the template AND is installed in Graphback. This is why it is a current limitation - user can never have a different version of Knex from the one that Graphback is using.
