### ISSUE TITLE
selection fields should be namespaced by type

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1641]
looks like we have done really ugly hack that covered issue but generally selection fields should be namespaced by query or even part of the different object. adding things to context during execution phase might be tricky. Context can be overriden etc.

**Comment by wtrocki** [comment]
@machi1990 I think we need to extract services layer of graphback and have them in root context.
Also we need to expose db providers into the context as well for data driven operations and add ability to execute any custom operation.

This will improve overall experience with the library for local development. 
As seen in #1643 this looks very bad comparing to any other library

**Comment by machi1990** [comment]
> @machi1990 I think we need to extract services layer of graphback and have them in root context.
> Also we need to expose db providers into the context as well for data driven operations and add ability to execute any custom operation.

Do you seen db providers in the root context too? 
 
> This will improve overall experience with the library for local development.
> As seen in #1643 this looks very bad comparing to any other library

I think we should have a way to retrieve a service by name as proposed in #1643 with something like `context.service<User>('User')` or `context.getService('User')` etc. If we add db providers into the root context, we should also have way to retrieve db providers by name. 

We'll then have something like:
```ts
/**
 * Map model names to a CRUD service
 */
export interface GraphbackServiceConfigMap {
  [modelName: string]: GraphbackCRUDService
}

/**
 * Map model names to a db provider
 */
export interface GraphbackDataProviderConfigMap {
  [modelName: string]: GraphbackDataProvider
}

/**
 * Contains resolver options
 */
export interface GraphbackResolverOptions {
  selectedFields: string[],
  aggregations?: { // A map that indicates the type of aggreation that can be perfomed withing the current context
    count?: boolean
  }
}

/**
 * GraphQL context interface according to Graphback runtime layer format
 */
export interface GraphbackContext {
    services: GraphbackServiceConfigMap,
    providers: GraphbackDataProviderConfigMap, 
    service: <T>(name: string) => GraphbackCRUDService<T>, 
    provider: <T>(name: string) => GraphbackDataProvider<T>, 
    options: GraphbackResolverOptions
}
```

Hoping that we maybe not add anything graphback related if we remove the `graphback` from root context. 

WDYT? 
/cc @craicoverflow @wtrocki

**Comment by wtrocki** [comment]
As for db providers we need to be careful as skipping services can mean bugs like missing subscription when creating updating etc 

As for API - this looks ok but I really like how prisma does it `context.user.find` etc.

**Comment by machi1990** [comment]
> As for db providers we need to be careful as skipping services can mean bugs like missing subscription when creating updating etc
> 

Yes, basically if you direct use db providers you are on your own. 

> As for API - this looks ok but I really like how prisma does it `context.user.find` etc.

I'd like to know why?

**Comment by craicoverflow** [comment]
> As for API - this looks ok but I really like how prisma does it `context.user.find` etc.

Same, the whole reason we changed that was to avoid clashes with custom user context models. This is maybe a case of Graphback trying to cater for all possibilities and sacrificing a good API and overall usability.

Having the services on the root like that means it would be non-typed right? it would need to be at least one key down to create a service map.

I personally liked when we had `context.models.Note.findOne()` as it is easy to destructure the context to that level.
