### ISSUE TITLE
Missing authorization checks on oneToOne relations

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1644]
Thanks to https://github.com/aerogear/graphback/pull/1633 we have ability to add authorization rules for relations in our crud model.  But this feature is current missing for the `oneToOne` and possibly `manyToOne` relationship.

See https://github.com/aerogear/graphback/pull/1633#discussion_r448826859 and https://github.com/aerogear/graphback/pull/1633#discussion_r449111106 for context.

**Comment by wtrocki** [comment]
I think this is docs issue as mentioned in:
https://github.com/aerogear/graphback/issues/1638

Due to architecture manyToOne are not batched but still covered by Auth. I think there is issue created for reviewing batch for ManyToOne
