### ISSUE TITLE
[MongoDB]Using DB generated Date values for createdAt, updatedAt

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1646]
The proposal is to use Date values generated by MongoDB for uniformity for both createdAt and updatedAt
One possible way of doing this would be to use `$currentDate` but note that as it is an update parameter in MongoDB and so to use it for inserts we may have to either:
- call insertOne then updateOne
- call updateOne with `upserts: true`

wdyt?

We can also emulate our current functionality of timestamp as numbers quite easily I think (using MongoDB projection operators)

I also think this way it will (hopefully) be a painless update when we switch to Date Scalars

**Comment by wtrocki** [comment]
`call updateOne with upserts: true` - Sounds reasonable to me

**Comment by machi1990** [comment]
@ssd71 @wtrocki is this issue still of actuality? I remember seeing in our of @ssd71  PR's about opting out this approach, but cannot remember the exact details. Just checking if it is up to date or can be closed.

**Comment by ssd71** [comment]
@machi1990  I wanted to try a hand at this, because DB provided timestamps would be more accurate and more accuracy would've better suited conflict detection and resolution in datasync, but since we decided against using timestamps for conflicts (and decided use a `_version` field instead), I feel that this would be more troublesome rather than helpful at this point

Need you guys' opinion as well, as I may be mistaken or confused

**Comment by machi1990** [comment]
> @machi1990 I wanted to try a hand at this, because DB provided timestamps would be more accurate and more accuracy would've better suited conflict detection and resolution in datasync, but since we decided against using timestamps for conflicts (and decided use a `_version` field instead), I feel that this would be more troublesome rather than helpful at this point
> 
> Need you guys' opinion as well, as I may be mistaken or confused

@ssd71 thanks for the context. I feel like the need for this issue is gone now that we shift focus towards `_version`.

**Comment by wtrocki** [comment]
YEP. Good to close
