### ISSUE TITLE
GraphQL-Serve has invalid doc command

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1648]
https://www.npmjs.com/package/graphql-serve

gqls is mixed with gqlserve - not sure what to use.

**Comment by wtrocki** [comment]
gqlserve is much better. gqls is clashing in my system with git aliases from zsh

**Comment by wtrocki** [comment]
Also we renamed it without notice so we should restore to gqlserve

**Comment by wtrocki** [comment]
Datasync option is not documented :)

**Comment by machi1990** [comment]
> gqlserve is much better. gqls is clashing in my system with git aliases from zsh

We'll have `gqlserve serve models --port=8080`, won't that make the `serve` redundant? 

> Also we renamed it without notice so we should restore to gqlserve

Where was it renamed? For me to grab some context.

**Comment by wtrocki** [comment]
if you look into history it should show all details. 
Renaming CMD is quite bad approach as people might already have it installed etc.

**Comment by machi1990** [comment]
> if you look into history it should show all details.

Found this https://github.com/aerogear/graphback/pull/865/commits/23cf7be73b76e52d8350464a18cda6d5fea82588 but does not say much. 
 
> Renaming CMD is quite bad approach as people might already have it installed etc.

This can be easily fixed.

**Comment by craicoverflow** [comment]
> We'll have `gqlserve serve models --port=8080`, won't that make the `serve` redundant? 

I think this is the original reason `gqls` was chosen.

**Comment by wtrocki** [comment]
Hi
Anything would worki for me as long we are consistent
