### ISSUE TITLE
Add graphql-serve template to promote headless mode 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1650]
GraphQL serve is mentiuoned in docs as fun fact. Where it is offering a lot of benefits for the  sample app use cases etc.

https://github.com/wtrocki/graphql-serve-example

**Comment by craicoverflow** [comment]
Thoughts on this still? I personally think a template is overkill. However the CLI could generate a schema file as a getting started:

```ts
$ gqlserve init schema.graphql
```

This would mean no need for a template in Graphback (which would need to be created through `create-graphback`?) and actually have a quicker way to get started with gqlserve.
