### ISSUE TITLE
Graphback overwrites custom query with same name

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1656]
Given this model:

```gql
type Query {
  getNote(id: ID!, test: String): Note
}
```

Graphback will ignore it and still use the generated query:

```gql
type Query {
  getNote(id: ID!): Note
}
```

**Comment by machi1990** [comment]
Discussion we had in https://github.com/aerogear/graphback/issues/1597 could be useful here too.

**Comment by craicoverflow** [comment]
See #1670 

The problem is that `buildModel` is called multiple times, so the approach taken here will not work.

The first time `buildModel` is called it is using the original data model schema, which does not have any generated CRUD API yet. At this point it is easy to identify custom queries that have a clashing name. This PR uses this information to update the CRUD options on the ModelDefinition. The main benefit of this is there is a single source of truth for the model's CRUD config.

The next time `buildModel` is called, it is using the schema which has the Graphback queries generated. It sees this as custom user queries and updates the CRUD config accordingly, so no resolvers are created.

The obvious quick solution is to not update the model CRUD config from the custom queries, instead calculating this when needed. The issue I have with this is there are now two truths - The model CRUD config will say that the `create` CRUD is enabled (as an example), but Graphback does not generate this because the user supplied their own custom create query in the schema.

**Comment by machi1990** [comment]
> See #1670
> 
> The problem is that `buildModel` is called multiple times, so the approach taken here will not work.
> 
> The first time `buildModel` is called it is using the original data model schema, which does not have any generated CRUD API yet. At this point it is easy to identify custom queries that have a clashing name. This PR uses this information to update the CRUD options on the ModelDefinition. The main benefit of this is there is a single source of truth for the model's CRUD config.
> 
> The next time `buildModel` is called, it is using the schema which has the Graphback queries generated. It sees this as custom user queries and updates the CRUD config accordingly, so no resolvers are created.

Instead of updating the CRUD config, I was thinking maybe we can throw an error if the a model's crud config is activated for a certain query/mutation and the user provides a custom one? The error message could be indicative proposing either changing the name of the custom query/mutation or suggesting deactivating the corresponding crud operation on the model config.

**Comment by craicoverflow** [comment]
That sounds like a better approach. The current approach silently disables generation giving no explanation to why the CRUD query is not working for them.

This PR is re-implementing the same behaviour that existed in an early version of Graphback (pre-plugins). That is not to say it should be the case.

I like your idea, I will leave this open a bit longer for discussion and we can decide to action it then.

**Comment by wtrocki** [comment]
> Instead of updating the CRUD config, I was thinking maybe we can throw an error if the a model's crud config is activated for a certain query/mutation and the user provides a custom one? The error message could be indicative proposing either changing the name of the custom query/mutation or suggesting deactivating the corresponding crud operation on the model config.

Best way to resolve problem post 0.14.0 IMHO
For 0.14.0 I would document it briefly
