### ISSUE TITLE
DataSync Conflict server returns value using integer rather than string. 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1668]
<img width="620" alt="Screenshot 2020-07-07 at 16 02 19" src="https://user-images.githubusercontent.com/981838/86800822-54811200-c06b-11ea-9b3e-e6f5963651e4.png">

**Comment by machi1990** [comment]
Datasync https://github.com/aerogear/graphback/blob/master/packages/graphback-datasync/src/DataSyncPlugin.ts#L83 expects it as string so it should be returned and saved as string  and not a number as in https://github.com/aerogear/graphback/blob/master/packages/graphback-core/src/utils/fieldTransformHelpers.ts#L33.

**Comment by wtrocki** [comment]
I was thinking about this. Since we have index we can ignore performance issues, but we use this as order by. @ssd71 any reason why we used number vs strings?

**Comment by ssd71** [comment]
Comparing timestamps as strings will not work if, say I want all changes and give a lastSync value of "0", however this workaround of using numbers still feels lacking

**Comment by wtrocki** [comment]
Ah.. I think we are grand - DB can have number - feels more natural and in this case we can transform that back (as this is error and it not going to be touched by scalars etc.)

**Comment by wtrocki** [comment]
Fixed and verified
