### ISSUE TITLE
Release rc1

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1677]
I have spent some time over the last 2 days testing MongoDB and Postgress. 
I think we can release rc1 over the coming days by bumping package versions in the repository.

**Comment by machi1990** [comment]
We have dropped a couple of beta releases, the latest being https://github.com/aerogear/graphback/releases/tag/0.14.0-beta6. 

This can be closed when we are happy with final e2e testing.

**Comment by machi1990** [comment]
We've done a version bump for the 014-beta6 release here https://github.com/aerogear/graphback/commit/461a8c7c09c65958ee973b67e4dbec51045a54c3
