### ISSUE TITLE
[Discussion] selected fields should only be applied to `findOne`, `findBy` and `sync` related db queries but not write/delete operations

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1684]
https://github.com/aerogear/graphback/pull/1509 added support to retrieve only fields that the user requested. 

This was applied for all the CRUD operations. I am opening this issue for discussion as I might have ran into a potential bug where subscriptions (create, update, delete) are broken. See example scenario below:

 
```graphql
""" @model """
type Note {
  id: ID!
  title: String!
  description: String
}
```

With the above model:

I've the following subscription created:
```graphql
type Subscription {
  newNote(filter: NoteSubscriptionFilter): Note!
  updatedNote(filter: NoteSubscriptionFilter): Note!
  deletedNote(filter: NoteSubscriptionFilter): Note!
}
```

If I subscribe to the creation live updates as below:
```graphql
subscription {
  newNote {
    id,
    title,
    description
  }
}
``` 

and I issue a create mutation 
```graphql

mutation {
  createNote(
    input: {
      title: "kichwa cha habari cha noti"
      description: "maelezo zaidi ya noti"
    }
  ) {
    id
  }
}
```

The create mutation actually works as one would expect but this breaks the subscription above with the following error
```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Note.title.",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "newNote",
        "title"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ],
  "data": null
}
```

But If the mutation is changed to 
```
mutation {
  createNote(
    input: {
      title: "kichwa cha habari cha noti"
      description: "maelezo zaidi ya noti"
    }
  ) {
    id,
    title,
    description
  }
}
```

The subscription is working as expected.

```json
{
  "data": {
    "newNote": {
      "id": "6",
      "title": "kichwa cha habari cha noti",
      "description": "maelezo zaidi ya noti"
    }
  }
}
```

This is because the [Crud Service](https://github.com/aerogear/graphback/blob/9fbe415b2e4eb93eea3ef0cbdcac1bcb74418a53/packages/graphback-core/src/runtime/CRUDService.ts#L40-L78) only sent the payload with selected fields, meaning that if the actual write operation only requested `id` in return, the subscription payload sent will only have the `id` field and missing other fields, in this case the `title` and `description`. 
 
From the error above, we can deduct that `title` was not sent but it is actually required for the `Note` model, where as the `title` is there but not just selected by the incoming mutation. But this could also be a bug in a sense that it may return `null` for the description field even if the field is there in database but not actually selected.

**Comment by machi1990** [comment]
It could be also very useful to have subscriptions integration tests as part of our [test harness](https://github.com/aerogear/graphback/tree/master/integration)

**Comment by craicoverflow** [comment]
Experiencing issues with this very issue implementing subscription filtering.

If a field, let's say `title` is not specified in the return payload for a `createNote` mutation, then this field will also be unavailable to the `newNote` subscription. This means you can only perform a subscription filter on the fields from the payload, even though all fields are generated in the filter object.

This is critical, and a blocker on completion of in-memory subscription filtering in https://github.com/aerogear/graphback/issues/1273

**Comment by wtrocki** [comment]
CC @machi1990 - So what we have on plane here?

1) Disable selection set feature :)
2) Periodically query backend based on active object subscriptions?
3) Subscriptions doing their own full query (this what Hasura was aggregating outside subscribers space for performance)

Anything I have missed?

**Comment by craicoverflow** [comment]
For `create<T>`, `update<T>`, `delete<T>` we could just disable database field selection, as this is now causing issues in a) filtering of subscriptions and b) it limits the available fields to be selected to those in the mutation payload.

> 2. Periodically query backend based on active object subscriptions?
> 3. Subscriptions doing their own full query (this what Hasura was aggregating outside subscribers space for performance)

Are these alternative approaches to 1?

**Comment by wtrocki** [comment]
Yes. Those are alternatives. Disabling this feature will not work if we will deal with the relationships. So did we made call that subscriptions can only hit roots?
If yes disabling this might make sense.

**Comment by machi1990** [comment]
> For `create<T>`, `update<T>`, `delete<T>` we could just disable database field selection, as this is now causing issues in a) filtering of subscriptions and b) it limits the available fields to be selected to those in the mutation payload.

+1 for this.

**Comment by craicoverflow** [comment]
Existing schema does not include relationship fields in the generated subscription filters:

```graphql
input NoteSubscriptionFilter {
  id: ID
  title: String
  description: String
}

input CommentSubscriptionFilter {
  id: ID
  text: String
  description: String
}

""" @model """
type Note {
  id: ID!
  title: String!
  description: String
  """
  @oneToMany(field: 'note')
  """
  comments: [Comment]!
}

""" @model """
type Comment {
  id: ID!
  text: String
  description: String
}
```

So in this way we cannot filter on relationships without changing the spec.

**Comment by wtrocki** [comment]
I think approach from PR is making things work and also doesn't have much disadvantages. 
+100
