### ISSUE TITLE
Publish user facing API docs by using https://typedoc.org and friends

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1702]
We have the package here https://github.com/aerogear/graphback/blob/master/package.json#L30.

The idea is to build the docs from code comments and publish them under the `API` page avoiding having to maintain two separates docs.

Idea follows these comments:
- https://github.com/aerogear/graphback/pull/1698#issuecomment-656646513
- https://github.com/aerogear/graphback/pull/1698#issuecomment-656658562
- https://github.com/aerogear/graphback/pull/1698#issuecomment-656661720

/cc @craicoverflow 

Targeted API:
   - [ ] buildGraphbackAPI
   - [ ] createCRUDService
   - [ ] createKnexDbProvider
   - [ ] createMongoDbProvider
   - [ ] GraphbackDataProvider
   - [ ] GraphbackCRUDService
   - [ ] GraphbackPlugin

**Comment by machi1990** [comment]
Running the below command in the root directory:

```shell
yarn typedoc --ignoreCompilerErrors --out typedoc --inputFiles packages/**/src/**/*.ts
```

Will result into the attached output:

This can be further tuned, by setting up the `TOC` or the `Theme`, wanted to first push this bare minimum output 
which may help us in this direction.
[typedoc.zip](https://github.com/aerogear/graphback/files/4911164/typedoc.zip)

**Comment by wtrocki** [comment]
We need to investigate if we can use typedoc as iframe or migrate to markdown.

**Comment by craicoverflow** [comment]
https://github.com/tgreyuk/typedoc-plugin-markdown

**Comment by machi1990** [comment]
> https://github.com/tgreyuk/typedoc-plugin-markdown

@craicoverflow thanks for the link. I'll play with this to see how it integrates with typdoc and our website.

**Comment by machi1990** [comment]
![Screenshot from 2020-07-29 16-36-53](https://user-images.githubusercontent.com/10106536/88814204-18e4ee00-d1ba-11ea-8abb-cffa45a3a9ec.png)

Using the markdown plugin with the `docusaurus` theme gives the above page for the `buildGraphbackAPI`.
