### ISSUE TITLE
Explicit containment by `@contains` definition 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1723]
We can have `@contains` or `@belongs` annotations to explicitly mention that this object is embedded.

**Comment by machi1990** [comment]
Another option could be `@embedded`

**Comment by wtrocki** [comment]
Actually `@embedded` is the best!

**Comment by craicoverflow** [comment]
We have inferred implicit relationships through non-model annotated types being identified as embedded. However that could change in the future when we get implicit relationships added (post v1) - so then this annotation will become vital.

My vote is to update the description of this issue and give it a Hacktoberfest label.

**Comment by RinkiyaKeDad** [comment]
I'd like to work on this. Can you please provide me with a bit more details to get started on? Thanks.

**Comment by craicoverflow** [comment]
Hi @RinkiyaKeDad I looked at this recently and it is not necessary to do, so I will close it.
