### ISSUE TITLE
`id` mapping is wrong for MongoDB

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1732]
The mapping assumes that the primary key is always named `id`: 

See https://github.com/aerogear/graphback/blob/56b887f077809e4cccc4e594411f2c34f49afb28/packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts#L173-L176

But we could as well have a different name like in example below:  

```graphql
"""
@model
"""
type SomeType {
 """
 @id
 """
 primaryKey: ID!
}
```

In this case the name is `primaryKey`

**Comment by wtrocki** [comment]
@wtrocki find duplicate

**Comment by machi1990** [comment]
Duplicate of https://github.com/aerogear/graphback/issues/1547
