### ISSUE TITLE
Integrate with GraphQL-CLI templates 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1736]

**Comment by machi1990** [comment]
- Add MongoDB templates in graphql-cli
- Add example custom resolvers in both pg and the to-be-added mongo fullstack template
- integrate `gqlserve` and replace mock graphql serve.

**Comment by wtrocki** [comment]
Also we need to add client side template as well :)

**Comment by wtrocki** [comment]
High priority for the moment

**Comment by machi1990** [comment]
Ongoing work here https://github.com/machi1990/graphql-cli/tree/refactor/brings-in-graphback-commands. I'll add the MongoDB template into GraphQL cli templates configuration so that we've a mongo based template too during init.

**Comment by machi1990** [comment]
Too many tabs opened and I clicked the wrong button of an unrelated issue.
