### ISSUE TITLE
DeltaTypes return documents or changed fields?

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1744]
Should `DeltaType`s always return full documents or be allowed to return only changed fields?

**Comment by wtrocki** [comment]
@ssd71 Cna you provide more information. This will affect subscriptions (if we want return delta there as well). GraphQL generally has this required flag and if type has required flag it will not be able for us to not return it - thus delta might require some specific type created

**Comment by craicoverflow** [comment]
It should be the full document (IMO) because the user will likely need to work with the entire document (by rendering it on their webpage as an example). 

If we start returning only changed fields the user would have to merge the objects to keep the full document, which does not seem desirable.

**Comment by ssd71** [comment]
> @ssd71 Cna you provide more information. This will affect subscriptions (if we want return delta there as well). GraphQL generally has this required flag and if type has required flag it will not be able for us to not return it - thus delta might require some specific type created

@wtrocki When using delta tables, we have the option of returning only either the changed fields or entire documents, but due to GraphQL some fields are strictly, required, if we were to allow returning changed fields that would mean making all fields optional (Except maybe `id` and `_deleted` and some other metadata which will need to be returned anyway)

> It should be the full document (IMO) because the user will likely need to work with the entire document (by rendering it on their webpage as an example).

> If we start returning only changed fields the user would have to merge the objects to keep the full document, which does not seem desirable.

@craicoverflow Fair point :+1:

**Comment by wtrocki** [comment]
On the other hand, it will be confusing to not get data for what you requested (or get nulls). 
Cost of adding delta types returning delta etc. History API and changes will be only available on server to be able to perform server-side conflict resolution. For client-side conflict resolution, we going to send delta in error object (where we do not have any constraints over payload format)

Can I hook up into this and ask - do we want to have subscription delta expands (fetching relationships)?

> If we start returning only changed fields the user would have to merge the objects to keep the full document, which does not seem desirable.

Total offtopic/fun fact - most of the GraphQL clients do that out of the box. We can use subscription to refill your cache and watch for cache changes to fetch full objects.

**Comment by ssd71** [comment]
> It will be confusing to not get data for what you requested (or get nulls).
Cost of adding delta types returning delta etc. History API and changes will be only available on server to be able to perform server-side conflict resolution. 

Agreed

> Can I hook up into this and ask - do we want to have subscription delta expands (fetching relationships)?

Just wondering, wouldn't being able to filter subscriptions make up for this?

**Comment by wtrocki** [comment]
We will be able to filter them out. Our team works on this now

**Comment by ssd71** [comment]
I believe this has been settled, as we decided to use full types instead of changed fields
