### ISSUE TITLE
Analyze Performance suite build for Graphback

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1758]
Check results and identify areas for improvements:

Tasks:
- [x] Analyse startup time
- [x] Analyse throughput
- [x] Analyse database query performance. A first round of analysis on https://github.com/aerogear/graphback/pull/2024. 
- [x] Memory usage (RSS column Added)
- [x] Bring in the tests suite in our repository
- [x] A script to run tests in docker container so we always have the same resources/memory limits for better results by isolating any hardware specificity (See https://github.com/aerogear/graphback/pull/2028)
- [x] Display 99.999 percentiles instead of mean values in comperative table of benchmark results. See https://github.com/aerogear/graphback/pull/2056
- [ ] Add a script to wipe out old perfs results e.g those of two previous major releases. See https://github.com/aerogear/graphback/pull/2028#discussion_r486334034 /cc @craicoverflow 
- [ ] Try out https://github.com/TechEmpower/FrameworkBenchmarks. See [JavaScript Frameworks](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/JavaScript)

**Comment by wtrocki** [comment]
CC @martinhesko @machi1990 @craicoverflow

**Comment by machi1990** [comment]
It will be interesting to add a database and see how performance fares in https://www.techempower.com/benchmarks especially against other graphql related frameworks or [Javascript libraries](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/JavaScript).

**Comment by machi1990** [comment]
I'll look into dockerising the benchmark tests and provide a onetime script to launch it.

**Comment by craicoverflow** [comment]
Looks like this has can be closed. @machi1990 has done great work in analysing performance and integrating it into the workflow
