### ISSUE TITLE
Performance downgrade in 0.14

### ISSUE THREAD

**Issue by martinhesko** [aerogear/graphback#1759]
During my work on the performace test-suite I recently upgraded from 0.14-alpha4 to 0.14.0 and I noticed a real hit to performance.
Most of the metrics have been cut in half, except startup time which surprisingly improved.

For comparison here are my measurements I took today:

**0.14-alpha4**
| Server                                                                                                                            | Requests/s | Latency | Throughput/Mb | Startup time |
| :--                                                                                                                               | --:        | :-:     | --:           | --:          |
| [mongo10types](https://github.com/martinhesko/node-graphql-benchmarks/tree/master/benchmarks/mongo10types.js)                     | 1116.8     | 4.24    | 3.84          | 4.17         |
| [postgres10types](https://github.com/martinhesko/node-graphql-benchmarks/tree/master/benchmarks/postgres10types.js)               | 1113.6     | 4.14    | 3.14          | 3.04         |
| [mongo100types](https://github.com/martinhesko/node-graphql-benchmarks/tree/master/benchmarks/mongo100types.js)                   | 1070.8     | 4.28    | 3.65          | 9.85         |
| [postgres100types](https://github.com/martinhesko/node-graphql-benchmarks/tree/master/benchmarks/postgres100types.js)             | 1059.2     | 4.29    | 2.96          | 10.16        |

**0.14.0**
| Server                                                                                                                            | Requests/s | Latency | Throughput/Mb | Startup time |
| :--                                                                                                                               | --:        | :-:     | --:           | --:          |
| [mongo10types](https://github.com/martinhesko/node-graphql-benchmarks/tree/master/benchmarks/mongo10types.js)                     | 516.2      | 9.21    | 1.76          | 3.16         |
| [mongo100types](https://github.com/martinhesko/node-graphql-benchmarks/tree/master/benchmarks/mongo100types.js)                   | 495.6      | 9.56    | 1.69          | 8.54         |
| [postgres10types](https://github.com/martinhesko/node-graphql-benchmarks/tree/master/benchmarks/postgres10types.js)               | 442.6      | 10.77   | 1.23          | 3.21         |
| [postgres100types](https://github.com/martinhesko/node-graphql-benchmarks/tree/master/benchmarks/postgres100types.js)             | 413.6      | 11.59   | 1.14          | 8.57         |

**Comment by wtrocki** [comment]
Results were related to unbalanced environment. Tests done on AWS cloud showing different values. Closed as duplicate of existing issue
