### ISSUE TITLE
Investigate expansion of SubscriptionFilter to allow non-simplistic filtering

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1760]
Currently the SubscriptionFilter input allows direct value comparisons. Since we are going to route of in-memory subscription filtering this can be expanded to be more aligned with the model filter input in the `findBy` query.

**NoteFilter**

```gql
input NoteFilter {
  id: IDInput
  title: StringInput
  opened: BooleanInput
  likes: IntInput
  completedPercentage: FloatInput
  and: [NoteFilter!]
  or: [NoteFilter!]
  not: NoteFilter
}
```

**NoteSubscriptionFilter**

```graphql
input NoteFilter {
  id: ID
  title: String
  opened: Boolean
  likes: Int
  completedPercentage: Float
}
```

1. Will it be straightforward to implement this advanced filtering on subscriptions?
2. What operators should be used? All the same as in `findBy`?
1. Can we reuse the same filter input, or should the <T>SubscriptionFilter? Depends on answer to 2.

**Comment by craicoverflow** [comment]
If we were to use simpliar filters to `findBy` (see description), exclude relationship filtering, and AND/OR/NOT operators from subscription filtering, the complexity and of an in-memory subscription filter would be O(n^³).

It would actually be much simpler to implement than the database layer query mapping, because it would operate directly on the data, whereas the Mongo and Knex query mappers have to build a query from the filters.

Here is how the filter would look:

```ts
const filter = {
  id: {
    gt: 10,
    lt: 100
  },
  title: {
    startsWith: 'hello'
  },
  likes: {
    gt: 100
  },
  enabled: {
    eq: true
  }
}

return withFilter(asyncIterator, (payload: any) => {
  const subscriptionPayload = payload[subscriptionName]

  for (const [filterFieldName, operators] of Object.entries(filter)) {
    
    const subscriptionFieldValue = subscriptionPayload[filterFieldName]

    for (const [operatorKey, filterValue] of Object.entries(operators)) {
      const matchesValue: boolean = operatorMap[operatorKey](subscriptionFieldValue, filterValue)

      if (!matchesValue) {
        return false
      }
    }
  }

  return true
})
```

**Comment by craicoverflow** [comment]
I think if we are to add this level of filtering to the subscriptions, any more (AND/OR/NOT/Relationships) would further increase complexity and might impact performance.

cc @wtrocki @machi1990

**Comment by machi1990** [comment]
@craicoverflow missed this somehow. I was thinking maybe we could build the `Predicate`, by composing operators matchers upon the reception of subscription and pass the resulting filter to the `withFilter(..)` fn. 
 
So building the Predicate filter could be a one off thing and the rest will be just operating on it.

**Comment by craicoverflow** [comment]
What it is doing on master is wrapping `withFilter`:

```ts
return withSubscriptionFilter(() => asyncIterator, filter, subscriptionName)()

...

export function withSubscriptionFilter(asyncIterator: ResolverFn, filter: any, subscriptionName: string): ResolverFn {
  if (!filter) {
    return asyncIterator
  }

  return withFilter(asyncIterator, (payload: any) => {
    const subscriptionPayload = payload[subscriptionName]

    for (const key of Object.keys(filter)) {
      if (!subscriptionPayload[key] || subscriptionPayload[key].toString() !== filter[key].toString()) {
        return false
      }
    }

    return true
  })
}
```

But we might not need to use `withFilter` at all if we simply implement all of the filtering logic in a custom AsyncIterator wrapper, like described in [graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions#custom-asynciterator-wrappers). Is this something like what you had in mind?

**Comment by machi1990** [comment]
> What it is doing on master is wrapping `withFilter`:
> 
> ```ts
> return withSubscriptionFilter(() => asyncIterator, filter, subscriptionName)()
> 
> ...
> 
> export function withSubscriptionFilter(asyncIterator: ResolverFn, filter: any, subscriptionName: string): ResolverFn {
>   if (!filter) {
>     return asyncIterator
>   }
> 
>   return withFilter(asyncIterator, (payload: any) => {
>     const subscriptionPayload = payload[subscriptionName]
> 
>     for (const key of Object.keys(filter)) {
>       if (!subscriptionPayload[key] || subscriptionPayload[key].toString() !== filter[key].toString()) {
>         return false
>       }
>     }
> 
>     return true
>   })
> }
> ```
> 
> But we might not need to use `withFilter` at all if we simply implement all of the filtering logic in a custom AsyncIterator wrapper, like described in [graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions#custom-asynciterator-wrappers). Is this something like what you had in mind?

I was thinking of using `withFilter` but instead of going iterating the `filter` object every time an item needs to be sent, I was hoping we could do a one off construction of a `Predicate`.  

 

> I think if we are to add this level of filtering to the subscriptions, any more (AND/OR/NOT/Relationships) would further increase complexity and might impact performance.
> 
> cc @wtrocki @machi1990

+1 on starting small and improve later on.
