### ISSUE TITLE
Datasync enduser api

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1765]
I would like to propose an API as a starting place for further discussion:
We create two helper functions that will be like [`createDataSyncMongoDbProvider`](https://github.com/aerogear/graphback/blob/master/packages/graphback-datasync/src/providers/createDataSyncMongoDbProvider.ts) but for people who want conflicts

One would be `createDataSyncSSCProvider` (some help with names) that would create a Provider which would conflict on `_version` mismatch and use Server-side conflict resolution

Another would be `createDataSyncCustomConflictProvider` that would require a custom strategy for both conflict detection and conflict resolution per operation type as argument

**Comment by ssd71** [comment]
cc @wtrocki following up from #1764

**Comment by wtrocki** [comment]
Does this resolves problems mentioned in #1764 
I think this is making things even worse.

**Comment by ssd71** [comment]
This resolves problems like having to pass Version for conflict as someone who wants just wants server-side conflicts can use the first one that will need no extra arguments, no extra configuration (optionally TTL maybe), plus someone who wants their own state provider can just use the second function

**Comment by ssd71** [comment]
Maybe we are not on the same page, passing Version to datasync plugin is going away, it was there because of wrong approach on my part, Do you mean that 'we need to require `_version` for updates only if server-side conflicts is used or not?'

**Comment by wtrocki** [comment]
See https://gist.github.com/wtrocki/f22ac90a99325734135da87d1085abdf

**Comment by ssd71** [comment]
@wtrocki Is there some better way to configure server-side conflict resolution?
```typescript
createDataSyncChangeThisName(modelDefs: string|GQLSchema, graphbackConfigObject: GraphbackConfigMinusProviderCreator, conflictConfig: { 
  Note: {
    enabled: false,
    // Hardcoded to versions for the moment 
    conflictDetection: versionConflict
    conflictResolutionStrategy: serverSideAutoThing,
    ttlforDelta: 4000
  }
}) {
```
The way I see it, we have to set both conflict detection and conflict resolution, so we still have to set two things to createDatasync

**Comment by wtrocki** [comment]
just asume defaults and do not pass detection. Same with enabled. If resolution is passed means enabled?

**Comment by ssd71** [comment]
Hmm, what if someone only wants conflict detection ?

**Comment by ssd71** [comment]
Also, should there be some way to configure only delta queries and no conflicts (for some models maybe) in this setup? I was thinking that maybe just `@datasync` annotation without any conflict config would mean only delta queries, wdyt

**Comment by wtrocki** [comment]
> Hmm, what if someone only wants conflict detection

Ok. Enabled needs to be there

> Also, should there be some way to configure only delta queries and no conflicts (for some models maybe) in this setup? I was thinking that maybe just @datasync annotation without any conflict config would mean only delta queries, wdyt

Yep. We covered this couple times. this how it should work
