### ISSUE TITLE
Directives on Object Types are removed in generated schema

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1767]
I am on graphback `0.15.0-alpha1`. Object type directives in my model schema are removed by Graphback in the generated schema.

Model schema:
```graphql
type Users @directive1 @directive2 {
  id: ID!
}
```

This is what is currently happening with the generated schema:
```graphql
type Users {
  id: ID!
}
```
This is what should happen with the generated schema:
```graphql
type Users @directive1 @directive2 {
  id: ID!
}
```

**Comment by craicoverflow** [comment]
Thanks for reporting this issue. It appears that a dependency of Graphback (graphql-compose) is removing the directive from the object. We reported a similar issue in the past on field definitions, which was fixed (and still works). We will follow up on this.

**Comment by machi1990** [comment]
Fixed by https://github.com/aerogear/graphback/pull/1810. I'll add a test case tomorrow and hopefully do a release.

**Comment by machi1990** [comment]
@lastmjs we have droppped https://github.com/aerogear/graphback/releases/tag/0.16.0-alpha1, which include a fix for this issue. Let me know if that fixes the issue on your side. Thanks!

**Comment by wtrocki** [comment]
Awesome work @machi1990

**Comment by machi1990** [comment]
@lastmjs we've dropped another [0.16.0-alpha3](https://github.com/aerogear/graphback/releases/tag/0.16.0-alpha3) which includes a fix for this issue. Mind checking if this release effectively fix the issue for you? Thanks!
