### ISSUE TITLE
Directives on field definitions are removed if there is a @oneToOne annotation

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1772]
I'm not sure how general the problem is here, but in my generated schema for one of my fields with the following annotation:

```graphql
    """
    @oneToOne(key: 'company_id')
    """
```
the schema directives for that field in my model schema are removed in the generated schema.

**Comment by lastmjs** [comment]
It does seem to generally be a problem with all fields that have annotations, all of my directives are removed in the generated schema, that I've seen so far.

**Comment by lastmjs** [comment]
I need this fixed ASAP and am happy to do a PR, but seems like this is probably a problem with graphql-compose?

**Comment by wtrocki** [comment]
https://github.com/graphql-compose/graphql-compose/issues/273 logged.
Looking for alternatives that will make this work in upcoming days.

**Comment by wtrocki** [comment]
@lastmjs What version of GraphQL you are using? 0.15?

**Comment by lastmjs** [comment]
I am using `14.6.0`

**Comment by craicoverflow** [comment]
I don't believe this issue relates to https://github.com/graphql-compose/graphql-compose/issues/273 since it appears to only be happening on the `@oneToOne` and `@oneToMany` annotated fields (it maps just fine with other or no field annotations.

I will take a look into it now, but with timezone differences (reaching end of day where I am) you may be able to get to it first @lastmjs, if its urgent for you.

**Comment by lastmjs** [comment]
If it can be done in the next 2-3 days, I'll let you handle it, I think that would be quicker. I do have a workaround in the short-term

**Comment by wtrocki** [comment]
ah.. it could be that we do update this fields in schema plugin ourselves and this removes directive. 
Possible place that fails.
https://github.com/aerogear/graphback/blob/master/packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts#L154-L158

**Comment by craicoverflow** [comment]
Fix should be available now in 0.15.1

https://github.com/aerogear/graphback/releases/tag/0.15.1
