### ISSUE TITLE
@datasync and @delta

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1775]
What should be done about [this](https://graphback.dev/docs/datasync/soft-delete#advanced-topics)?

`@datasync` will have `_version`(through #1771) and eventually `_lastUpdatedAt`

At this point it becomes really confusing as to which means what (`@delta` vs `@datasync`). Having one annotation would surely serve to simplify things. Plus since datasync is going to have a `_lastUpdatedAt` and not rely on `updatedAt` and `createdAt` anymore, I think it makes even more sense to decouple `@datasync` from `@versioned` as well.

what do you guys think?

**Comment by machi1990** [comment]
Isn't `@datasync` a shorthand for 
```
@delta
@versioned
```
?

**Comment by wtrocki** [comment]
`@datasync will have _version(through #1771) and eventually _lastUpdatedAt`

Do you meant this to be other way around. _version will be `eventual`?

I see us (including myself) being confused.. 

I will try to show how we can sort out annotations:

Generic versioning (@versioned) that might stay in the platform but not going to be used anymore for datasync.

@datasync -> adds sync queries and `__lastUpdatedAt`
If you configure conflicts in code you will also get `__version`

This is aligned with what we said and agreed before so let's maybe close this issue if we are on the same page

**Comment by ssd71** [comment]
> Generic versioning (@versioned) that might stay in the platform but not going to be used anymore for datasyn (lastUpdatedAt vs __lastUpdatedAt)
> 
> @datasync -> adds sync queries and `__lastUpdatedAt`
> If you configure conflicts in code you will also get `__version`

+💯 exactly what I wanted to say, thanks

@machi1990 sorry for confusing you
