### ISSUE TITLE
`sync` Query filter expression using "gt" instead of "ge"

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1790]
Currently, in datasync, we are using the following as our filter expression for delta queries (`sync` queries):
https://github.com/aerogear/graphback/blob/c0056b4bd3250df8a3e39131302dcd3138b312b9/packages/graphback-datasync/src/providers/DatasyncMongoDBDataProvider.ts#L108-L113
Would it be better if we had `ge` instead of `gt` ?
It seems to me (as far as I can understand) that `gt` might miss some updates that may be happening at the same time as the `sync` query, therefore, would it be better if we did `ge`(greater than or equal) instead of `gt`(strict inequality)?

**Comment by wtrocki** [comment]
Yep. Looks like oversight

**Comment by wtrocki** [comment]
@machi1990 ROLF - now I will never know if that was you doing all nighter or you confired bot that has AI and applies labels :D

**Comment by machi1990** [comment]
> @machi1990 ROLF - now I will never know if that was you doing all nighter or you confired bot that has AI and applies labels :D

It's indeed confusing. We should have a dedicated account soon.

**_It's me not a bot here ;-)_**

**Comment by wtrocki** [comment]
No way. We need to keep it as it fits perfectly to the joke of yourself having 24 hours coverage... I would extend the boot to do more actions like:

/Matchi approve please

Imagine your contribution graph after that

**Comment by craicoverflow** [comment]
@wtrocki did you mean to close this?

**Comment by wtrocki** [comment]
Yep.. That was discussion issue. @ssd71 will apply this in single line on the existing PR.
