### ISSUE TITLE
Directives only allow for enabling

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#182]
Currently using directives only enables a certain operation out of
- `@create`
- `@update` 
- `@delete` 
- `@find`
- `@findAll`
- `@subCreate`
- `@subUpdate` 
- `@subDelete`

Directives should invert the value of the flag in config

**Comment by wtrocki** [comment]
Inverting will be confusing. How about having enabled property with default true?

**Comment by ankitjena** [comment]
Didn't get this, are you saying for each property, like
```
@create: enabled
```

**Comment by wtrocki** [comment]
Sorry for not being clear. SO full explanation is:
```
type Test @create 
```
Enables create


```
type Test @create(enabled: false) 
```
Disables create (This needs to be added but low priority)
