### ISSUE TITLE
Move auth API docs to API reference

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1823]
<img width="276" alt="Screenshot 2020-08-06 at 10 48 44" src="https://user-images.githubusercontent.com/981838/89518176-74bf0080-d7d2-11ea-8fc3-33846bb3781b.png">

**Comment by machi1990** [comment]
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by machi1990** [comment]
I think it makes sense to move all API Docs under the API Reference docs. 

![Screenshot from 2020-08-17 10-49-13](https://user-images.githubusercontent.com/10106536/90376853-60eb8800-e077-11ea-953d-351ff9409d38.png)

This is from https://github.com/aerogear/graphback/pull/1872 which I find rather loaded with API stuffs and not a guide kind of a documentation that I'd expect as a user.

**Comment by wtrocki** [comment]
Yep. CC @ssd71
