### ISSUE TITLE
[DataSync] automatic indexing of "lastUpdatedAt" field for better query performance

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1825]
I believe this would make for much faster sync queries, and remove the step of in-memory sorting when ordering by lastUpdatedAt, if one chooses to do it in a findBy query

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by machi1990** [comment]
+1, makes sense to me. This will mean adding the `@index` annotation by default right? @ssd71

**Comment by wtrocki** [comment]
Aren't we doing it now 🙈

**Comment by ssd71** [comment]
> +1, makes sense to me. This will mean adding the `@index` annotation by default right? @ssd71

Yep

> Aren't we doing it now :see_no_evil:

Nope :smile:

**Comment by wtrocki** [comment]
🤦

**Comment by machi1990** [comment]
This is low hanging fruit. I kind of have my eyes in the codebase that does this, I am grabbing this issue in order to leave @ssd71 focused on interesting issues. WDYT?

**Comment by wtrocki** [comment]
@machi1990 This is not longer up to date. We have separate _lastUpdated field now for datasync.

**Comment by machi1990** [comment]
> @machi1990 This is not longer up to date. We have separate _lastUpdated field now for datasync.

Yes, that's the one that's indexed automatically in the patch I opened.
