### ISSUE TITLE
No simple documentation for hooking up subscriptions

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1836]
In the main areas of graphback.dev that talk about subscriptions, there is nowhere showing how to actually hook up subscriptions to in `buildGraphbackAPI`.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by machi1990** [comment]
@lastmjs thank you for reporting the issue. 

Yes, adding an example on how to setup subscriptions will be very welcomed. 

If you trying to figure out how to do the setup, if you do not provide any pubsub queue, graphback will set one using an in memory queue for you. This is useful for dev purposes. 

If you are looking for setting up a prod ready pubsub queue, you can check out how we setup the [AMQ PubSub service](https://github.com/aerogear/datasync-starter/blob/a58fbab136504a28cf2678a74589939bfc977d27/server/src/crudServiceCreator.ts#L20)

with the queue setup happing [here](https://github.com/aerogear/datasync-starter/blob/a58fbab136504a28cf2678a74589939bfc977d27/server/src/pubsub.ts#L6). Here we use AMQ, you can use any other messaging system as described in [PubSub Implementations](https://github.com/apollographql/graphql-subscriptions#pubsub-implementations) 

And finally, the service is in [buildGraphbackAPI](https://github.com/aerogear/datasync-starter/blob/a58fbab136504a28cf2678a74589939bfc977d27/server/src/graphql.ts#L28)

**Comment by wtrocki** [comment]
https://graphback.dev/docs/next/subscriptions/intro

Yep. Docs we have do not have code. Adding some snippets will do a lot
