### ISSUE TITLE
Add custom scalars to QueryFilter

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1864]
[`QueryFilter`](https://github.com/aerogear/graphback/blob/c2a718aa9da5d00ab74877996f2a72bcc65c414d/packages/graphback-core/src/runtime/QueryFilter.ts#L81) only deals with default scalars. We could add [Graphback scalars](https://graphback.dev/docs/next/model/scalars#table-summary) to provide more strongly typed query-ability.

Let's also disable generating filters for unknown scalars since we have provided most scalars by now.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by wtrocki** [comment]
And.. disable automatic filtering for user provided scalars (we had that as workaround for time being!)

**Comment by machi1990** [comment]
+1 thanks for the followup @craicoverflow

**Comment by craicoverflow** [comment]
> And.. disable automatic filtering for user provided scalars (we had that as workaround for time being!)

So what happens if user has a custom scalar like `BigInt`? Having a filter input generated for this would be really convenient, and lessens what we need to support. At the same, we are generating a filter input which possibly will throw some sort of error, so it may be best to disable and we can review requests for new scalars as they come in.
