### ISSUE TITLE
[DataSync] Inform client about operation where conflict occured

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1867]
We might need to know what operation thrown conflict (in case someone will start batching requests on client)

_Originally posted by @wtrocki in https://github.com/aerogear/graphback/pull/1833_

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by wtrocki** [comment]
Two cases. Error thrown where no server side conflict resolution is possible.

Extensions can be used to notify about server side error resolution

Research needed

**Comment by wtrocki** [comment]
```
mutation edit{
  myTodo: updateTodo(input:{_id:"5f3e4925deefe21ea421242c", _version:2}){
        _id
  }

    otherTodo: updateTodo(input:{_id:"5f3e4925deefe21ea421242c", _version:5}){
        _id
  }
}
```

When executing this operations we getting path that identifies errors:
```
errors": [
    {
      "message": "",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
      ],
      "path": [
        "myTodo"
      ],
```
