### ISSUE TITLE
@disablegen and @rest directive

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#187]
`@rest` directive should disable db generation and leave empty implementation.

**Comment by wtrocki** [comment]
Leaving as a good first issue for the community. 
CC @MStokluska

**Comment by wtrocki** [comment]
`@rest` and `@disablegen` directives should have the same behaviour. 
disablegen is needed because sometimes we want to have type 
that is being used only for relational purposes and this will mean that 
we will need to put all possible directives on it to disable it. 
For rest we will keep this behavior temporarily - we can add some extra parameter later and improve generation.

**Comment by richcorbs** [comment]
I don't know how to link this to the PR for this issue but here is the (merged) PR:

https://github.com/aerogear/graphback/pull/214

**Comment by wtrocki** [comment]
We might need discussion how restful ones can work. Making empty resolvers would not justify existence of REST. Lets leave it for the moment and see what community will expect from rest first
