### ISSUE TITLE
Better automated testing

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1877]
Hey everyone, great job on the library so far! As you know, I've been opening a lot of issues. I'm concerned with the number of issues that I'm having to open for edge cases in my queries. It seems to me that a more extensive test suite that covers many different permutations of selection sets would really help. A lot of the little problems I'm having should be caught by automated testing. I'm not doing anything too crazy, just stretching GraphQL beyond the basics.

Have you considered property-based testing? https://github.com/dubzzz/fast-check These types of tests require you to create a model of your data, and then you can write tests checking properties of arbitrary inputs. It's extremely powerful when appropriate, and can create a much better test suite than simple one-off unit tests. Seems to me that this would be a great fit for testing queries, as it could generate an arbitrary number of arbitrarily nested selection sets.

All of these issues I'm running into make my weary, and I'd love to feel that Graphback is rock solid.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by lastmjs** [comment]
Another example of core functionality breaking when upgrading graphback versions: https://github.com/aerogear/graphback/issues/1941

**Comment by craicoverflow** [comment]
Going to close this one, as we are constantly improving out automated tests. feel free to open again!
