### ISSUE TITLE
Is this needed?

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1879]
I am pretty sure that we are not using this anywhere because datasync has it's own way of checking what to add and what not to
https://github.com/aerogear/graphback/blob/ba6e2969f9ab674f83a7d83d26cea242a20523a6/packages/graphback-core/src/plugin/ModelDefinition.ts#L22-L23

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by wtrocki** [comment]
NOt needed. Closing
