### ISSUE TITLE
DataSync demands TTL even with delete mutations disabled

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#1890]
* **Module**: Graphback DataSync
* **Version**: 0.16.0-alpha5
* **Node.js / npm versions**: N/A
* Example/snippet of the model that is causing issue
```graphql
"""
@model(
  delete: false
)
@datasync
"""
type Comment {
  _id: GraphbackObjectID!
  text: String
  description: String
}
```

TTL should not be required in this case, because deletes are disabled

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki
