### ISSUE TITLE
Use `IObjectTypeResolver` instead of `IFieldResolver` in SchemaCRUDPlugin

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1898]
The SchemaCRUDPlugin is casting the resolver query, mutation and subscription objects to `IFieldResolver` whereas they should be `IObjectResolver`.

Everything is working fine, but let's correct this in case it causes problems in the future.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki
