### ISSUE TITLE
TypeError encountered while using graphback generate command.

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/graphback#190]
While using graphback to generate schema and resolvers for the below graphql file:
```graphql
type Task {
  id: ID!
  version: Int
  title: String!
  description: String!
  status: TaskStatus
}

enum TaskStatus {
  OPEN
  ASSIGNED
  COMPLETE
}

type Query {
  allTasks(first: Int, after: String): [Task],
  getTask(id: ID!): Task
}

type Mutation {
  createTask(title: String!, description: String!, status: TaskStatus): Task
  updateTask(id: ID!, title: String, description: String, version: Int!, status: TaskStatus): Task
  deleteTask(id: ID!): ID
}
```

I encountered the error: `TypeError: Cannot read property 'forEach' of undefined`.
@wtrocki Can you please help me out?

**Comment by ankitjena** [comment]
Graphback currently does not support `enum`, hence the issue. Will be adding it for version `0.6.0` roadmap

**Comment by Lavanyagaur22** [comment]
Yeah just read issue #188 .

**Comment by wtrocki** [comment]
@Lavanyagaur22 I just hit the same. @Lavanyagaur22 you can fix it by PR against that branch to replace that with strings and other required changes you want to introduce.

**Comment by ankitjena** [comment]
Closing this. Issue #191 is tracking it
