### ISSUE TITLE
Custom DateTime filter no longer available when upgrading from 0.16.0-alpha5 to 0.16.0-alph6

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1904]
Here's an example filter in `0.16.0-alpha5`:

```graphql
type Incoming_queue_itemsFilter {
id: IDInput
call_id: IDInput
created_at: DateTimeInput
handled_at: DateTimeInput
incoming_call_type: StringInput
pod_id: IDInput
updated_at: DateTimeInput
user_call_sid: StringInput
and: [Incoming_queue_itemsFilter!]
or: [Incoming_queue_itemsFilter!]
not: Incoming_queue_itemsFilter
}
```
When I upgrade to `0.16.0-alpha6` the filter looks like this:

```graphql
type Incoming_queue_itemsFilter {
id: IDInput
call_id: IDInput
incoming_call_type: StringInput
pod_id: IDInput
user_call_sid: StringInput
and: [Incoming_queue_itemsFilter!]
or: [Incoming_queue_itemsFilter!]
not: Incoming_queue_itemsFilter
}
```
I have been using a simple `scalar DateTime` just fine until `0.16.0-alph6`, and there is no mention of this change in the release notes. I hope it's just a bug and that this functionality hasn't been removed.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by craicoverflow** [comment]
Hey Jordan! That's a bug, thanks. We will get it back.

**Comment by machi1990** [comment]
> Here's an example filter in `0.16.0-alpha5`:
> 
> ```graphql
> type Incoming_queue_itemsFilter {
> id: IDInput
> call_id: IDInput
> created_at: DateTimeInput
> handled_at: DateTimeInput
> incoming_call_type: StringInput
> pod_id: IDInput
> updated_at: DateTimeInput
> user_call_sid: StringInput
> and: [Incoming_queue_itemsFilter!]
> or: [Incoming_queue_itemsFilter!]
> not: Incoming_queue_itemsFilter
> }
> ```
> 
> When I upgrade to `0.16.0-alpha6` the filter looks like this:
> 
> ```graphql
> type Incoming_queue_itemsFilter {
> id: IDInput
> call_id: IDInput
> incoming_call_type: StringInput
> pod_id: IDInput
> user_call_sid: StringInput
> and: [Incoming_queue_itemsFilter!]
> or: [Incoming_queue_itemsFilter!]
> not: Incoming_queue_itemsFilter
> }
> ```
> 
> I have been using a simple `scalar DateTime` just fine until `0.16.0-alph6`, and there is no mention of this change in the release notes. I hope it's just a bug and that this functionality hasn't been removed.

This is a bug, you can use `scalar GraphbackDateTime` which is supported out of the box. 
- https://github.com/aerogear/OpenVolunteerPlatform/blob/master/platform/server/model/main.graphql#L81
