### ISSUE TITLE
Graphback support for interfaces

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#191]
Graphback currently doesn't support enums and interfaces as the visitor is not parsing it. It would be a nice feature to add.

**Comment by wtrocki** [comment]
Hmm.. another inconvinience is that for custom mutations we will need to know input types that can be used (they will be generated) we need to document how input types are named because we never know until they are generated.

**Comment by wtrocki** [comment]
To do this first we will need to:

1) Extend model in template to have interface
```
interface A { ...}
type B implements interface A
```

2) Investigate generated AST using ast explorer. Check blog post on graphback page

3) Investigate visitor we have build:
https://github.com/aerogear/graphback/blob/master/packages/graphback/src/InputTypeVisitor.ts#L11

4) Add handler for an interface for visitor and stage information about the interface to separate object

https://github.com/aerogear/graphback/blob/master/packages/graphback/src/InputTypeVisitor.ts#L11

5) Extend schema generation to include interface.
