### ISSUE TITLE
Types missing for 'bson' in @graphback/core

### ISSUE THREAD

**Issue by Eunovo** [aerogear/graphback#1915]
* **Module**: @graphback/core
* **Version**: 0.16.0-beta1
* **yarn version:** 0.1.2
* Screenshot of console log

![image](https://user-images.githubusercontent.com/37949128/90776044-808de500-e2f1-11ea-9456-0864ba9bf985.png)

I get above error when I try to compile my typescript project

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by machi1990** [comment]
Is it the Graphback project that you are compiling?

**Comment by Eunovo** [comment]
No. I'm using the graphback-core in offix

**Comment by machi1990** [comment]
Ah strange that it tries to compile an external dependency (might be how the project is configured).

**Comment by wtrocki** [comment]
Yep... This is due to using it within CLI. This can be replicated by using generate from cli.
