### ISSUE TITLE
Avoid querying relationship field from GraphbackService (database) when relationship owner contains full dataset

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1925]
Consider the business model below:

```graphql
""" @model """
type Comment {
  id: ID!
  text: String
  createdAt: GraphbackDate
  """
  @oneToOne
  """
  metadata: CommentMetadata
}

""" @model """
type CommentMetadata {
  id: ID!
  metadata: GraphbackJSON
  """
  @oneToOne
  """
  comment: Comment
}

type Query {
  todaysCommentWithMetadata: [Comment]
}
scalar GraphbackJSON
scalar GraphbackDate
```

**Is your feature request related to a problem? Please describe.**

The code of my custom resolver `todaysCommentWithMetadata`, returns an array of `Comment` each with their associated `Metadata` all in a single database query. However, when I enabled database query logging, I noticed two queries being sent to the database 

1. My custom database query
2. The query to resolve relationship. **This should not happen since the first query has all the data**

**Describe the solution you'd like**

Just one query sent to the database as my custom resolver contain the full dataset and there is no need to re-fetch the "metadata" field from database .

We should only retrieve the relationship field from database if it is not in the parent object. 
 
With something like 
```ts
if (parent[relationOwner]) {
   return parent[relationOwner];
}
```

This should happen before the following lines:
- https://github.com/aerogear/graphback/blob/7d4f80c47cb5ff0c58da9dd493c424ffd0015fcb/packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts#L697
- https://github.com/aerogear/graphback/blob/7d4f80c47cb5ff0c58da9dd493c424ffd0015fcb/packages/graphback-codegen-schema/src/SchemaCRUDPlugin.ts#L732

**Describe alternatives you've considered**
N/A

**Comment by craicoverflow** [comment]
Seems very sensible, +1.
