### ISSUE TITLE
Delta - mutiple records lost

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1928]
This is hard to replicate but when having multiple changes done in the same milliseconds (lastUpdated is the same) Only single record is returned

**Comment by wtrocki** [comment]
CC @ssd71 

BTW. I have made manual changes to replicate this problem (it was not possible to get that without manual change)

**Comment by wtrocki** [comment]
Swapping from `new Date().getTime` to process.hrtime() when saving to original table using soft deletes will fix that.

If we have a range for that large number - if not let's close this issue

**Comment by ssd71** [comment]
[process.hrtime()](https://nodejs.org/api/process.html#process_process_hrtime_time) gives two numbers instead of one, process.hrtime.bigint() gives us BigInts which are not supported by MongoDB as they are arbitrary precision, This wouldn't be a simple fix I am afraid

**Comment by wtrocki** [comment]
So we cannot save them as strings? String indexes will have the same implication as number indexes

**Comment by ssd71** [comment]
> String indexes will have the same implication as number indexes

Yep, sorry for missing that out plus some more stuff:
From same page:
> These times are relative to an arbitrary time in the past, and not related to the time of day and therefore not subject to clock drift. The primary use is for measuring performance between intervals
- process.hrtime doesn't return timestamp

- Scalar Support (not 100% sure but we cannot use GraphbackTimestamp with this)

wdyt?

**Comment by wtrocki** [comment]
Closing then! Thank you for investigation
