### ISSUE TITLE
Conflict metadata missing 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1929]
I is really confusing when replication returns different data that was sent and if we have other changes that were done offline we need to update them to avoid further conflicts. I have tried to check version that is returned but this also can be iterated. We need to add some info about conflict in extension or something

**Comment by wtrocki** [comment]
CC @ssd71 

Very important and simple to achieve. We need extensions

**Comment by craicoverflow** [comment]
What is the state of this issue?

**Comment by wtrocki** [comment]
Closing. No simple way to solve it
