### ISSUE TITLE
Delta - missing validation for invalid conflict key

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1930]
We enable conflict per model and not operation. If someone will pass operation name should get error.

**Comment by wtrocki** [comment]
CC @ssd71

**Comment by ssd71** [comment]
@wtrocki Could you describe a setup where one should get an error?

**Comment by wtrocki** [comment]
validation should go thru the keys and check if key exist (is represented by model).

"user": {} // OK

"getUzer": {} // Not ok
