### ISSUE TITLE
_deleted is not returned when requested

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1939]
We do not have _deleted returned in sync queries despite objects being deleted. 

## Steps to reproduce

1. Delete item
1. Sync using timestamp - deletion information is not available despite it was requested.
It should have _deleted true/false

**Comment by wtrocki** [comment]
CC @ssd71 critical bug

**Comment by machi1990** [comment]
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by wtrocki** [comment]
Bug on the client side.

**Comment by ssd71** [comment]
@wtrocki   Does the delta type have a _deleted field?

**Comment by wtrocki** [comment]
it is bug on the client - I cannot have deleted in the schema, because it will be used to build mutation queries. so need to pass _deleted only for sync call. Closing. 

Sorry for missunderstanding

**Comment by ssd71** [comment]
> Bug on the client side. Invalid issue

Cool
