### ISSUE TITLE
Cannot read property 'and' of undefined

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#1941]
graphback version: 0.16.0-alpha5

All of my subscriptions without filter now return this error:

```json
{
  "errors": [
    {
      "message": "Cannot read property 'and' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "newIncoming_queue_items"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```
The error above came from this subscription query:

```graphql
subscription {
  newIncoming_queue_items {
    id
  }
}
```
Any new subscription without a filter is doing this.

This is another example of something very core breaking when I upgrade. My subscriptions were all working very reliably before this change. Seems regressions are easily added. I'm trying to take graphback into production, but now I fear any updates

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by wtrocki** [comment]
Easy fix. Workaround is to pass empty object as filter

**Comment by machi1990** [comment]
Hi @lastmjs thank for reporting this issue. It should be an easy fix to make sure that it's retro-compatible with previous releases. 
I'll take care of this and drop a beta release. 
 
> This is another example of something very core breaking when I upgrade. My subscriptions were all working very reliably before this change. Seems regressions are easily added. I'm trying to take graphback into production, but now I fear any updates

Our target is to make Graphback stable enough and we appreciate your inputs. Sorry for this issues you are running into, they are top priority for us. Testing is an area that we are giving much focus, it may arrive that some test cases are missing as of this case we are working on covering this missing pieces.

**Comment by machi1990** [comment]
[0.16.0-beta2](https://github.com/aerogear/graphback/releases/tag/0.16.0-beta2) has been released and should effectively fix this issue.
