### ISSUE TITLE
Graphback CLI missing docs

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1954]
The graphback-cli doc page is empty at the moment - https://graphback.dev/docs/cli/graphback-cli 

Opening this issue to add a paragraph or two.

**Comment by machi1990** [comment]
/cc @craicoverflow, @wtrocki
Automatically generated comment to notify maintainers

**Comment by craicoverflow** [comment]
https://graphback.dev/docs/cli/graphback-cli
