### ISSUE TITLE
Logical OR operator is not working correctly in MongoDB query builder

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1963]
* **Module**: `graphback-runtime-mongodb`
* **Version**: `0.16.x` but this issue has probably always existed as the unit test did not correctly cover this case.
* **Node.js / npm versions:** *

The `or` operator is behaving like an `and` operator and will only return a match if both conditions are met.

```graphql
query {
  findNotes(filter: {
    title: {
      startsWith:"[DRAFT]"
    },
    or: {
      description: {
        endsWith: "[DRAFT]"
      }
    }
  }) {
    items {
      _id
      title
      description
    }
  }
}
```

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by craicoverflow** [comment]
I think the issue with this stems from the fact that the logical OR operator in the CRUD spec accepts an object only, whereas the MongoDB $or operator only accepts an array:

```bash
{ $or: [ { <expression1> }, { <expression2> }, ... , { <expressionN> } ] }
```

Therefore the remapping of the $or conditions attempted in https://github.com/aerogear/graphback/pull/1985 is kind of impossible.

**Comment by machi1990** [comment]
> I think the issue with this stems from the fact that the logical OR operator in the CRUD spec accepts an object only, whereas the MongoDB $or operator only accepts an array:
> 
> ```shell
> { $or: [ { <expression1> }, { <expression2> }, ... , { <expressionN> } ] }
> ```

I think accepting an array of expression makes sense and in this case it will mean that the condition is satisfied when either of the expression evaluates to true. 
 
> Therefore the remapping of the $or conditions attempted in #1985 is kind of impossible.
> 
> We will have to change the `or` operator to accept an array, but this will also require changes in Postgres.

How big is this change?

**Comment by wtrocki** [comment]
Quick discussion needed.

**Comment by craicoverflow** [comment]
Ah my bad - I can see that `or` is already a GraphQLList. Need to look into this.

**Comment by wtrocki** [comment]
> We will have to change the or operator to accept an array, but this will also require changes in Postgres.

Also Schema and AWS compatibility.
Can we use/recomend nested syntax for or?
