### ISSUE TITLE
The closing block of a generated Graphback query is not inline

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#1965]
* **Module**: graphback-codegen-client
* **Version**: *
* **Node.js / npm versions:** *

This is a minor styling bug I noticed in the queries that are generated by the `@graphback/codegen-client` plugin.

This does not affect functionality in any way, but would be nice to get fixed.

```patch
query findNotes($filter: NoteFilter, $page: PageRequest, $orderBy: OrderByInput) {
    findNotes(filter: $filter, page: $page, orderBy: $orderBy) {
      items {
        ...NoteExpandedFields
      }
      offset
      limit
      count
    }
- }
+}
```

### Testing your changes

From the `templates/ts-react-apollo-client` directory, run `yarn graphback generate`.

Note, that you need to change the path of `extensions.graphback.model` in the `.graphqlrc` file to point to a valid model file ([this one](https://github.com/aerogear/graphback/blob/f262f4cd5d36dc1ef13e9d7188ce9ff7389898ab/templates/ts-apollo-postgres-backend/model/datamodel.graphql#L21)).

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by shivambhatia5432** [comment]
Hi, I would like to take this issue can you guide me in right direction.

**Comment by craicoverflow** [comment]
Hi @shivambhatia5432 - the issue description should hopefully have enough information for you to get started. The best thing to do is understand what Graphback does by looking at [our docs](https://graphback.dev/docs/next/introduction).

This issue specifically is located in the [ClientCRUD Plugin](https://graphback.dev/docs/next/plugins/crud-client). You can find this in the `graphback-codegen-client` package in this repo.

**Comment by shivambhatia5432** [comment]
Hi, can you please elaborate the issue I am on exact same line and file you are talking about, I cannot understand meaning of " to be inline with `q`." as I am not able to generate Graphback query.
Thanks for assigning me this issue.

**Comment by craicoverflow** [comment]
Are you in the `graphback.graphql` file? This file is generated when you run `yarn graphback generate` from the template. The ClientCRUDPlugin is a plugin which generates this code and writes it to the `graphback.graphql` file.

> I cannot understand meaning of " to be inline with q.

Sorry, I should be more clear. The closing bracket should be at the same indentation level as the `q` from the start of `query findNotes`.

The templates are created in https://github.com/aerogear/graphback/blob/f8ab9f3cf4a8fe58379a0eac1655f0e9c825d82b/packages/graphback-codegen-client/src/templates/gqlTemplates.ts

**Comment by shivambhatia5432** [comment]
![Screenshot 2020-09-22 at 10 42 34 PM](https://user-images.githubusercontent.com/50217679/93914956-ee7c6080-fd24-11ea-9ec2-c9d8794afe1d.png)
Issue while running yarn graphback generate

**Comment by wtrocki** [comment]
Templates are in the workspace. You need to issue this command in the actual template folder. 
Generate generates only in single template etc.

**Comment by shivambhatia5432** [comment]
I think I have corrected the issue please check at pull request #2107 , this is my first open source contribution so thank you for helping me and I would love to contribute more to your organisation.

**Comment by wtrocki** [comment]
@shivambhatia5432 Thank you for creating that. You can always join our community chat if you have any questions: https://discord.com/invite/mJ7j84m

**Comment by RinkiyaKeDad** [comment]
Hey! Is someone still working on this issue? If not then I'd like to try and solve it.

**Comment by craicoverflow** [comment]
I've updated the issue description with a guide on how to test your changes.

**Comment by craicoverflow** [comment]
Fixed by @RinkiyaKeDad in #2130 - amazing work man!

**Comment by RinkiyaKeDad** [comment]
Thanks for guiding me @craicoverflow @wtrocki @machi1990 :))

**Comment by machi1990** [comment]
Our pleasure, thanks for the great contribution @RinkiyaKeDad . Looking forward to many more from you ;-)
