### ISSUE TITLE
repurpose templates to have `.graphqlrc.yml` file instead of `codegen.yml`

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#1977]
https://github.com/aerogear/graphback/blob/56266d28e301367f49788d17b5a86a592ae107f5/templates/ts-apollo-mongodb-backend/codegen.yml does this be re-purposed to a `.graphqlrc.yml` file?

**Comment by machi1990** [comment]
/cc @craicoverflow, @wtrocki
Automatically generated comment to notify maintainers

**Comment by wtrocki** [comment]
Yes we should. We did not do that because graphql-cli required graphback and we had problem with the older graphback version available. Since moving all the work here we will not have this problem anymore.

**Comment by machi1990** [comment]
> Yes we should. We did not do that because graphql-cli required graphback and we had problem with the older graphback version available. Since moving all the work here we will not have this problem anymore.

Thanks @wtrocki for the reply. I've renamed the issue so that it does not look like a question. 

For the record the client side template has the file https://github.com/aerogear/graphback/blob/56266d28e301367f49788d17b5a86a592ae107f5/templates/ts-react-apollo-client/.graphqlrc.yml

**Comment by wtrocki** [comment]
This also blocks graphql-cli integration as it bases on graphql-config
