### ISSUE TITLE
Graphback templates readme is missing details

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#1993]
Our readmes missing details about project structure, how to edit, create resolver etc. 
We can link to some specific graphback docs if needed but starting with template has now only info about running it.

**Comment by machi1990** [comment]
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by machi1990** [comment]
The server side READMEs have this line:
`For more on customising your Graphback application, check out [our docs](https://graphback.dev/docs/gettingstarted)` which is more general. What I think is desirable is a short into on:
1. Modifying and customizing model, which file to modify and a link to relevant graphback docs
2. Writing custom resolvers , which file to modify and a link to the docs 
3. How to deploy / dockerise the application ? (Is it far fetched)

Anything else?

**Comment by wtrocki** [comment]
I was hoping to have general info on the structure of the templates - Where are the resolvers.
What can be changed and what is static etc. Getting started gives concepts and now we can link them in template with some couple sentences. Same for the client side. We need to mention config files etc.

**Comment by wtrocki** [comment]
Suggested chapters:

- What technologies are used
- Repository structure
- Running application
- Modifying server
- (in client) Adjusting to changes on the server
- (in client) Modifying client

> Modifying and customizing model, which file to modify and a link to relevant graphback docs

> Writing custom resolvers , which file to modify and a link to the docs

Yep. Where are they. How to generate typings and link to docs if we have docs for it.

> How to deploy / dockerise the application ? (Is it far fetched)

If there is dockerfile it might be good. If not ignore it.
