### ISSUE TITLE
Semantics of how the `or` operator should be used

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2009]
* **Module**: `@graphback/runtime-mongodb`, `@graphback/runtime-knex`
* **Version**: *
* **Node.js / npm versions:** NA

When combined with the `root` query operators, the `or` operator evaluates to `find X where <root query conditions> OR <or conditions>`. Take the example below. This outputs the following pseudo-query in both Postgres and MongoDB: `find Blogs where name is "blog3" or name is "blog3"` or condition3....

```graphql
{
  findBlogs(filter: {name: {eq: "blog3"}, or: [{name: {eq: "blog1"}}]}) {
    items {
      id
      name
    }
  }
}
```

Upon initial raising of this as being potentially incorrect by @machi1990 and then checking out alternative libraries (namely AWS AppSync), the query above should output: `find Blogs where name is "blog3" and (name is "blog3" || condition2 || condition 3)...`

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by craicoverflow** [comment]
Thanks for highlighting this one @machi1990 - this is in fact a bug and should be actioned ASAP.

**Comment by craicoverflow** [comment]
Going to start this.

**Comment by machi1990** [comment]
Thanks @craicoverflow

**Comment by CoreyKovalik** [comment]
This should be re-opened, as I believe there are still bugs in the knex query builder.  We are experiencing that this simply _**does not work as expected**_ for Postgres + Knex for any and/or query on the same field.

Example:

```
// returns no results
query {
  findLocations (filter: { country_code: { eq: "US" }, or: { country_code: { eq: "CN" } } })
  
// the following 2 queries seem to work as expected, and return different results....
query {
  findLocations (filter: { country_code: { eq: "US" }, or: { city: { contains: "a" } } })

query {
  findLocations (filter: { country_code: { eq: "CN" }, or: { city: { contains: "a" } } })
  
// However, `or` seems to be operate no different than `and`.
// Expected: locations return with Either `country_code` === "US" or countries starting with `C`, i.e. `China`
// Actual: No results, assuming because "United States" doesn't have "C"
findLocations (filter: { country_code: { eq: "US" }, or: { country_name: { contains: "C" } } }
```
