### ISSUE TITLE
Create Demo plan

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#201]
Create a top-level demo plan that will cover functionalities we have.
We need to plan as the number of functionalities we have is very large with multiple options to go with. In plan, we can cover - what template we want to show. What database to start with etc. 

Supper top level so we can see how we can demo it and how long it will take.

**Comment by ankitjena** [comment]
- Do graphback init
- Select apollo-starter-template
- Select PostgreSQL as database
- Select Note model
- Talk about generation config, edit it in the config.json
- Open the model, edit it with directives and custom queries and mutations.
- Do graphback generate
- Write custom function for the generated empty stubs
- Do graphback db
- Run graphback watch or npm start

**Comment by wtrocki** [comment]
I love it I would just drop extra step:

```
1. Do graphback init
1. Select apollo-starter-template
1. Select PostgreSQL as database
1. Select Note model
1. Talk about generation config, edit it in the config.json
1. Open the model, edit it with directives and custom queries and mutations.
1. Insert one of the generation directives
1. Write a custom function for the generated empty stubs
1. Do graphback generate
1. **Do graphback db**
1. Run graphback watch or npm start
1. Open playground (have queries and mutations in clipboard)
1. **Show it working end to end** 
1. Show query
1. Show mutation
1. Show subscription
1. **Talk about other templates - rest/graphql.js

```

**Comment by wtrocki** [comment]
Generally, this needs to be done by single person as every step relies on state.

**Comment by ankitjena** [comment]
I'll go through the process a few times and check.
What will be the plans for future ?
- Support other databases and ?

**Comment by wtrocki** [comment]
> I'll go through the process a few times and check. 

No need. We will do release and cover it plus we have demo call for the same purpose.

> What will be the plans for future?

https://github.com/aerogear/graphback/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3Agraphback.next

**Comment by ankitjena** [comment]
> https://github.com/aerogear/graphback/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3Agraphback.next

Well yes!

**Comment by wtrocki** [comment]
Going to work on slides.
