### ISSUE TITLE
Improve documentation for our templates (mainly readme.md)

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#2013]
Documentation should contain basic information about what is the picked technology: express.
What is the GraphQL technology. Apollo etc. What tools are required before development (codegen, graphback generate) and how they work into complete development workflow. 

Current readme has this info but it needs to be extended.

**Comment by machi1990** [comment]
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by RinkiyaKeDad** [comment]
Hi! I'm new to this repo and would like to work on this issue. Can you point me in the right direction? Apart from the mentioned stuff in the issue what all should I include in the README?

**Comment by wtrocki** [comment]
@RinkiyaKeDad Hi. Thanks for reaching out. 
Our repo templates contains readme:
https://github.com/aerogear/graphback/tree/master/templates

Readme needs to have more information about what technologies are used for testing, code generation etc. Similairly to https://github.com/facebook/create-react-app

**Comment by RinkiyaKeDad** [comment]
Thanks for responding @wtrocki. As far as I understand the READMEs in all four of the folders need to updated. I'll be starting with the 'ts-react-apollo-client' one first. I'm a bit new to this so would like to confirm that I'm to fork the repo, make the changes in the readme and create a pull request right?

**Comment by craicoverflow** [comment]
Hey @RinkiyaKeDad! Thanks for offering to help us out! Have you used Graphback before? I would first suggest playing around with Graphback and using the templates to get an understanding of how they work.

Yes, you fork the repo, create a new branch and create a PR!

**Comment by RinkiyaKeDad** [comment]
Hi @craicoverflow! I thought of using Graphback but hesitated since I have never used TypeScript before. But I'll follow your suggestion and try again in order to get a better understanding before I begin updating the README.

**Comment by craicoverflow** [comment]
Have you used JavaScript before?

**Comment by RinkiyaKeDad** [comment]
Yes I have.

**Comment by craicoverflow** [comment]
That's great - to use the templates JavaScript knowledge should be sufficient - TypeScript is a superset of JavaScript so they are very similar.

**Comment by RinkiyaKeDad** [comment]
> What tools are required before development (codegen, graphback generate) and how they work into complete development workflow.

I have added a section of dependencies in the README where I've briefed about GraphQL, Apollo Client and Material UI. But I'm not quite sure what this line means? I see that there is a generate script in the package.json,
```  "generate": "graphback generate && graphql codegen" ```
So from what I understand till now ``` graphback generate``` is to regenerate the files after some changes have been made. But what is ```codegen``` and ```graphql codegen```?

**Comment by wtrocki** [comment]
> So from what I understand till now graphback generate is to regenerate the files after some changes have been made. But what is codegen and graphql codegen?

Amazing questions! Absolutely love that you have reached out and helped us as this really shows that.. in fact we need better README.md

For graphback generate see:
https://graphback.dev/docs/cli/graphback-cli

For codegen generate see:
https://graphql-code-generator.com/

**Comment by RinkiyaKeDad** [comment]
Thanks a lot @wtrocki! Have gone through them a created a PR for the README of the React Template. Please suggest me what more can I imporve in the README.

**Comment by RinkiyaKeDad** [comment]
Hey before I start working on the other READMEs, I wanted to ask that if something is similar across the templates is it fine if I use the same descriptions or is it prefered to re-write it? Like if lets say another template also uses React then can I copy over what I wrote for React in the previous README?

**Comment by craicoverflow** [comment]
You can likely reuse some bits of information from the React template around Graphback, but since all the other templates are backend templates, the content will be pretty different overall.

**Comment by RinkiyaKeDad** [comment]
Got it!

**Comment by RinkiyaKeDad** [comment]
Was going through the mongodb template files. ```yarn generate``` there too has the same funtionality as far as I could understand, right?

**Comment by wtrocki** [comment]
Yep. It was shortcut to not explain complexities of using 2 tools.

**Comment by RinkiyaKeDad** [comment]
So should I use the same explanation?

**Comment by craicoverflow** [comment]
Yes you can. The best thing to do is create a PR and we can review whether it needs to be adjusted from there.

**Comment by craicoverflow** [comment]
Fixed by @RinkiyaKeDad - amazing work!

**Comment by machi1990** [comment]
Thanks @RinkiyaKeDad for the amazing contributions. Looking forward to many more from you <3

**Comment by RinkiyaKeDad** [comment]
Thanks :) Will surely be contributing more.

**Comment by craicoverflow** [comment]
That's great to hear! :+1:
