### ISSUE TITLE
Custom resolvers info object needs to be better documented

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#2033]
Issue from https://github.com/aerogear/OpenVolunteerPlatform/pull/153:

> The main issue with that I saw was that the info: GraphQLResolveInfo was passed to every service call which resulted in a "wrong" projection being sent to the MongoDB. When the assignVolunteers mutation is called, the info parameter will contain resolvable fields for DailyActionPlan model and not any other business model meaning that once the query is sent to db it won't err (as a relational database would) but simply tries its best to project the db results to the requested fields. If this query is sent to retrieve a list of Products, it will simply return _id, as the other fields do not belong to the product collection but dailyactionplan.

Better documentation is needed.

**Comment by machi1990** [comment]
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers
