### ISSUE TITLE
Second database migration throws an error

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2047]
* **Module**: `graphql-migrations`
* **Version**: 0.16

This occurs when the primary key field is NOT "id" - it fails on `uuid: ID`, `_id: ID` etc.

```shell
> yarn develop
yarn run v1.22.5
$ ts-node src/index.ts
🚀  Server ready at http://localhost:4000/graphql
Migrated database
^C
> yarn develop
yarn run v1.22.5
$ ts-node src/index.ts
🚀  Server ready at http://localhost:4000/graphql
(node:71304) UnhandledPromiseRejectionWarning: error: alter table "public"."note" alter column "_id" drop not null - column "_id" is in a primary key
```

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by craicoverflow** [comment]
I think we need an automated test or unit test that covers consecutive migrations like this.

**Comment by machi1990** [comment]
Looks like the diff algorithm needs some love :-)

**Comment by craicoverflow** [comment]
Patch available in https://github.com/aerogear/graphback/releases/tag/1.0.0-beta2
