### ISSUE TITLE
Automate changelog / release notes generation

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#2052]

**Comment by machi1990** [comment]
/cc @craicoverflow, @wtrocki
Automatically generated comment to notify maintainers

**Comment by craicoverflow** [comment]
We could consider a bot that does all: handles release and changelog generation.

See https://github.com/semantic-release/semantic-release as a good example. I was particularly impressed by it, as it adds a comment to issues with linked PRs to information the OP what version their fix/feature was included in. It is worth investigating.

**Comment by machi1990** [comment]
> We could consider a bot that does all: handles release and changelog generation.
> 
> See https://github.com/semantic-release/semantic-release as a good example. I was particularly impressed by it, as it adds a comment to issues with linked PRs to information the OP what version their fix/feature was included in. It is worth investigating.

Impressive. Can we try it out?

**Comment by craicoverflow** [comment]
Sure, I plan to do so once I get on top of some new issues in Graphback - our focus now is finding those bugs.
