### ISSUE TITLE
"npx graphback-cli generate" throws an error 

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#2054]
* **Module**: graphback-cli
* **Version**: 0.16.2
* **Node.js / npm versions:**
* Example/snippet of the model that is causing issue

```bash
npx graphback-cli generate
```

```log
Cannot find module 'graphql'
Require stack:
- .npm/_npx/83078/lib/node_modules/graphback-cli/node_modules/@graphback/core/dist/crud/mappingHelpers.js
- .npm/_npx/83078/lib/node_modules/graphback-cli/node_modules/@graphback/core/dist/crud/index.js
- .npm/_npx/83078/lib/node_modules/graphback-cli/node_modules/@graphback/core/dist/index.js
- .npm/_npx/83078/lib/node_modules/graphback-cli/node_modules/graphback/dist/index.js
- .npm/_npx/83078/lib/node_modules/graphback-cli/dist/components/generate.js
- .npm/_npx/83078/lib/node_modules/graphback-cli/dist/components/index.js
- .npm/_npx/83078/lib/node_modules/graphback-cli/dist/index.js
```

@craicoverflow I know you once encountered a similar issue, not sure if its related so opening this here to see if we are planning to do anything about it.

**Comment by machi1990** [comment]
/cc @craicoverflow, @wtrocki
Automatically generated comment to notify maintainers

**Comment by craicoverflow** [comment]
This is expected, users will have to run `yarn graphback generate` from inside their template for it to work. I see this as a docs issue.

**Comment by machi1990** [comment]
> This is expected, users will have to run `yarn graphback generate` from inside their template for it to work. I see this as a docs issue.

Sure, it what I have gone with when documenting the generate command #2053.  

But id the project is missing `graphql`, it will still err right? What would be the impact of making  `graphql` a dependency in the cli?

**Comment by craicoverflow** [comment]
Yes it would also error, the template will need graphql installed to use the generate command

> What would be the impact of making graphql a dependency in the cli?

This would fix the CLI to a certain version, the CLI might have v15 of graphql but the user uses v14, these are incompatible.

**Comment by machi1990** [comment]
> Yes it would also error, the template will need graphql installed to use the generate command

I think I've that explicit-ed in the docs. 

> > What would be the impact of making graphql a dependency in the cli?
> 
> This would fix the CLI to a certain version, the CLI might have v15 of graphql but the user uses v14, these are incompatible.

Sure, I am going to close this as docs will indicate how to use the cli.
