### ISSUE TITLE
"Error: 'Subscription' defined in resolvers, but not in schema" when subscriptions are disabled

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#2070]
* **Module**: schema-plugin
* **Version**: 0.16.2
* **Node.js / npm versions:**
* Example/snippet of the model that is causing issue

Subscription disabled with
```
crud: {
      create: false,
      subCreate: false,
      subUpdate: false,
      subDelete: false
    },
```

**Comment by machi1990** [comment]
/cc @craicoverflow, @wtrocki
Automatically generated comment to notify maintainers

**Comment by craicoverflow** [comment]
Patch available in https://github.com/aerogear/graphback/releases/tag/1.0.0-beta2

**Comment by evanshortiss** [comment]
Haven't had a chance to test yet but will ping you guys when we update builds. Thank you 🥳
