### ISSUE TITLE
DataSync - creating new object is not assigning _version field properly.

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#2079]
WHen creating item I would expect version to be:

returned and 1. I get version as null all the time.

**Comment by wtrocki** [comment]
@ssd71 Is this a bug or somewhat clients should pass _version to server as 1 all the time?

**Comment by machi1990** [comment]
/cc @ssd71
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by wtrocki** [comment]
I haven't used official api. There are two ways to create datastore. Seems like duplicate of the issue created by @ssd71 anyway.
