### ISSUE TITLE
Blog post: Introduction to GraphQL and GraphBack 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#208]
## Motivation

Blog post from the point of view of the person trying to start with GraphQL explaining concepts and introducing graphback

CC @MStokluska for ideas/discussion

**Comment by MStokluska** [comment]
The idea for now is to create an entry level introduction to GraphQL, with no front end covered. Something clear - but not oversimplified. Make it a little bit difficult so whoever is going to follow the tutorial will appreciate what GraphBack can do ! 
My primary target audience are students that are only starting with client server architecture and REST. So 3rd - 4th years in college. 
Any suggestions ?

**Comment by wtrocki** [comment]
Sound like very good plan. Over the next week we are going to focus on generating client so you could get that for free

**Comment by MStokluska** [comment]
@wtrocki think this can be closed?
