### ISSUE TITLE
init method for graphback on the website is broken

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#2083]
* **Module**:
* **Version**:
* **Node.js / npm versions:**
* Example/snippet of the model that is causing issue

**Comment by wtrocki** [comment]
critical issue

**Comment by machi1990** [comment]
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by machi1990** [comment]
Fixed by https://github.com/aerogear/graphback/pull/2084
