### ISSUE TITLE
There is no Fullstack DataSync template available to choose in CLI

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2102]
* **Module**: create-graphback
* **Version**: 1.0.0
* **Node.js / npm versions:**

I would expect to be able to choose a FullStack DataSync template, but there is none. Is this by design or is it an oversight?

```
? Choose a template to bootstrap 
  apollo-fullstack-react-postgres-ts 
  apollo-fullstack-react-mongo-ts 
❯ apollo-mongo-server-ts 
  apollo-mongo-datasync-server-ts 
  apollo-postgres-server-ts 
```

**Comment by craicoverflow** [comment]
@wtrocki do you know if this needs to be added?

**Comment by machi1990** [comment]
/cc @ssd71
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by wtrocki** [comment]
Design. Current template will be replaced by datasync-starter enterprise one with datasync capabilities.
