### ISSUE TITLE
Could not find a declaration file for module 'bson'

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2103]
* **Module**: `@graphback/core`
* **Version**: *
* **Node.js / npm versions:**
* Example/snippet of the model that is causing issue

This error occurs when I run `yarn build` from the Postgres template

```shell
> yarn build
yarn run v1.22.5
$ tsc
node_modules/@graphback/core/types/runtime/QueryFilter.d.ts:1:26 - error TS7016: Could not find a declaration file for module 'bson'. '/home/ephelan/code/playground/graphback/testing/next/postgres-backend/node_modules/bson/lib/bson.js' implicitly has an 'any' type.
  Try `npm install @types/bson` if it exists or add a new declaration (.d.ts) file containing `declare module 'bson';`

1 import { ObjectID } from 'bson';
                           ~~~~~~


Found 1 error.

error Command failed with exit code 2.

```

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by machi1990** [comment]
Does the error occur too when the template is outside the Graphback repo?

**Comment by craicoverflow** [comment]
I only experienced this when outside the repo - I am doing all testing of templates in isolation.

**Comment by machi1990** [comment]
Okay, thanks for clarifications.
