### ISSUE TITLE
How do I generate updated client documents and fragments for data synchronization?

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2105]
The `DataSyncPlugin` updates the schema with the following:

- `sync<T>` queries for each of the models with data sync enabled
- updates the models with new fields, such as `_version`, `_lastUpdatedAt`
- Adds new container types for deltas

However there is no plugin available to generate the associated client-side queries and update the fragments.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by wtrocki** [comment]
Offix DataStore works with those out of the box. There is actually a lots of extra handling required on the client to handle those so generating just queries makes no sense for us.

**Comment by craicoverflow** [comment]
Thanks.
