### ISSUE TITLE
Issue with setting up subscriptions

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#2113]
* **Module**: 1.0.0-beta5
* **Version**: core
* **Node.js / npm versions:**
* Example/snippet of the model that is causing issue

```graphql
"""
@model(
  find: false,
  findOne: false,
  create: false,
  update: false,
  delete: false,
  subCreate: true,
  subUpdate: true,
  subDelete: true
)
"""
type Addresses {
  id: ID
  customer_id: ID
  street: String
  city: String
  state: String  
  zip: String
  type: AddressType
}

"""
@model(
  find: false,
  findOne: false,
  create: false,
  update: false,
  delete: false,
  subCreate: true,
  subUpdate: true,
  subDelete: true
)
"""
type Customers {
  id: ID
  first_name: String!
  last_name: String!
  email: String
}

enum AddressType {
  SHIPPING
  BILLING
  LIVING
}
```

I want to activate subscriptions only with the above business model but it fails with:

```log
Error: Query root type must be provided.
```

If I change the mode to activate at least one query type generation e.g by generate a find all queries

```graphql
"""
@model(
  find: true,
  findOne: false,
  create: false,
  update: false,
  delete: false,
  subCreate: true,
  subUpdate: true,
  subDelete: true
)
"""
type Addresses {
  id: ID
  customer_id: ID
  street: String
  city: String
  state: String  
  zip: String
  type: AddressType
}

"""
@model(
  find: true,
  findOne: false,
  create: false,
  update: false,
  delete: false,
  subCreate: true,
  subUpdate: true,
  subDelete: true
)
"""
type Customers {
  id: ID
  first_name: String!
  last_name: String!
  email: String
}

enum AddressType {
  SHIPPING
  BILLING
  LIVING
}
```
I am getting 

```
[Error: "Subscription" defined in resolvers, but not in schema]
```
I believe this is related to https://github.com/aerogear/graphback/issues/2070

/cc @craicoverflow

**Comment by machi1990** [comment]
/cc @craicoverflow, @wtrocki
Automatically generated comment to notify maintainers

**Comment by wtrocki** [comment]
@machi1990 workaround for this is to add empty query type in model. In practical scenarios this problem will not exist.

**Comment by machi1990** [comment]
> @machi1990 workaround for this is to add empty query type in model. In practical scenarios this problem will not exist.

Yeap, I know. That's what I am using now to get me moving.

**Comment by craicoverflow** [comment]
`Error: Query root type must be provided.` this error comes from GraphQL library - a schema without a Query root type is not valid. I'm wondering if it is something we should not even consider looking to "fix"?

> [Error: "Subscription" defined in resolvers, but not in schema]

Strange, thought that was resolved, I will take a look.

**Comment by wtrocki** [comment]
> Error: Query root type must be provided.

This is happening only for graphql 0.14.0 (0.15 graphql schema doesn't require query to be there). Confirmed in datasync starter.

**Comment by craicoverflow** [comment]
> > Error: Query root type must be provided.
> 
> This is happening only for graphql 0.14.0 (0.15 graphql schema doesn't require query to be there). Confirmed in datasync starter.
> 

I am seeing the error happening in the templates right now which use 15.3.0:

```

/home/ephelan/code/aerogear/graphback/node_modules/graphql/type/validate.js:71
    throw new Error(errors.map(function (error) {
          ^
Error: Query root type must be provided.
```

**Comment by machi1990** [comment]
> `Error: Query root type must be provided.` this error comes from GraphQL library - a schema without a Query root type is not valid. I'm wondering if it is something we should not even consider looking to "fix"?

If we have a fix in place that would be welcomed e.g having an empty `type Query {}` etc.

**Comment by craicoverflow** [comment]
> If we have a fix in place that would be welcomed e.g having an empty `type Query {}` etc.

GraphQL did not like that:

```shell

/home/ephelan/code/aerogear/graphback/node_modules/graphql/error/syntaxError.js:15
  return new _GraphQLError.GraphQLError("Syntax Error: ".concat(description), undefined, source, [position]);
         ^
GraphQLError: Syntax Error: Expected Name, found "}"
```

**Comment by machi1990** [comment]
> > If we have a fix in place that would be welcomed e.g having an empty `type Query {}` etc.
> 
> GraphQL did not like that:
> 
> ```shell
> /home/ephelan/code/aerogear/graphback/node_modules/graphql/error/syntaxError.js:15
>   return new _GraphQLError.GraphQLError("Syntax Error: ".concat(description), undefined, source, [position]);
>          ^
> GraphQLError: Syntax Error: Expected Name, found "}"
> ```


Ouuch.. what about `type Query` will work as an empty query object? Otherwise, we can close the issue for subscriptions and direct users to a workaround as it is more an upstream issue.

**Comment by craicoverflow** [comment]
Fix available in https://github.com/aerogear/graphback/releases/tag/1.0.0-beta6
