### ISSUE TITLE
[Error: "Mutation" defined in resolvers, but not in schema]

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2117]
* **Module**: `@graphback/datasync`
* **Version**: 1.0.0-beta*
* **Node.js / npm versions:**
* Example/snippet of the model that is causing issue

This error is occurring when the DataSync plugin is used but mutations are disabled.

https://github.com/aerogear/graphback/blob/8763612f240a59cd15c011333c7d6fab530050ec/packages/graphback-datasync/src/DataSyncPlugin.ts#L79-L84

This should be fixed in the DataSyncPlugin, but I will also see if we can prevent this my checking and removing empty resolver objects in `GraphbackCoreMetadata`

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki
