### ISSUE TITLE
Website has a typo

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2127]
[graphback.dev](https://graphback.dev) has a typo in the sidebar:

`Databases > Overiew`

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by apoorvakumar2306** [comment]
@craicoverflow can I work on this issue?

**Comment by craicoverflow** [comment]
Hi @apoorvakumar2306 thank you so much for looking to help out with the Graphback project! We would love if you could work on this issue. Could you give Graphback a :star: ?

**Comment by apoorvakumar2306** [comment]
Thank you @craicoverflow . Looking forward to solve other issues too.

**Comment by apoorvakumar2306** [comment]
Thank you @craicoverflow . I would love to work on this issue.

**Comment by craicoverflow** [comment]
Great, you can begin working on it whenever suits you. Just open a PR and we will review it.

**Comment by apoorvakumar2306** [comment]
@craicoverflow @machi1990 @wtrocki  It looks like some guy has already raised a PR without any discussion or approval of maintainer. Should I close my PR or not?

**Comment by craicoverflow** [comment]
Thanks for your contribution @apoorvakumar2306! Your code got merged :rocket: 

Generally we do not need to discuss or approve you working on an issue beforehand, as different people can have different ideas, so we do not want to limit them to just one person.

**Comment by machi1990** [comment]
This has been fixed by #2128 #2129
