### ISSUE TITLE
ClientSide plugin unable to generate subscription query unless otherwise mutation operation in model  is set to `true`

### ISSUE THREAD

**Issue by machi1990** [aerogear/graphback#2135]
* **Module**:  graphback/client-codegen
* **Version**: 1.0.1
* **Node.js / npm versions:**
* Example/snippet of the model that is causing issue

```graphql
"""
@model(create: false, update: false, delete: false, find: false, subCreate: true, subUpdate: true, subDelete: true)
"""
type Test {
  _id: GraphbackObjectID!
}
```

This will not generate any subscription. 

while:

```graphql
"""
@model(create: true, update: false, delete: false, find: false, subCreate: true, subUpdate: true, subDelete: true)
"""
type Test {
  _id: GraphbackObjectID!
}
``` 

Will only create the `newTest` subscription since the `@model.create` is set to true.

I think the generation should depend only on `subXXX` knobs.

**Comment by machi1990** [comment]
/cc @craicoverflow, @wtrocki
Automatically generated comment to notify maintainers

**Comment by wtrocki** [comment]
> Version: 1.0.1

I would see this as candidate for 1.0.2 :)

**Comment by machi1990** [comment]
We should be looking at these lines:

- https://github.com/aerogear/graphback/blob/2f8bb076b524c062e00e1cf1494d9af495bf3f12/packages/graphback-codegen-client/src/templates/gqlTemplates.ts#L168
- https://github.com/aerogear/graphback/blob/2f8bb076b524c062e00e1cf1494d9af495bf3f12/packages/graphback-codegen-client/src/templates/gqlTemplates.ts#L177
- https://github.com/aerogear/graphback/blob/2f8bb076b524c062e00e1cf1494d9af495bf3f12/packages/graphback-codegen-client/src/templates/gqlTemplates.ts#L186

and modify the three condition to only check for `t.crudOptions.subXXX`.


/cc @RinkiyaKeDad this is a good issue too if you are looking for something.
