### ISSUE TITLE
Change all test file suffixes to be `.test.ts`

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2136]
## Problem

All test files have the following naming convention:

`/tests/*Test.ts`

Examples:

- `KnexDbDataProviderTest.ts`
- `CRUDServiceTest.ts`
- `createInMemoryFilterPredicateTest.ts`

It is difficult to differentiate a test file from a regular module file at a glance, for example:

`createInMemoryFilterPredicateTest.ts` compared to `createInMemoryFilterPredicate.ts`.

## Solution

All test files should get renamed with a `.test.ts` suffix instead. This is probably the most common naming pattern used in JavaScript/TypeScript.

New naming pattern: `/tests/*.test.ts`

Examples:

- `KnexDbDataProvider.test.ts`
- `CRUDService.test.ts`
- `createInMemoryFilterPredicate.test.ts`

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by codetravellearn** [comment]
may i do it

**Comment by codetravellearn** [comment]
please

**Comment by craicoverflow** [comment]
Hi @codetravellearn - yes you can do this one. Thank you so much for offering to help! I will assign you for now, but if your PR does not progress I will eventually unassign you, so keep active and let us know if you are having issues.

First thing you should do is go to the CONTRIBUTING.md file to set up your development environment.

**Comment by Codedude1** [comment]
Wanna work

**Comment by craicoverflow** [comment]
@codetravellearn has been assigned this task @Codedude1. Can you please be more through in your comments and offer more than "Wanna work" for us to consider assigning you. Thanks.

**Comment by Odin94** [comment]
This one is still open, right?

Mind if I pick it up?

**Comment by craicoverflow** [comment]
Hi @Odin94!

There is currently a PR in progress but it has been pretty inactive for a couple of days. Of course, feel free to take it :+1: Thanks.
