### ISSUE TITLE
Compress website logo

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2137]
The main Graphback website logo is too large, which slows down webppage load time.

Image: https://github.com/aerogear/graphback/blob/master/website/static/img/logo.png

This image is PNG, 1.5Mb, 6378x5309. We should convert the image to JPG and make it smaller. I am not sure what sizes we should go with, as it probably needs web developer expertise or we will have to experiment. I am conscious of the fact that it is used as the main logo on the home page, so we will have to see how it looks.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by wtrocki** [comment]
🙏 Thank you so much @craicoverflow This is in fact the most overlooked detail - logo is huge!

**Comment by craicoverflow** [comment]
cc @kingsleyzissou any recommendations on sizes?

**Comment by wtrocki** [comment]
anything bellow 5mb will be success :D

**Comment by munishgarg-02** [comment]
Can you tell whether the image wil be used in the navbar or on the centre page?

**Comment by NecroTechno** [comment]
It looks like the maximum size it will display on the site is approximately 320x270, though keeping it a bit larger for other purposes might be best Also, keeping it a PNG to keep transparency is probably  a good idea as well. @munishgarg-02 it seems like it is used in both!

**Comment by craicoverflow** [comment]
> anything bellow 5mb will be success :D

It is currently 1.5Mb

**Comment by wtrocki** [comment]
@munishgang-02 hey.. We will need separate image for navbar (looks like we scale current one)

**Comment by munishgarg-02** [comment]
@craicoverflow Because man if the image will be used in the navigation bar, then you should use icon format of this image and if you want it on main page basically in center, then you have to compress the image a little bit.

**Comment by munishgarg-02** [comment]
@craicoverflow I think 1920X1080 will do the task for website.

**Comment by craicoverflow** [comment]
Yes, that would be great! And we can have a separate one for Navbar at much smaller size.

**Comment by kingsleyzissou** [comment]
I think as @NecroTechno mentioned, the main reason for using the PNG is the transparency. But we can certainly scale that down. 1920x1080 sounds more than reasonable.

**Comment by craicoverflow** [comment]
Fixed in #2140 - thanks @SgtWalking!
