### ISSUE TITLE
Update "Graphback init can create your app from following templates:"

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2142]
* **Module**: create-graphback
* **Version**: 1.0.1
* **Node.js / npm versions:**

The message "Graphback init can create your app from following templates:" is wrong - `Graphback init` should be replaced with `create-graphback`. Asdditionally, it should be highlighted as a code snippet with `chalk.cyan`.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by g-ravity** [comment]
I would like to take this up, if this is up for grabs.

**Comment by wtrocki** [comment]
Go for it.

**Comment by g-ravity** [comment]
Okay, I'll start working on it.
