### ISSUE TITLE
Replace "GitHub" text link in top nav with the GitHub logo

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2144]
The topnav has a link to the GitHub repo on https://graphback.dev - I think this would be way nicer as a GitHub logo instead. For example see https://v2.docusaurus.io/

Source to change: https://github.com/aerogear/graphback/blob/c306e17ec5dcbe5fa2d47043f64fcc3a26722e9a/website/docusaurus.config.js#L52

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by eftakhairul** [comment]
@craicoverflow  I am interested to try this one.

**Comment by wtrocki** [comment]
First PR counts :D
