### ISSUE TITLE
Jest is required to run tests but not part of dev dependencies

### ISSUE THREAD

**Issue by Odin94** [aerogear/graphback#2150]
* **All modules**:
* **1.0.1**:
* **Node.js v10.16.0 / npm 6.9.0**

Steps to reproduce:

* Clone fresh copy of repository
* Run `npm install`
* Run `npm test`

Output:

```
> graphback-monorepository@1.0.0 test C:\Users\kamme\Desktop\Repos\Hacktoberfest\graphback
> jest -w 1

'jest' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
```

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by Odin94** [comment]
Pull request to fix: https://github.com/aerogear/graphback/pull/2151

**Comment by Odin94** [comment]
Update:

Using NodeJS 12 and yarn fixed it

**Comment by craicoverflow** [comment]
Thanks for the fix @Odin94! We recommend using `yarn` as we use yarn workspaces which hoists all dependencies into the root `node_modules`. However we should still allow `npm` users to work with the project and so having jest as a dependency here is great. Massive thank you for this!
