### ISSUE TITLE
Getting error while running server. 

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/graphback#216]
### Description

I tried to run the project (server) using the following steps.
- graphback generate
- graphback db
And then `npm start` command to be followed after this.

While running `graphback db` command I got this error: `password authentication failed for user "name"`. How to resolve this?

**Comment by wtrocki** [comment]
problem is our config.json require config. 
We require file that is outside typescript source path.
Compiling source code to dist will still work but running npm run start without
compilation is causing config to be empty.

I could not replicate that on my machine and debug it but I think we might need to improve the way we use config in templates or force compile when template is created. @Lavanyagaur22 Thank you for logging issue

**Comment by wtrocki** [comment]
Workaround now is to use `graphback watch` or simply `npm run build` before `npm run start`

**Comment by ankitjena** [comment]
> Workaround now is to use graphback watch or simply npm run build before npm run start

@Lavanyagaur22 did this work for you?

**Comment by Lavanyagaur22** [comment]
> > Workaround now is to use graphback watch or simply npm run build before npm run start
> 
> @Lavanyagaur22 did this work for you?

@ankitjena Yep 👍

**Comment by ankitjena** [comment]
addressed it in #249
