### ISSUE TITLE
Relationships are not synced for the datasync (Offix Datastore relies on them to get data)

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#2163]
ObjectDelta missing relationship fields.

**Comment by machi1990** [comment]
/cc @ssd71
/cc @craicoverflow, @machi1990
Automatically generated comment to notify maintainers

**Comment by wtrocki** [comment]
FYI @kingsleyzissou - I need to fix that first to get over the required data in order to filter it.

**Comment by craicoverflow** [comment]
This is down as a `bug` - but this was intended behaviour and a known limitation until now. Should it be a `feat`?

**Comment by wtrocki** [comment]
Delta should contain exactly the state of the database. I see it as bug but not problem to make it feature :D

**Comment by craicoverflow** [comment]
That's fine, let us keep it as a bug.

**Comment by craicoverflow** [comment]
Docs will also need to be updated to include relationships in delta object.

**Comment by RinkiyaKeDad** [comment]
Hey could I work on this issue? Can you please provide some more details about what needs to be done?

**Comment by wtrocki** [comment]
I think @kingsleyzissou worked on this issue and we could technically close it due to solution available outside graphback. @kingsleyzissou Please close if you are happy with this

**Comment by kingsleyzissou** [comment]
Yep, I'll close this issue
