### ISSUE TITLE
[MDEP001] DeprecationWarning: "MongoMemoryReplSet.getConnectionString" is deprecated, use ".getUri"

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2172]
We should use `.getUri` instead of `.getConnectionString` where https://github.com/nodkz/mongodb-memory-server is used.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by craicoverflow** [comment]
Hi @Muditxofficial yes that looks to be the case. You will need to research the relevant documentation at https://github.com/nodkz/mongodb-memory-server to find out what it does.
