### ISSUE TITLE
OneToMany vs OneToOne (Docs)

### ISSUE THREAD

**Issue by kingsleyzissou** [aerogear/graphback#2181]
I'm not entirely sure if this is a bug or possibly something that might need to be clarified in the docs.

Given this example here from the [docs](https://graphback.dev/docs/model/annotations#onetomany) a `oneToMany` annotation will create a field on the type, so:
```
"""model"""
type User {
  id: ID!
  """@oneToMany(field: 'author')"""
  posts: [Post]!
}

"""@model"""
type Post {
  id:ID!
  text: String!
}
```

Will generate the following:

```
"""@model"""
type Post {
  id: ID!
  text: String!
  author: User
}
```
When I inspect the schema on the server that all checks out.

The docs say something similar about the `oneToOne` relationship, but inspecting the schema on the server,
I find that it is creating the field on the type that has the annotation, so the following:

```
"""
@model
"""
type Note {
  _id: GraphbackObjectID!
  title: String!
  description: String!
  """
  @oneToOne(field: 'note')
  """
  comment: Comment!
}

"""
@model
"""
type Comment {
  _id: GraphbackObjectID!
  title: String!
  description: String!
}
```

And the result on the server is this:

```
type Note {
  _id: GraphbackObjectID!
  title: String!
  description: String!
  comment: Comment!
  _lastUpdatedAt: GraphbackTimestamp
  _version: Int
}

type Comment {
  _id: GraphbackObjectID!
  title: String!
  description: String!
  _lastUpdatedAt: GraphbackTimestamp
  _version: Int
}
```

Is there an undocumented change I am missing, or am I making a mistake with my annotations?

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by kingsleyzissou** [comment]
I noticed the same applies when I am trying to generate schema for the `oneToOne` relationships in the Offix cli. The field is generated for the type that has the annotation, is this expected behaviour.

The PR is (I haven't pushed the changes yet):
https://github.com/aerogear/offix/pull/899

**Comment by craicoverflow** [comment]
Thank you for pointing this out. The `@oneToOne` annotation does not have a `field` argument..these docs are wrong. Eventually it will have, if we add bidrectional query capacity on a 1:1 (see https://github.com/aerogear/graphback/issues/930).

I will remove this from the documentation.
