### ISSUE TITLE
Add pattern to .gitignore file to ignore all `*.sqlite` files

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2186]
**Is your feature request related to a problem? Please describe.**

SQLite files should never be committed, but it can happen by accident.

**Describe the solution you'd like**

We can ignore all `*.sqlite` files in the `.gitignore`. This is the most common naming pattern for these files so it should cover >90% cases.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by saiprasadnayak6858** [comment]
I would like to work on it and contribute to solve it , please can you describe the issue more precisely?

**Comment by craicoverflow** [comment]
Great! I have given all the information required to complete this task, you will need to do research how to do this.

**Comment by saiprasadnayak6858** [comment]
Are the files already in the repo i.e they are versioned?

**Comment by craicoverflow** [comment]
Nope, but we want to prevent this from ever happening.

**Comment by saiprasadnayak6858** [comment]
I think adding `*.sqlite` into the git ignore file will do the job

**Comment by craicoverflow** [comment]
If you push a PR we can review its validity from there. Thank you! :star:

**Comment by saiprasadnayak6858** [comment]
Shall I add `*.sqlite` to only the global git ignore file or all the git ignore files present in the repo?

**Comment by craicoverflow** [comment]
You can just add it to the root gitignore file, but make sure that it covers all folders too with a glob pattern.
