### ISSUE TITLE
Enable auto-merge for renovate (for pathc and minor dependency updates)

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#2194]
**Is your feature request related to a problem? Please describe.**

I think we should enable auto-merge on minor and patch updates. We disabled this ahead of 1.0 but since this is passed it is good to keep up to date (for security reasons more than anything).

Updates are managed with [renovate](https://github.com/renovatebot/renovate)

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @machi1990, @wtrocki

**Comment by rajivrtk11** [comment]
hi, i would like to work on this issue, can you you suggest me the way to get started

**Comment by craicoverflow** [comment]
Hi @rajivrtk11 - thanks! The best thing to do is to look at the CONTRIBUTING.md file. The issue describes what is required.
