### ISSUE TITLE
Generated GraphQL schema doesn't allow arrays into update mutation

### ISSUE THREAD

**Issue by PixelYeti** [aerogear/graphback#2203]
* **Module**: graphback-core
* **Version**: 1.0.1
* **Node.js / npm versions:** Node:v15.0.1 NPM:6.14.8
* Example/snippet of the model that is causing issue

Schema
```graphql
type Volunteer {
    _id: GraphbackObjectID!
    name: String!
    email: String
    preferredDays: [DaysOfWeek]
    skills:[String]
}

enum {
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY,
    SUNDAY
}
```

Generated Mutation
```graphql
type Mutation {
    updateVolunteer(input: MutateVolunteerInput!): Volunteer
}

input MutateVolunteerInput {
  _id: GraphbackObjectID!
  name: String
  email: String
  preferredDays: DaysOfWeek
  skills: String
}

....
```

What I was expecting this to generate is:

Expected Mutation
```graphql
type Mutation {
    updateVolunteer(input: MutateVolunteerInput!): Volunteer
}

input MutateVolunteerInput {
  _id: GraphbackObjectID!
  name: String
  email: String
  preferredDays: [DaysOfWeek]
  skills: [String]
}

....
```

I would expect the skills field in MutateVolunteerInput to be an array of Strings. At the moment I can create a Volunteer with an array of skills, however once I update with the above mutation all queries fail since it cannot convert a string back to an array of strings.

If you need anymore info let me know

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by wtrocki** [comment]
Thank you for logging issue. This is due to no representation for array in graphback - array is relationship to type so if we do not have it as relation things could be tricky. Looks like simple fix.

@craicoverflow I think we had some workaround for this right?

**Comment by craicoverflow** [comment]
This is a small bug. I've put out a fix in #2205.

**Comment by PixelYeti** [comment]
Ah brilliant! Have you guys got a plan to do a release to NPM anytime soon?

**Comment by craicoverflow** [comment]
We have releases 1.1.0 - please try it out :smile: 

https://github.com/aerogear/graphback/releases/tag/1.1.0
