### ISSUE TITLE
Headstart

### ISSUE THREAD

**Issue by mukeshgupta7** [aerogear/graphback#2211]
Hello can someone share the good first issues, for getting started, it would be very helpful.

**Comment by machi1990** [comment]
Automatically generated comment to notify maintainers
/cc @craicoverflow, @machi1990, @wtrocki

**Comment by craicoverflow** [comment]
Hi! We don't have any good first issues right now, we had some great contributions in Hacktoberfest which cleared them all up! But if you find things you think could be improved, feel free to create an issue for it and start working on it.

https://github.com/aerogear/graphback/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3A%22good+first+issue%22+is%3Aopen

**Comment by wtrocki** [comment]
Some community members asking for Nest.js template. We do not have much experience with it so having nest.js template will be appreciated
