### ISSUE TITLE
Error while fetching data on playground. 

### ISSUE THREAD

**Issue by Lavanyagaur22** [aerogear/graphback#222]
### Description
While creating a task using mutation:

```graphql
mutation {
    createTask(input: {
    title: "Task 1",
    description: "Hello 1",
    status: "Open"   
  }){
 version
  id
  } 
}  
```

I got the following error: (although the mutation works well and the task is created)

```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Task.id.",
 ...
```

Why is it returning this instead of returning the id? Also, if I ask to return version only it works well because it is a nullable type of field in the schema whereas all the other fields are of non-nullable type.

Also, upon running queries and mutations on the playground, I am getting this:

<img width="725" alt="Screenshot 2019-08-12 at 12 25 58 PM" src="https://user-images.githubusercontent.com/33238323/62855099-ede65d80-bd0e-11e9-868a-8d2c256d13c6.png">

Why is it not returning the data?

**Comment by wtrocki** [comment]
Problem was related to local changes made after generation
