### ISSUE TITLE
'apollo-fullstack-react-mongo-ts' template breaks when a Comment is created

### ISSUE THREAD

**Issue by namit-chandwani** [aerogear/graphback#2239]
* **Module**: ts-apollo-mongodb-backend
* **Version**:
* **Node.js / npm versions:**
* Example/snippet of the model that is causing issue: https://github.com/aerogear/graphback/blob/2d3e304fbe675536d3e39494d6a91b4d74aceb74/templates/ts-apollo-mongodb-backend/model/datamodel.graphql#L17

# Steps to reproduce the issue:

![graphback issue](https://user-images.githubusercontent.com/51479159/102141242-84d4a400-3e86-11eb-821a-ae8a7f138896.gif)

**Error received:**
```python
0: "GraphQLError: Variable "$input" got invalid value { text: "test", description: "xyz", noteId: "5fd7dacb0a9dce610bb081ab" }; Field "roles" of required type "[String!]!" was not provided."

```
# Description of the issue:

The data model of the 'ts-apollo-mongodb-backend' template contains a Comment model with 3 non-primary key fields (text, description, roles) whereas in the client template (ts-react-apollo-client) only the values of 'text' and 'description' are captured through the form and there's no input element for the 'roles' field.

Secondly, on searching the generated query on the client side I found that the 'CreateCommentMutation' mutation accepts these fields as the input:
https://github.com/aerogear/graphback/blob/2d3e304fbe675536d3e39494d6a91b4d74aceb74/templates/ts-react-apollo-client/src/generated-types.tsx#L53-L58

...which shows that the default client schema is not up-to-date with the project data model (declared in the backend template), as it does not include the 'roles' field.
As a result, I regenerated the client schema using ```yarn generate```, which updated 'CreateCommentInput' to include the roles field as well.
Now while running the client using ```yarn start```, I received the following error:
```python
Property 'roles' is missing in type '{ text: string; description: string; noteId: string; }' but required in type 'CreateCommentInput'.  TS2741

    34 |                     <Button variant="outlined" color="primary"
    35 |                         onClick={() => {
  > 36 |                             createComment({ variables: { input: { text: newCommentTitle, description: newCommentDescription, noteId: noteId } } });
       |                                                          ^
    37 |                             addCommentState(false);
    38 |                         }}>Add Comment</Button>
    39 |                 </form>

```
...which can be fixed by adding an additional input element to capture the value of the 'roles' field and send it as an input to the mutation, just as I mentioned earlier.

# Possible Solutions:
* **Remove the 'roles' field from the data model of the 'ts-apollo-mongodb-backend' module**:
This simple change will fix all of the above errors without the need for any changes in the client template.

* **Make changes in the 'ts-react-apollo-client' to accept the 'roles' field as an additional input:**
This will fix the errors mentioned above, but since the other backend templates (which are dependent on the client template for full-stack projects) like 'ts-apollo-postgres-backend' do not have the 'roles' field defined in the Comment model of their data model, it will result in errors while using a different template. So in order to fix this issue completely, the data models of all backend templates would also need to be changed by adding an additional 'roles' file in the Comment model.

Can any of the maintainers please let me know that which of the 2 solutions mentioned above would be the most preferred one?
I'd be happy to start working on fixing this issue as soon as I get to know about your views on this.

**Comment by namit-chandwani** [comment]
@wtrocki @craicoverflow
Can I please start working on this issue with any of the solutions that I have mentioned above?

**Comment by craicoverflow** [comment]
Sorry, I fixed this but comment on the PR instead of this issue! https://github.com/aerogear/graphback/pull/2240#issuecomment-745128937

By the way, you do not need to ask to work on an issue like this.

**Comment by namit-chandwani** [comment]
Yeah, but I wanted to know which one of the solutions (mentioned above) would you all prefer the most, that is why I waited before sending a PR.

No problem, the issue is now fixed and that's what matters! 😊
