### ISSUE TITLE
Graphback watch does not return errors

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#230]
Graphback watch currently doesn't return any error on running the server, instead it doesn't show any output.

**Comment by ankitjena** [comment]
@wtrocki I was thinking of improving `watch` command to also watch for server changes, and only restart the server, and in case of changes in model do all three steps. Otherwise `watch` becomes limited in use.

**Comment by wtrocki** [comment]
Good idea. Lets leave it out of the current scope for now

**Comment by ankitjena** [comment]
So currently after doing `npm run start` we do not actually stop the process on changes, and run `npm start` again, but as error was not handled so didn't know about this. On change we should kill the existing subprocess first.

**Comment by wtrocki** [comment]
@ankitjena Workaround exists.

```
graphback generate
graphback db
npm run build
npm run start
```

 We might stop recommending watch in tutorials we build and resolve this issue in next release. Dropping to next release, however, this will need to wait till next week.


FYI @MStokluska @darahayes
