### ISSUE TITLE
Custom resolver "create" method types

### ISSUE THREAD

**Issue by itsemirhanengin** [aerogear/graphback#2300]
Hello! I'm trying to write a custom resolver for a reason. But when I try to use create method, I get this type error.
![image](https://user-images.githubusercontent.com/21215832/130300260-0908dad8-a6cd-43f5-bd17-7230749d2eee.png)

But when I ignore the error with // @ts-ignore I get no error and it works.
How can I make this without ignore the errors?

Thanks!

**Comment by CoreyKovalik** [comment]
You are running into an issue we have been running into as well. This is because of how the crud service is typing the create method. Here's the solve I've been doing.

```typescript

import { CreateUserInput, User } from "your-generated-types.ts";

// TypeScript will protect you here. careful not to use `as CreateUserInput`
const createPayload: CreateUserInput = {
    fullname: 'John Doe',
    email: 'email@domain.com',
    password: '12345',
    phone: '555-1234',
};

// you're casting "User" and basically telling TypeScript it's OK.
// this typically would be unsafe, but because you're typing it above, this should be acceptable :)
const user = await context.graphback.User.create(<User>createPayload);
```

**Comment by itsemirhanengin** [comment]
Thank you so much @CoreyKovalik! I've just tried it and It works great.

**Comment by itsemirhanengin** [comment]
![image](https://user-images.githubusercontent.com/21215832/130332292-4a4595bc-eadf-4024-a307-a6bc32294c80.png)
@CoreyKovalik  I don't know why but VS code started to give me this error...
