### ISSUE TITLE
It should not be required to install Graphback globally

### ISSUE THREAD

**Issue by darahayes** [aerogear/graphback#253]
Hey so this is a non critical issue right now but it is a generally accepted idea that installing things globally is bad. 

I would like to see a world where I don't need to globally install `graphback` in order to create an application and then manage the local development lifecycle.

## Summary

* The documentation should recommend using `npx` for `graphback init`
* commands like `graphback watch`, `graphback db` and `graphback generate` should be run from npm scripts. e.g. `npm run watch`, `npm run generate`.

These two suggestions together would mean I never have graphback installed globally and it will allow for working on multiple projects created and managed by different versions of graphback where those commands might behave slightly differently.

## Background

* Lots of developers (like me) do not like to install unnecessary things on our machines.
* If I use Graphback today to create some project, then 6 months later I want to create a new project, I need to make sure I have the latest version.
* If I work on two different graphback projects that were created at different times, I run the risk of commands like `graphback generate`, `graphback db` and `graphback watch` not working as expected because of version mismatches.
* npm themselves recommend not installing things globally https://docs.npmjs.com/downloading-and-installing-packages-globally

I see some potential solutions for this that will not require any major refactoring.

## graphback init

`npx` should be the recommended tool for `graphback init`

```
npx graphback-cli init myapp
```

This is a pretty common thing to see. example: create-react-app https://github.com/facebook/create-react-app#quick-overview

# watch, db, generate

My understanding is that the purpose of these commands is to manage the local development lifecycle of my project and that they are not intended for production. To me that means these commands are specific to a given project and should not be run globally.

I think the graphback-cli should be included as a dev dependency of the project and these commands should be run as local npm scripts, e.g. `npm run generate`, `npm run watch`, `npm run db`

**Comment by wtrocki** [comment]
Fully agree.

**Comment by wtrocki** [comment]
I think we need to:

- Remove init command as part of this PR
- Create new create-graphback-app package that will be used for npm init and has the same functionalities as init. 
- Document adding graphback to existing templates in docs

This way we going to provide great getting started while not confusing people about role of the init command
 
WDYT?

**Comment by ankitjena** [comment]
I will take this up

**Comment by wtrocki** [comment]
I think I will close it.. Because this is possible now. You can simply install it locally and add config. 
We have this documented as well. We going to restructure packages anyway in upcoming refactor
