### ISSUE TITLE
Cannot query findAll method for graphql-js template

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#278]
`"message": "Cannot read property 'select' of undefined",`

**Comment by wtrocki** [comment]
This is due to the wrong resolver format. Apollo pass different resolvers than graphql JS

**Comment by wtrocki** [comment]
Side note. I have disabled template for the moment as hacking things around to make it work might not have sense. We need a different generator for different types of resolvers.

**Comment by ankitjena** [comment]
Closing this as we removed the template
