### ISSUE TITLE
It should be possible to choose the directory when generating a new project

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#287]
The CLI should allow the user to provide a directory where they would like the project installed.

**Examples**

* `graphback init hello-world .` creates the project in the current directory.
* `graphback init hello-world ~/code/src/github.com/craicoverflow` creates the project in a specific directory.

**Comment by ankitjena** [comment]
@craicoverflow  Using `.` at the end seems like something people will miss or forget. How about having a argument like `--directory` or something else?

**Comment by wtrocki** [comment]
Less flags then better. Flags should implement features that are not possible to be done otherwise. In thiscase:

`cd dir && graphback init` would work same as git command etc.

**Comment by wtrocki** [comment]
We need to have plan about generator including custom model folder as wel as generation folders. 
Creating separate isseu to talk about this.
