### ISSUE TITLE
Graphback support for GraphQL enums types

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#288]

**Comment by ankitjena** [comment]
We have to handle enum definitions in Resolvers too.

**Comment by wtrocki** [comment]
Yes!

**Comment by wtrocki** [comment]
@craicoverflow Let's cover this topic in migration.
If we can say that we support enums then we will need to create representation in db for them.
If not we simply need validator that will check if enums are there

**Comment by wtrocki** [comment]
Closing as we not going to support enums in input models.
