### ISSUE TITLE
All input output folders should be configurable

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#294]
Currently graphback expects model to be in some hardcoded locations and outputs to some specific folders as well. This can lead to many problems and wrong assumptions. 
All folders should be configurable in separate part of the configuration file. 

## Spec
Currently available folders:

Input folders: 
- model

Output folders:
- resolvers
- schema

Additional we should provide documentation for all input and outputs of the generation process - including configuration so that it will be clear how things work and how to build an template.

**Comment by wtrocki** [comment]
1. Let's post here format of the config we want to build
2. Let's agree on this
3. Let's use `.graphback` as file name
4. We should generate default config as it is now. 
5. We should utilize config everywhere
6. We need release notes - breaking change

**Comment by MStokluska** [comment]
@wtrocki @ankitjena 

```
{
  "dbConfig": {
    "user": "postgresql",
    "password": "postgres",
    "database": "users",
    "host": "127.0.0.1",
    "port": 55432
  },
  "generation": {
    "create": true,
    "update": true,
    "findAll": true,
    "find": true,
    "delete": false,
    "subCreate": false,
    "subUpdate": false,
    "subDelete": false,
    "disableGen": false
  },
  "database": "pg"
}, 
"routes": {
"model": './dev/myOwnGraphQLModel/model'
"resolvers": './dev/graphbackProject/src/resolvers/'
"schema": './dev/graphbackProject/src/schema/
}
```

For now, my initial understanding of an issue leads to something like above. Where after initialization we can specify if we would like to use another route for model input, resolvers & schema output.

**Comment by wtrocki** [comment]
Perfect! yes. The way I see it is that after this we will have two commands:
- create (it will create server from template)
- init (it will simply create sample configuration

This will be as separate issue so let's not bother about this. 

I would move all items into some root element like `layout: {` or something similar.
