### ISSUE TITLE
Schema generation process should base on `printSchema`

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#298]
`printSchema` from graphql-js allows to print human redable schema from schema object. 
Generating schema this way will allow us to support many different types out of the box - if schema contains enum - we do not need to handle it anymore. 

The way it could work is:
1) Users give us input schema
2) Schema then is being parsed into Graphql AST objects
3) We use visitor to collect some data in order to build resolvers. 
4) We add extra types and operations directly to the schema
5) We print schema instead of generating it from strings.

**Comment by wtrocki** [comment]
FYI @ankitjena

**Comment by ankitjena** [comment]
+1000 for this. Seems like a great idea. I will try this out.

**Comment by wtrocki** [comment]
Let's put that on hold

**Comment by wtrocki** [comment]
https://graphql.org/graphql-js/constructing-types/

**Comment by wtrocki** [comment]
Done quick investigation and I think we can do some creature like this:

1) For each individual GraphQL file we will build AST without query 
(so long so good but it will fail validation if query is missing)

2) Build query, mutation, subscriptions using object definitions

3) Use join ast to join both source and additional methods we added
https://github.com/graphql/graphql-js/blob/master/src/utilities/concatAST.js

4) Use print schema.

**Comment by wtrocki** [comment]
Drawback of using print schema is that we going to loose order of the elements defined in model. 
Printschema will simply sort them: 
https://github.com/graphql/graphql-js/blob/a5bbe713f4b704247d56616e522f3d855354b974/src/utilities/schemaPrinter.js#L90-L92

**Comment by wtrocki** [comment]
Reopened as I got some idea from community to explore https://github.com/sibelius/graphql2ts

**Comment by wtrocki** [comment]
So using this library we can get schema in the typescript format... however... We still need to have full schema generated for it. I do think that human redable schema that is generated is best for review and having it gives bigger benefit. Done spike to check if we can add elements on top and this can be done easily but our target is maintainability. I think generated source code that is quite complex to read goes against it.
