### ISSUE TITLE
CLI instructions

### ISSUE THREAD

**Issue by MStokluska** [aerogear/graphback#307]
## Summary

I think we should rethink how Graphback instructions are displayed as currently, we are repeating steps unnecessarily. 

## Issue

The first set of instructions are displayed after `init`
```sh
graphback init <name>
```
Which produces following output:
![image](https://user-images.githubusercontent.com/43473912/64266771-17b92b80-cf2d-11e9-8e0d-fe274d9a2385.png)

Another set of instructions are displayed `generate`
```sh
graphback generate
```
![image](https://user-images.githubusercontent.com/43473912/64266899-50f19b80-cf2d-11e9-84cd-0e07afa379f6.png)

I don't think there's any need for the second set of instructions and that step 4. could have been separated into 2 individual steps.

ping @wtrocki @darahayes @craicoverflow @ankitjena

**Comment by wtrocki** [comment]
For init we should only print step:

1,2,3

For generate we should only print 

1.

For db we should print 

2.

**Comment by ankitjena** [comment]
@wtrocki agree with this
