### ISSUE TITLE
Add unit tests for Schema/Resolver generation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#311]
General idea is to build unit tests for schema resolver generation by inspecting output from visitor. We can also use validate function for resolver output. Compile it and see if schema has required fields etc.

**Comment by wtrocki** [comment]
CC @craicoverflow let's chat here how we see this done

**Comment by wtrocki** [comment]
I think we might simply need to start with simple test using some advanced schema like here: https://github.com/Shopify/graphql-design-tutorial/blob/master/TUTORIAL.md

Then we can extend it over time once development moves.

**Comment by craicoverflow** [comment]
The [`validate`](https://graphql.org/graphql-js/validation/) function accepts type [GraphQLSchema](https://graphql.org/graphql-js/type/#graphqlschema) - something which we do not seem to use anywhere.

Do you think Graphback should be refactored a little bit to try and use this?

This will require a little bit of investigation to see how it works now/how it could work.

**Comment by wtrocki** [comment]
Deifnietly graphback needs to be refactored as we operate on strings that are very hard to deal with. See also https://github.com/aerogear/graphback/issues/298

To get GraphQLSchema from string we can simply do `buildASTSchema(parse(`type...`))` but. 

we can simply do parsc

**Comment by wtrocki** [comment]
on hold for new architecture
