### ISSUE TITLE
[Idea] Introduce graphback config command 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#316]
`graphback config` will ask for the same question as init but this time it will not download template - users can execute template in current template root.

**Comment by MStokluska** [comment]
@wtrocki 
could this be a possible part of issue #294 ? 
Sorry, I'm probably missing something but not sure where would like to see the difference exactly between template and sample configuration.

**Comment by wtrocki** [comment]
Definitely not. This will be separate focus

**Comment by wtrocki** [comment]
Updated details!

**Comment by wtrocki** [comment]
Done
