### ISSUE TITLE
Database migration tools for graphback

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#318]
## Summary
We can separate concerns of handling database by using preexisting database tools which will handle database migration. 

## TODO
List out database tools we can employ to our usecase

**Comment by wtrocki** [comment]
After investigation I think we need prototype for Postgres and MySQL based migrations using knex

**Comment by wtrocki** [comment]
Requirements:

- Support SQL migration (in form of README.md file) 
- Support direct database migration for dev
- React-based on environment abstraction 
- React-based on generated database mapping file.

**Comment by wtrocki** [comment]
We going to build our own migration tooling basing on GraphQL https://github.com/aerogear/graphql-relx/issues/3

**Comment by wtrocki** [comment]
Reopening as we trying to apply some minimal changes inside graphback first before adding things to relix

**Comment by wtrocki** [comment]
@craicoverflow Closing as we decided to use our own implementation. There is no reliable migration tool for the moment in js community that will work nicely with graphql.
