### ISSUE TITLE
[5min] Prettier and TSLint out of the box

### ISSUE THREAD

**Issue by b1zzu** [aerogear/graphback#323]
If there is something I really love when developing is keeping the code clean (Prettier) and enforce best practice (TSLint) and they both works cross-editor (WebStorm, VS Code, ...), are fully integrated with the editors, and they can both verified with one single command `npm run lint` (if correctly configured).

https://prettier.io/docs/en/integrating-with-linters.html#tslint

--------------------

EDIT from @wtrocki 

We need to add support prettier or anything else into our template. 
See `/templates` folder for the sample projects that should have it. 

Additionally we could also provide some documentation for this.

**Comment by wtrocki** [comment]
I think this can be done by our template using eslint formatter after generation as example and docs. Making formatter inside makes no sense as it can be simply called after generation.

**Comment by b1zzu** [comment]
Another solution could be to define a post generate script, and then the user can define prettier or any  other linter, or formatter to run after `graphback generate`

**Comment by wtrocki** [comment]
Outdated as we moving out of the idea of the template and going to have only a single opinionated example base application for different workflows.

**Comment by wtrocki** [comment]
https://github.com/aerogear/graphback/issues/422 for reference
