### ISSUE TITLE
Database fields are not being created for interfaces

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#326]
Adding interface to my datamodel, and running `graphback generate` includes the interface in the generated schema. But database fields of the interface are not being created in the types on running `graphback db`. We should be creating database fields and #297 had the work for creating them. @craicoverflow

**Comment by craicoverflow** [comment]
Hi @ankitjena. I have been unable to reproduce this bug. Could you show your GraphQL schema?

Could it be that you are not actually providing the field to your type? You must still include the field in your type, it does not automatically inherit from an implemented interface.

What happens when you run `npm run develop`?

**Comment by wtrocki** [comment]
I have found issue about graphback - build process overrides permissions so everytime we build we loosing global npm link and we executing globally available command. 
This leads to many things simply not working when breaking changes were introduced. 
This can be case here.

**Comment by ankitjena** [comment]
> Could it be that you are not actually providing the field to your type? You must still include the field in your type, it does not automatically inherit from an implemented interface.

Oh my bad then, I wasn't including the field again in the type thinking that it was handled. Don't you think that creates redundancy?

**Comment by ankitjena** [comment]
> I have found issue about graphback - build process overrides permissions so everytime we build we loosing global npm link and we executing globally available command.
> This leads to many things simply not working when breaking changes were introduced.
> This can be case here.

Not the case here. I saw the bug so edited my scripts a bit in local machine.

**Comment by craicoverflow** [comment]
> Oh my bad then, I wasn't including the field again in the type thinking that it was handled. Don't you think that creates redundancy?

From the [GraphQL specification](https://graphql.github.io/graphql-spec/June2018/#sec-Interfaces):

> GraphQL interfaces represent a list of named fields and their arguments. GraphQL objects can then implement these interfaces which requires that the object type will define all fields defined by those interfaces.

This implies that the input schema would be invalid if a type does not provide a required interface field.

My original plan was to generate these automatically, but I changed it as this would be a bit misleading as the input schema should be valid.

> Don't you think that creates redundancy?

A little bit, but that is how interfaces should work. [Object extensions](https://graphql.github.io/graphql-spec/June2018/#sec-Object-Extensions) would would be more suitable if a developers wishes for their fields to automatically inherit (though I don't believe we have this yet).

**Comment by ankitjena** [comment]
> From the [GraphQL specification](https://graphql.github.io/graphql-spec/June2018/#sec-Interfaces):
> 
> > GraphQL interfaces represent a list of named fields and their arguments. GraphQL objects can then implement these interfaces which requires that the object type will define all fields defined by those interfaces.
> 
> This implies that the input schema would be invalid if a type does not provide a required interface field.
> 
> My original plan was to generate these automatically, but I changed it as this would be a bit misleading as the input schema should be valid.

Okay got it. Thanks for clearing that out.
