### ISSUE TITLE
Investigate having runtime without code generation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#333]
Investigate ways of having runtime without physical source code being generated where output can be just executable graphql schema with resolvers.

**Comment by wtrocki** [comment]
@b1zzu Adding yourself as assigne to provide updates after your findings done in testx project.

**Comment by b1zzu** [comment]
@wtrocki would take some time

**Comment by wtrocki** [comment]
I'm happy to collaborate on this and there is no pressure. Runtime is not main focus of the graphback at the moment.

**Comment by wtrocki** [comment]
After chat we decided that we not going to follow this lead for the moment.
