### ISSUE TITLE
Graphback Architecture

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#336]
Graphql Code generator with state providers can be used here.

**Comment by craicoverflow** [comment]
## 1. User input

- User provides GraphQL input schema.
- User provides custom template configuration options.

## 2. Process GraphQL Schema

- Graphback will process the schema and create queries, mutations etc.
- The old schema will be compared to the new schema to find changes.

## 3. Perform database schema migrations.

- Database schema adjustments are made based on changes to the schema.

## 4. Create back-end

- Graphback will the create runtime resolvers, which will be in-memory and will not be written to any file.
- There is a generic data access layer which will be called from resolvers to make CRUD operations.
- The back-end is created and the application is run.

![Graphback Architecture(2)](https://user-images.githubusercontent.com/11743717/66379324-1f954100-e9ad-11e9-8bec-e29c10acff6d.png)

**Comment by wtrocki** [comment]
FYI @ankitjena @darahayes @MStokluska

**Comment by wtrocki** [comment]
Outstanding work here is to document the new architecture in contribution section. 
We have so much context in individual issues so we can dump that into our docs.
