### ISSUE TITLE
InputType in model  is causing db generation to fail

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#338]
Having input type in Model causing generation to fail. 
We need to have additional case added to the visitor to ignore input types

```
create table "task" ("id" serial primary key, "completed" boolean, "description" varchar(255), "id" varchar(255), "name" varchar(255), "created_at" timestamptz, "updated_at" timestamptz) - column "id" specified more than once

```

**Comment by craicoverflow** [comment]
I believe the error you are saying is nothing to do with having an input type in the model.

Take the following input schema example:

```gql
type Note {
    id: ID
    title: String
    text: String
}

input NoteInputTwo {
  title: String
}
```

This will not fail - the custom input will not be transferred into the output schema, but I can successfully run the application.

What you are seeing occurs when a model contains an id with type other than ID.

You can reproduce this error by changing the id type:

```gql
type Note {
    id: Int
    title: String
    text: String
}

input NoteInputTwo {
  title: String
}
```

`graphback db` will give you:

```sh
create table "note" ("id" serial primary key, "id" integer, "title" varchar(255), "text" varchar(255), "created_at" timestamptz, "updated_at" timestamptz) - column "id" specified more than once

```

**Comment by wtrocki** [comment]
Ok.. so we need to require ID! field anyway so the issue is related to the PR I'm working on and going to resolve this there.
