### ISSUE TITLE
Resolvers generation

### ISSUE THREAD

**Issue by MStokluska** [aerogear/graphback#360]
### Issue summary

Currently, if our model contains an entity that has 2 or more attributes of the same type it will generate resolvers as many times as the type has been used. 

### To recreate

- use `graphback init` with shop example model
- navigate to `model/Shop.graphql` and add `owner` field of type `Person!` to the model
- run graphback generate
- navigate to `src/resolvers/generated/person.ts` 

![image](https://user-images.githubusercontent.com/43473912/65525318-38025780-dee7-11e9-97c8-098b474bf108.png)
- run `graphback db` and `npm run develop`, the following error should be produced:

![image](https://user-images.githubusercontent.com/43473912/65525431-67b15f80-dee7-11e9-9631-40e2031cb26d.png)

**Comment by wtrocki** [comment]
I think this feature should not be there as it is strange to have this type of connection as person do not have capabilities to fetch shop.

**Comment by ankitjena** [comment]
Since this is created as part of nested relation, it's just repeated. Keeping one will work for both. So we can check if it's already been added and skip append.

**Comment by wtrocki** [comment]
Which leads to the point that we need object representation of the resolvers first and then map it to the template. This will mean that we can test things nicely without inspecting strings. 

Another problem I see is that I'm not sure if the relation should be there in the first place.
There is no shop relation in any of the types so this cannot be queried.

https://github.com/aerogear/graphback/blob/master/packages/graphback-cli/src/templates/resources/models/Shop.graphql#L1-L17

We are missing product relations for example etc.
