### ISSUE TITLE
Manually publish graphback package on dev tag

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#395]
We have people interested in trying our runtime capabilities but it is hard to use it as we cannot make official release yet. We need to publish graphback package as dev tag in order to give it to testers and first users.

`npm publish --tag=dev`

We should use 0.9.0-dev1 dev2 etc. for every change we doing to master till we move to the state where we will be able to merge all changes

**Comment by craicoverflow** [comment]
Okay - should it be 0.9.2-dev1 etc since the most recent release was 0.9.2?
