### ISSUE TITLE
Client queries and mutations are not generated as expected

### ISSUE THREAD

**Issue by vinifarias** [aerogear/graphback#401]
# Bug Report

**Current behavior:**

The current implementation of methods that generates client queries and mutations are generating code like the followed:

```
export const findItem = gql`
  query findItem(id: ID!, name: String, title: String!) {
    findItem(fields: {id: $id, name: $name, title: $title}) {
      ...ItemFields
    }
  }

  ${ItemFragment}
`
```
The generated code is incorrect because in the second line the symbol **$** is missing before each field name.

**Expected behavior:**

Generation of code like the followed:

```
export const findItem = gql`
  query findItem($id: ID!, $name: String, $title: String!) {
    findItem(fields: {id: $id, name: $name, title: $title}) {
      ...ItemFields
    }
  }

  ${ItemFragment}
`
```

**Other information**

Probably the error is [here](https://github.com/aerogear/graphback/blob/master/packages/graphback/src/generators/client/targetContext.ts#L9) and [here](https://github.com/aerogear/graphback/blob/master/packages/graphback/src/generators/client/targetContext.ts#L15).
The map function should return something like **`\\$${f.name}...**

**Comment by wtrocki** [comment]
Thank you for reporting this issue. Our team is going to fix it as soon as possible. We are also welcome contributions as this could be quite easy fix.

**Comment by wtrocki** [comment]
See https://github.com/aerogear/graphback/blob/master/packages/graphback/src/generators/client/targetContext.ts
