### ISSUE TITLE
[Idea] Changelog formatted with os strandards

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#415]
It would be really nice if Graphback would have a Changelog file which would be kept in sync with releases and added to release notes.

There are some conventions and templates that we could choose to follow.

- https://keepachangelog.com/en/1.0.0/
- I personally am a big fan of [create-react-app](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md)'s changelog.

**Comment by wtrocki** [comment]
You mean this: https://github.com/aerogear/graphback/blob/master/docs/releases.md? 
Create-react-app is driven mostly by community. I would go with something that requires minimal effort and matches our state. We can recognize external contributors and issue creators etc.
