### ISSUE TITLE
Graphback architecture - package structure checkup

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#426]
# Motivation

We should document and define new package structure and relationships between them. 
Additionally we should rething all interfaces that are exposed and verify the package names.

# Verify package names before release

Verify generator patterns
Check role of the graphback and graphback-cli

# Document breaking changes and integrate with graphql-cli

Document all changes that are needed to integrate with the graphql-cli package.

# Notify users

Notify the existing community about the changes and provide different npm label for previous version.

# Consistent naming convention for input types

We should define and stick to a consistent and clear naming convention for input types. 

Let's take `InputModelTypeContext` as an example. Even though this is a four word name, it is still not clear what its intention is.

Naming suggestions:

- TypeContext
- GraphbackModel
- GraphbackType
- InputModel
- GraphbackInputType
- ModelContext
- Model

What we choose should be applied to all other types also, so `TypeContext`, `FieldContext`, `InterfaceContext` etc.

We can discuss what convention we want to go with here.

**Comment by wtrocki** [comment]
@craicoverflow Added more details by directly editing this issue
