### ISSUE TITLE
Declarative authorization/permissions with custom directives

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#446]
Hi,

I'm coming from the Prisma world. Unfortunately they seem to be moving away from direct GraphQL support in Prisma 2. I also had a number of architectural issues with Prisma's design, and they were never resolved. I ended up writing quite a bit of my own code to try and fix Prisma to work as I wanted. The biggest thing being exposing all queries and mutations to the client with declarative permissions. You can see some of my initial thoughts on this here: https://twitter.com/codenmath/status/1192290679428276225?s=20

I have iterated on the design shown I that article, and in a private deployment I have advanced declarative permissions working rather well. As far as I know there are no other projects that have done declarative permissions to this level, except for maybe AWS' GraphQL project...I forgot the exact name.

Anyway, I hope declarative permissions using custom directives are on the roadmap, and I'd like to offer my insights as I've been designing what in my mind is the best solution for over a year now.

**Comment by wtrocki** [comment]
@lastmjs I twitter link is not correct. There are a couple implementations of declarative permissions using directives. AWSApp sync is one example. AeroGear community has it's own that works with keycloak (opensource OpenID server)

https://github.com/aerogear/keycloak-connect-graphql/

Which can be used in Graphback today. With new architecture, we will add those directives automatically, but it is up to the community to see what authentication/authorization solution is being used under the hood - For example acccount.js/passport.js etc. 

So short answer - authentication and authorization is on the roadmap and I would love to get more insights on how the community will like to have it done. However, thanks to modular architecture authorization can be added today to any graphql-cli or graphback templates.

**Comment by wtrocki** [comment]
We going to provide this as separate package: https://github.com/aerogear/datasync
