### ISSUE TITLE
ask for example model file in init flow

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#45]
## Implementation
- Ask user if include model or not
- if yes ask for set of example models present in cmd or github
- bootstrap with example model in init

**Comment by ankitjena** [comment]
@wtrocki Should we create custom model too taking input from user, just the filename, user will enter the details later on.

**Comment by wtrocki** [comment]
I think input from user makes this command go for long. Usually you would probably be better to have project as fast as possible and then edit stuff in your fav ide. If someone says no we should be creating empty file maybe or file with example that is commented out will be even bette4
