### ISSUE TITLE
Create items require id

### ISSUE THREAD

**Issue by vinifarias** [aerogear/graphback#474]
### Bug Report

In Graphback version `0.9.6` the client-side _create_ mutation is generated like the example:

```javascript
export const createItem = gql`
  mutation createItem($id: ID!, $name: String, $title: String!) {
    createItem(input: {name: $name, title: $title}) {
      ...ItemFields
    }
  }
  ${ItemFragment}
`
```
The problem is **$id: ID!**, in the second line. When you try to use the operation, it throws an error like:

![image](https://user-images.githubusercontent.com/15389384/68945160-78b37a00-078e-11ea-9689-8a93a3ca3f73.png)

**Comment by wtrocki** [comment]
Awesome catch. Workaround would simply pass id for the moment. Going to remove it inthe next release
