### ISSUE TITLE
Database migrations from CLI

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#477]
## What

Migrations don't work well with CLI. `graphback db` drop-creates the database but does not add a migration entry. Then `graphback update-db` tries to update the database but assumes there is not schema structure in place as the schema_migrations table is empty.

## Solutions

1. Apply migration logic when running `graphback db`.
2. Inspect database schema to see what tables exist and map these to `changes.json` which can be saved to the migrations table.

**Comment by wtrocki** [comment]
Addressed by @craicoverflow
