### ISSUE TITLE
Graphql file not found on windows

### ISSUE THREAD

**Issue by TomBrouwer** [aerogear/graphback#499]
I've generated a graphback project with init. I want to generate with `graphback generate` but it looks like it try to use the full path as a relative path (see slash begore C:/:

`Error: ENOENT: no such file or directory, open '/C:/Users/*** ***/Priv/firstgraph/model/Note.graphql'`

I'm running Node v12.13.0, and run `graphback generate` in powershell

**Comment by wtrocki** [comment]
@TomBrouwer Thank you for reporting this issue. This looks like our way of using nodejs path is not windows friendly. 

As workaround feel free to try graphql-cli init command that includes graphback. 
We are also releasing new version soon. Stay tuned

**Comment by wtrocki** [comment]
Thank you for reporting issue. We are in the process of moving our cli to graphql-cli tooling that supports windows. We can get the same features in graphql-cli as in graphback (as it is used under the hood)
