### ISSUE TITLE
Using `sqlite` as default database in runtime example

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#504]
Swap PostgreSQL for SQLite as the default database provider in the runtime-example.

## Why

As an example app, it should be quick and easy to run. Requiring Postgres to run it is overkill. This will also simplify tests.

**Comment by wtrocki** [comment]
No longer valid

**Comment by pwright** [comment]
@wtrocki  is sqlite support no longer on the 'roadmap'?

**Comment by wtrocki** [comment]
We always going to support it. This task was only to get our runtime example to use it

**Comment by wtrocki** [comment]
I have reopened those but this issue is blocked by https://github.com/aerogear/graphback/issues/555
