### ISSUE TITLE
The generated create mutation are missing foreigners ids

### ISSUE THREAD

**Issue by b1zzu** [aerogear/graphback#519]
My schema:
```graphql
type Foo {
  id: ID!
  title: String!
  bars: [Bar]!
}

type Bar {
  id: ID!
  description: String!
}
```
and this is the generated mutation for `createBar`
```graphql
mutation createBar($description: String!) {
  createBar(input: {description: $description}) {
    ...BarFields
  }
}

fragment BarFields on Bar {
  id
  description
}
```
and the error when I perform the mutation:
```graphql
[GraphQL error]: Message: Field BarInput.fooId of required type ID! was not provided., Location: [object Object], Path: undefined
[Network error]: ServerError: Response not successful: Received status code 400
```
the correct mutation should be this:
```graphql
mutation createBar($fooId: ID!, $description: String!) {
  createBar(input: {fooId: $fooId, description: $description}) {
    ...BarFields
  }
}
```
Graphback: 0.10.0-rc2

**Comment by b1zzu** [comment]
@wtrocki no it was broken also in the previous version

**Comment by craicoverflow** [comment]
Fixed in https://github.com/aerogear/graphback/pull/609

**Comment by b1zzu** [comment]
@craicoverflow is this fixed int the 0.10.0 or in the 0.10.1?

**Comment by craicoverflow** [comment]
> @craicoverflow is this fixed int the 0.10.0 or in the 0.10.1?

0.10.1 which should be published soon (its failing at the minute):

https://circleci.com/gh/aerogear/graphback/1950?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by b1zzu** [comment]
@craicoverflow testing this out I find that it's working for one to one but not for one to many. I'm reopening it to track it. 

If you are already fixing this but in another issue just close it again

**Comment by craicoverflow** [comment]
> @craicoverflow testing this out I find that it's working for one to one but not for one to many. I'm reopening it to track it.
> 
> If you are already fixing this but in another issue just close it again

Ah yeah this is because you need to explicitly add the field to the type on the M:1 side in order for it to be generated. 

So

```gql
type Foo {
  id: ID!
  title: String!
  bars: [Bar]!
}

type Bar {
  id: ID!
  description: String!
}
```

generates the following schema:

```gql
type Foo {
  id: ID!
  title: String!
  bars: [Bar!]!
}

type Bar {
  id: ID!
  description: String!
}
```

So if you want the field to added to create mutation you need to do this:

```gql
type Foo {
  id: ID!
  title: String!
  bars: [Bar!]!
}

type Bar {
  id: ID!
  description: String!
  note: Note
}
```

which creates the mutation as we want it:

```gql
mutation createBar($description: String!, $noteId: Int!) {
    createBar(input: {description: $description, noteId: $noteId}) {
      ...BarFields
    }
  }
```

**Comment by craicoverflow** [comment]
> @craicoverflow testing this out I find that it's working for one to one but not for one to many. I'm reopening it to track it.
> 
> If you are already fixing this but in another issue just close it again

Ah yeah this is because you need to explicitly add the field to the type on the M:1 side in order for it to be generated. 

So

```gql
type Foo {
  id: ID!
  title: String!
  bars: [Bar]!
}

type Bar {
  id: ID!
  description: String!
}
```

generates the following schema:

```gql
type Foo {
  id: ID!
  title: String!
  bars: [Bar!]!
}

type Bar {
  id: ID!
  description: String!
}
```

So if you want the field to added to create mutation you need to do this:

```gql
type Foo {
  id: ID!
  title: String!
  bars: [Bar!]!
}

type Bar {
  id: ID!
  description: String!
  note: Note
}
```

which creates the mutation as we want it:

```gql
mutation createBar($description: String!, $noteId: Int!) {
    createBar(input: {description: $description, noteId: $noteId}) {
      ...BarFields
    }
  }
```

**Comment by wtrocki** [comment]
We have created another issue to cover this problem:
https://github.com/aerogear/graphback/issues/614
