### ISSUE TITLE
Provide TypeORM DB layer for Graphback 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#535]
We currently use knex, however, knex library is recently introducing a lot of breaking changes in typings. TypeORM seems to be the option that provides much better coverage of the databases and it is also much more mature. The investigation should check how easy/hard will be to build type ORM db layer and what should be involved in it:

https://typeorm.io/#/

TypeORM will introduce a seamless way to work with relationships and give the ability to work ' with NoSQL databases.

## How

Instead of generating mapping files we can generate TypeORM entities that users can tweak later.

**Comment by wtrocki** [comment]
FYI @ardatan

**Comment by wtrocki** [comment]
Moving this out of the 1.0. We should enable people bringing their own ORMS.

**Comment by ardatan** [comment]
@wtrocki I think Graphback can be used only for frontend with TypeORM because TypeORM already fits better with TypeGraphQL in code-first approach while Graphback uses mainly schema-first approach.

**Comment by wtrocki** [comment]
Exactly!
