### ISSUE TITLE
Generated list type does not have same required level as the input model.

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#540]
**Input**
```gql
type Note {
  id: ID!
  title: String!
  description: String!
  ## Relationship
  comments: [Comment!]!
}
```

**Generated**
```gql
type Note {
  id: ID!
  title: String!
  description: String!
  comments: [Comment!] # list is not required
}
```

**Comment by wtrocki** [comment]
I believe that we were doing this to strip out directives and other stuff. Now we can simply print entire type as it is as we might resort to use annotations

**Comment by wtrocki** [comment]
I think target here was to keep the best pattern for array despite what the user puts in the model. 
We should always add `!`

**Comment by craicoverflow** [comment]
> I think target here was to keep the best pattern for array despite what the user puts in the model.
> We should always add `!`

But what about if the user does not want it to be required? We are now overriding their explicit desire to make it required.

If a user creates a `Note` it won't have any comments yet, but our model has `comments` a required. Would this affect things?

**Comment by wtrocki** [comment]
That is the best pattern. I will explain how required statement works on the relationship and you can let me know if you are happy with it.

Imagine having `books: type [Book!]!` 

Basically it says that books is an array of object type Book. The outer exclamation mark says that the array itself cannot be Null — at a minimum, it should be an empty array. The inner exclamation mark says that each entry in the array must be a Book — it cannot be Null. Note that this is a very “conceptual” definition of the books field — it says nothing about the underlying implementation, whether it is a foreign key in a relational table or an object reference in an object database — none of that! All it says is that given an author, we can get their authored books.
```
