### ISSUE TITLE
Use something other than `buildSchema` to create a `GraphQLSchema` object

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#542]
The example apps do the following in order to create a `GraphQLSchema` object:

1. Read the model directory and load contents of `*.graphql` files into a string variable.
2. Use [`buildSchema`](https://graphql.org/graphql-js/utilities/#buildschema) to create a `GraphQLSchema` object from the string content.

A schema generated using buildSchema:

- Cannot specify resolve functions for individual fields
- Cannot specify either resolveType or isTypeOf properties for Types, making it impossible to use Unions and Interfaces.
- Cannot utilize custom scalars

We should consider using some other API or library to do this.

[graphql-toolkit](https://github.com/ardatan/graphql-toolkit#schema-loading) is one option, but would need investigation to see how it works.

**Comment by wtrocki** [comment]
I think in long run we might go with:

- Assume that input is a model (types only) 
This model is parsed by graphql engine but we use it only to build our own understanding.

We can do
1) Generating the fully-featured schema and then this schema will be used everywhere else
2) Generating some abstract model and operate on that model everywhere in the graphback ecosystem - we have that partially done 

If we pick nr 1. Then we will def move away from build/parse schema method

**Comment by wtrocki** [comment]
I do not see any specific issue here that can be resolved. 
@craicoverflow we using the model for the moment which is fine for our needs.
