### ISSUE TITLE
Column/Table Name Transformation

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#554]
## What

`graphql-migrations` has customisable function to transform field and table names to/from the database.

Make this transformation strategy available to Graphback packages so that they can all implement the same transformation and use the same field mappings.

**Comment by wtrocki** [comment]
Currently, we set up defaults inside migration. We should take them out and embed into the core so every module in the ecosystem will know the table names.

This way:

- we no longer need to save state somewhere
- No need for some database tables

We offer highly customizable interface that will understand annotations etc.
