### ISSUE TITLE
Full SQLite support in `graphql-migrations`

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#555]
## What

There a couple of outstanding investigation pieces and issues to ensure that we fully support SQLite in `graphql-migrations`.

### Raw SQL

https://github.com/aerogear/graphback/blob/569935e003b7bcbb0f5d8209bc09e590e44b667e/packages/graphql-migrations/src/connector/write.ts#L243

https://github.com/aerogear/graphback/blob/569935e003b7bcbb0f5d8209bc09e590e44b667e/packages/graphql-migrations/src/connector/write.ts#L336

These raw statements are no supported by SQLite.

### Generated tables

```
drop table `sqlite_sequence` - SQLITE_ERROR: table sqlite_sequence may not be dropped
```

There are some internal tables that are created by SQLite which causes issues when `graphql-migrations` compare databases.

These should be ignored in the diff.

https://www.sqlite.org/fileformat2.html#seqtab

### More

There may be more reasons why SQLite is not fully supported. These require further testing.

**Comment by wtrocki** [comment]
Two ways - we can make exception for sequences or disable dropping tables completely. 
This very simple fix (requires prePlugin to return boolean) will be enough to enable it. 
Apart from this issue, SQLLite seems to be working fine.

**Comment by wtrocki** [comment]
Update initial amount of work was done to support SQLLite - mainly to not delete existing tables

**Comment by wtrocki** [comment]
Current status = Diff engine needs to be database specific. 
There are major differences in how knex returns database specs for different databases. 

![Screenshot 2020-01-03 at 16 57 17](https://user-images.githubusercontent.com/981838/71736939-40552180-2e4a-11ea-82fa-ae8555a6e0e5.png)

To support SQL lite we will need to ignore some of the values as migration engine tries to reexecute alter column tables based on wrongly compared data:

```
sqlite3 foreign keys not supported
getForeignKeys.ts:30
sqlite3 column unique constraints not supported
getCheckConstraints.ts:56
sqlite3 doesn't support column comment
getColumnComments.ts:25
sqlite3 primary keys not supported
getPrimaryKey.ts:25
sqlite3 column index not supported
getIndexes.ts:45
sqlite3 column unique constraints not supported
getUniques.ts:39
sqlite3 foreign keys not supported
getForeignKeys.ts:30
sqlite3 column unique constraints not supported
getCheckConstraints.ts:56
sqlite3 doesn't support column comment
getColumnComments.ts:25
sqlite3 primary keys not supported
getPrimaryKey.ts:25
sqlite3 column index not supported
getIndexes.ts:45
sqlite3 column unique constraints not supported
getUniques.ts:39
sqlite3 foreign keys not supported
getForeignKeys.ts:30
sqlite3 column unique constraints not supported
getCheckConstraints.ts:56
sqlite3 doesn't support column comment
getColumnComments.ts:25
sqlite3 primary keys not supported
getPrimaryKey.ts:25
sqlite3 column index not supported
getIndexes.ts:45
sqlite3 column unique constraints not supported
SQLite3 Foreign & Primary keys may only be added on create
logger.js:44
Sqlite does not support alter column.
```

While this is not causing any issues and SQL lite database works after, it clearly shows the weakness of comparing the database changes with the schema as opposed to schema as source of truth. 

Generally multiple operations and annotations will not be supported for SQL Lite which leads me to the point that for SQL lite we simply might use previous migration mechanism while recomending and diff one for postgress only (and other db in future).

Generally current abstraction for the database changes is very postgress specific and it will require rewrite of the diff mechanism to support more db layers.

**Comment by wtrocki** [comment]
As quick workaround we might simply regenerate sqllite db everytime we do migration directly in the CLI. and document it. 

@craicoverflow

**Comment by wtrocki** [comment]
Our support for SQL lite now might be just that we will always dump the entire database. What it means that for database migration that involves SQLLite we can always return empty database structure and let migration recreate it.

**Comment by wtrocki** [comment]
I think we should focus on MySQL and Postgres and Mongo. 
This will work with SQL lite but we do not want to expose it to the users.

**Comment by wtrocki** [comment]
Removed from docs
