### ISSUE TITLE
[Master] Relationships directions are invalid 

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#563]
See commented out integration test

Having model:
```
export const schema =
  `type Item {
    id: ID!
    name: String
    title: String
  }

  type Comment {
    id: ID!
    description: String
    item: Item
  }
```

I'm getting commentID as required:

<img width="268" alt="Screenshot 2019-12-13 at 16 29 15" src="https://user-images.githubusercontent.com/981838/70815788-1027df00-1dc6-11ea-8fe2-66fc2c52cb29.png">

I believe that the current way to work with relationships in model needs to change. 
We should allow array types etc.

ping @craicoverflow

**Comment by craicoverflow** [comment]
I just tried this out, but don't see the same inputs as you.

```gql
type Item {
  id: ID!
  name: String
  title: String
}

type Comment {
  id: ID!
  description: String
  item: Item
}
```

![Screenshot from 2019-12-17 09-28-41](https://user-images.githubusercontent.com/11743717/70982877-b0745100-20af-11ea-97ac-76d9355e73ea.png)

Could you see if this is still happening?

**Comment by wtrocki** [comment]
It looks like this issue was resolved at some point
