### ISSUE TITLE
How to install pre-release?

### ISSUE THREAD

**Issue by gaharrington** [aerogear/graphback#565]
How do I install pre-release graphback-cli? 

I do not understand the difference between the tags I see on this repo (https://github.com/aerogear/graphback/) and this info (https://www.npmjs.com/package/graphback-cli)

**Comment by wtrocki** [comment]
@gaharrington You can try our prerelease in https://github.com/Urigo/graphql-cli
We are actually working towards 1.0 so 0.10.0-rc2 will most likely become 1.0 once we resolve some of the issues

**Comment by wtrocki** [comment]
Thank you for the logging issue. 
I'm about to release another version of graphback in coming days also graphql-cli still can be used for the moment. Closing but feel free to reopen with more questions
