### ISSUE TITLE
Investigate using GraphQL-Compose for schema generation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#58]
The current template-based approach is really limited as it is constructed based on AST, but it will not support many different use cases like Fragments and buffers. 

GraphQL compose will allow a more flexible approach and it even has support for plugins: https://graphql-compose.github.io
We should explore using GraphQL compose

**Comment by ankitjena** [comment]
This looks promising. And has a lot of advantages over our current approach
