### ISSUE TITLE
[Feature Request]: Recommend matching commands if the user makes a typo

### ISSUE THREAD

**Issue by jamesgeorge007** [aerogear/graphback#593]
`graphback confi`

### What Expected

// help msg

Did you mean config?

**Comment by wtrocki** [comment]
See: https://github.com/yargs/yargs/blob/afaf6d38aad3cc016f130faa1ebafc165807fade/lib/validation.js#L324

**Comment by jamesgeorge007** [comment]
#594 makes use of the in-house solution to achieve the respective functionality.

**Comment by wtrocki** [comment]
CC @craicoverflow
