### ISSUE TITLE
Make generated schema using the opiniated patterns for schema generation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#60]
There are couple of patterns that we can employ from here: 
https://graphql-rules.com/

Let's have a discussion in this thread what patterns we can employ and we can apply them to the generated schema

**Comment by ankitjena** [comment]
Some patterns we need:
https://graphql-rules.com/rules/list-filter
https://graphql-rules.com/rules/list-limit-skip
https://graphql-rules.com/rules/list-pagination
https://graphql-rules.com/rules/mutation-business-operations

**Comment by wtrocki** [comment]
@ankitjena Can we post example input and output schema here?
It will be cool for us to open discussion on how this could look like.

IT is also a quite an important time for our team as we might use those for our sample apps.

ping @darahayes @StephenCoady

**Comment by ankitjena** [comment]
- Filtering - Combining filter options inside one filter argument. These would be specific for each type.
```
type Query {
  articles(filter: ArticleFilter): [Article]
}

input ArticleFilter {
  authorId: Int
  tags: [String]
  lang: LangEnum
}
```
- Limit - imit the number of items in the list
```
type Query {
  articles(limit: Int! = 20, skip: Int): [Article]
}
```
- Pagination - paginate items in list. For example, if Article and User are types two types ArticlePagination and UserPagination will extend PaginationInfo
```
type Query {
  articles(page: Int! = 1, perPage: Int! = 20): ArticlePagination
}

type ArticlePagination {
  # Array of objects.
  items: [Article]!

  # Information to aid in pagination.
  pageInfo: PaginationInfo!
}

type PaginationInfo {
  # Total number of pages
  totalPages: Int!

  # Total number of items
  totalItems: Int!

  # Current page number
  page: Int!

  # Number of items per page
  perPage: Int!

  # When paginating forwards, are there more items?
  hasNextPage: Boolean!

  # When paginating backwards, are there more items?
  hasPreviousPage: Boolean!
}
```
- Group mutations into single type - Group specific mutation of one type into a single type. This will reduce clutter as the API grows.
```
type ArticleMutations {
   create(...): Payload
   update(...): Payload
   delete(...): payload
}
```
- Better mutations - More than standard CRUD operations. Separating functionalities from these into separate mutations.
```
type ArticleMutations {
   create(...): Payload
   update(...): Payload
+  like(...): Payload
+  unlike(...): Payload
+  publish(...): Payload
+  unpublish(...): Payload
}
```

**Comment by wtrocki** [comment]
1) I believe this works like this already.
2) 3) How we intent do to both? They exclude each other.

3) We can use GraphQL modules to deliver elements like PaginationInfo.
This will mean that results schema can be much smaller and readable. 

4) Not sure if that is a good idea.
5) How is that possible? Do do not write schema ourselves - we trying to generate CRUD so the rule to not write crud requires you to know the business logic.

What we need is just an example of a single type and the output schema we will get after the generator kicks in. Let's create this as form of PR so we can comment on individual lines.
