### ISSUE TITLE
[CLI]: Notify the users of an available update

### ISSUE THREAD

**Issue by jamesgeorge007** [aerogear/graphback#605]
## Feature Request

Users may not be aware about any newer releases being made and would end up using the older versions.

[update-notifier](https://www.npmjs.com/package/update-notifier) serves the purpose here. As from the tagline, `Inform users of your package of updates in a non-intrusive way`.

**Comment by wtrocki** [comment]
@jamesgeorge007 With the latest update graphback becomes less about CLI and more about codebase and plugins it will offer. Because of that we will encourage people to watch our repository for releases instead of relying on cli versions (as there will be different types of releases etc.
