### ISSUE TITLE
Knex typings bumps break other clients

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#619]

**Comment by craicoverflow** [comment]
https://github.com/aerogear/graphback/blob/1d8533d58a6c18c5269a4e85b11cc0ae5c1fa49a/docs/database-schema-migrations.md#L33

Should we update docs also?

**Comment by wtrocki** [comment]
Migrations include knex inside. Runtime includes knex inside. This was just issue with runtime example that is trying to go with the most explanatory case by providing full customization and then including knex inside.
