### ISSUE TITLE
Support for schema  generation using existing database connection

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#636]
## Overview

Graphback only supports a data model first approach, where the types defined in the model are used to generate a database structure which maps directly to these types.

This is great for new projects, it makes it really easy and quick for a user to build their new server and database.

But it also makes it harder for people looking to migrate their existing applications to use Graphback.

## Implementation

[`graphql-migrations`](https://github.com/aerogear/graphback/packages/graphql-migrations) creates an abstraction model from your data model and database, comparing the two models to find the difference and apply these differences to your database to update its structure.

We can reuse this abstraction logic to create an abstract database model from an existing database. Each abstract table can then be mapped back to a GraphQL type, using sensible default field names, with perhaps some additional scalar support (JSON).

## Challenges

1. Ability to identify ManyToMany tables and correctly map the relationship to GraphQL type.

2. I think this should be a separate package from `graphql-migrations` as the responsibility is quite different. What then should we do to prevent a lot of duplicate abstraction logic between the two packages? We may need to have a third package just for the abstraction code which can be consumed by them both. This way the abstractions will not diverge in the future (for example if we decide to change the mapping between a database type and GraphQL type.

3. Maybe we will find from spikes/research that the abstraction logic in `graphql-migrations` does not fit this specific use case so it would need to be adapted heavily anyway so there would be no need for the common abstraction. Requires further investigation.

**Comment by wtrocki** [comment]
I had spiked this approach before and we have some documentaiton on what was the proposed flow for this to work. Generally we can always stay with model as input but use some external CLI to generate graphql schema. I think postgraphile, prisma and hasura have those tools, but they are embeeded into their tooling (there is no separate cli tool that will do that explicitly.)

If we do that by letting developers manually review db structure and fix some of the issues after then we can overcome all mentioned issues above.

More info:
https://graphback.dev/docs/migrations

**Comment by craicoverflow** [comment]
> I had spiked this approach before and we have some documentaiton on what was the proposed flow 
> If we do that by letting developers manually review db structure and fix some of the issues after then we can overcome all mentioned issues above.

So basically this (https://github.com/aerogear/graphback/issues/637) then :smile:

**Comment by wtrocki** [comment]
Yup. We have done OpenAPI migrations the same way.

**Comment by wtrocki** [comment]
This will be good first issue for anyone looking for really easy and rewarding job
