### ISSUE TITLE
Research OpenCRUD

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#638]
## Overview

[OpenCRUD](https://www.opencrud.org/) is defined as:

> a fully GraphQL compliant query language to access and modify data.

It is a specification that aims to standardise CRUD queries and mutations.

Graphback does not follow this specification, we instead have our own CRUD implementation.

The question is should we adopt OpenCRUD?

## Benefits

- Graphback would follow a public pattern for creating CRUD queries.
- Makes it easier for people to migrate to Graphback.

## Concerns

- OpenCRUD has not seen much adoption and has faced resistance from some of the leading players. See https://github.com/hasura/graphql-engine/issues/1358 and https://github.com/strapi/strapi/issues/1057 as examples.
- It was being driven by Prisma who have gone in a different direction, leading to the specification being essentially abandoned. 
- The last update to the specification was 2 years ago, and it is still in the first working draft meaning the specification might be unfinished and could change.

## More

It is certainly worth researching a bit more so we can decide if this will benefit our targets enough to implement.

**Comment by wtrocki** [comment]
As a team we made choice to build our own CRUD spec for flexibility. Prisma CRUD spec is very specific to prisma and have totally differet goals - they kinda trying to cover every possible fitering scenario in CRUD - which is basically wrong approach as it leads to anemic mutations and conflicts that are impossible to avoid. 

Graphback is going to use very flexible approach forcing developers to write their own mutations and queries thus our CRUD model do not need to have advanced filtering etc.
