### ISSUE TITLE
Remove mixed test executors

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#641]
In some cases we are using jest and is some cases we are using ava

**Comment by wtrocki** [comment]
Our prefference will be to use jest

**Comment by binayakbehera999** [comment]
Hello, @wtrocki I would like to work on this issue. Can we use the jest-code to migrate to jest?

**Comment by wtrocki** [comment]
Anyway to migrate will work for me. Minimize amout of work needed

**Comment by wtrocki** [comment]
@binayakbehera999 We are hitting some issues in relation to jest/ava and we have now a great time to migrate them. Do you still work on this?

**Comment by kingsleyzissou** [comment]
@wtrocki I can look at this if you want. Are you okay with doing it similarly to how offix is setup and run jest from the root?

**Comment by wtrocki** [comment]
@craicoverflow Any opinions on this? 
I guess having some form of standard across two repos is good.

**Comment by kingsleyzissou** [comment]
Just saw that @darahayes was doing something with Jest. Are you already working on this issue?

**Comment by darahayes** [comment]
I was looking into it but please feel free to take it 🙂

**Comment by kingsleyzissou** [comment]
No stress, haven't started yet. If you're already on it you may as well

**Comment by craicoverflow** [comment]
> @craicoverflow Any opinions on this?
> I guess having some form of standard across two repos is good.

No strong opinions - what are the issues you speak of?

**Comment by kingsleyzissou** [comment]
Closed with #921

**Comment by kingsleyzissou** [comment]
#921

**Comment by kingsleyzissou** [comment]
Closed with PR #921

**Comment by kingsleyzissou** [comment]
Closed with PR #921
