### ISSUE TITLE
Add support for custom id's

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#648]
Could it be autoincrementing and id: ID! by default but allow to use anything as ID and then do not care about increments and anything else. For example email could be marked as unique and that will be enough to have it as ID

**Comment by wtrocki** [comment]
`default: id: ID!`

Without annotation:
`email: ID!`

Validation for multiple ID's error!

""" db.id """
`email: String!`

**Comment by craicoverflow** [comment]
What order do we choose?

If our model has:

```gql
id: ID!
```
and

```gql
@db.primary
email: String
```

which should we choose as the primary key used in database generation and mapping?

I think we should prefer the `@db.primary` field over `id: ID!` field. This is an explicit request by the user to make this the primary key so it should be treated as such.

^^ @wtrocki

**Comment by wtrocki** [comment]
Fully agree. Explicit over implicit case

**Comment by craicoverflow** [comment]
This is now merged in Graphback, but `graphql-migrations` does not have this support yet (it is restricted to `id: ID!`. Closing this issue however as this is related to mapping and not migrations.
