### ISSUE TITLE
Implement watch command line

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#65]
Watch command line should watch for changes in graphql files and rebuild the schema, resolvers and db. For the database we should initially drop all tables as altering the tables based on diff will be investigated in other issue

**Comment by ankitjena** [comment]
What would be a good approach to dropping tables, problem arising if relationship have been created then we can't drop the table if data exists in a relation, we would have to do that without conflicts. Also tried `schema.destroy()` which didn't work.

**Comment by wtrocki** [comment]
Destroy should work. Why it do not work
