### ISSUE TITLE
Move testx to graphback?

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#659]
Testx provides a lots of value for testing and also demo app usage.

It will be cool to be able s use testx without having code at all. 
For example, we can use cli were we passing:

To start server
```
npx graphql-serve start ./model
``` 

To generate client-side queries

```
npx graphql-serve client ./model ./client
```

Cmd can also rely on graphback configuration available in the project and run things smoothly. TestX can still be used for testing but it will also have great value for users that want to quickly test their app with some backend.

Moving testx will mean:

- We can release it and tie to graphback versions
- TestX will rely on the graphback protocol and provide true runtime layer
- It can have small micro cmd involved

We can have some of the GSOC students helping us with that initiative

**Comment by wtrocki** [comment]
This way we can still maintain testx and use it along with other libraries inside graphback. Original package will stay as it is. We can rename things to `graphqlrun` etc.

CC 

@b1zzu @darahayes

**Comment by wtrocki** [comment]
We can also use multiple packages for client and server without issues

**Comment by wtrocki** [comment]
See also: https://github.com/aerogear/graphql-testx/pull/186

**Comment by b1zzu** [comment]
I agree that testx fit better inside graphback, I'm just thinking about how we could move it inside without losing tests, examples, and documentation

**Comment by wtrocki** [comment]
All can be inside graphql-serve folder so package itself will be independent and still have docs. We can also put some of the stuff into graphback website to popularize it. Target is to add graphpqhl serve to graphql cli so we can popularize CRUD format of graphback etc.

**Comment by wtrocki** [comment]
Ok. I think it is settled then. We really want to maintain it and we have good plan on how to do it. If we still have concerns about that let me know.

@b1zzu as you were mostly the original author of the changes I would like if you could simply copy-paste all the changes into graphback master in the form of PR. This will give you original attribution for the changes etc.

**Comment by b1zzu** [comment]
@wtrocki PR created, but there are still many things to todo

**Comment by wtrocki** [comment]
@b1zzu Do not worry. All I wanted is to have original source code on your own name. I will take look and refine this PR next week as we focusing now on refactoring stuff. Obviously original testx-repo can be still maintained etc. there is no problem with that.

**Comment by b1zzu** [comment]
@wtrocki well I think is kinda strange to maintain the same code on tho repos, it could make sence until testx is not completed integreated in graphback but otherwise after it I was thinking to deprecate the graphql-testx repo

**Comment by wtrocki** [comment]
Yes. But until we have it in graphback we can still do stuff there
