### ISSUE TITLE
Graphback generator fullstack sample react app.

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#691]
Improve template client application. 
Add support for more crud methods
Add styles like in Todo app

**Comment by wtrocki** [comment]
We can update and use offix example from here
https://github.com/aerogear/offix/tree/master/examples

**Comment by udith-shalinda** [comment]
@wtrocki is there anyone working on this?

**Comment by wtrocki** [comment]
No. Assignig to yourself

**Comment by wtrocki** [comment]
Awesome job! Closing as app is in decent state. Some styles might need to be applied later
