### ISSUE TITLE
Refactor documentation to docusaurus.io

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#70]
## Background
Currently documentation is done using docsify. Docusaurus.io provides a lot of better features and current documentation has a lot of missing pieces.

## Tasks
- [ ] refactor from docsify.js to docusaurus
- [ ] document missing pieces including cli workflow #64

**Comment by wtrocki** [comment]
@ankitjena I'm still going to investigate it and provide updates.

**Comment by ankitjena** [comment]
@wtrocki Status on this? Should we proceed with this. Docusaurus is really good from what I checked.

**Comment by wtrocki** [comment]
+1000 for docusaurus
