### ISSUE TITLE
Verify graphback MySQL support

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#707]
Check if graphback will work out of the box with MySQL when using Knex.js configuration

**Comment by udith-shalinda** [comment]
I'll check this one

**Comment by wtrocki** [comment]
@udith-shalinda Thank you so much!

**Comment by udith-shalinda** [comment]
@wtrocki Is there any way to create all tables according to the models at first

**Comment by wtrocki** [comment]
graphback db?

**Comment by wtrocki** [comment]
graphback db?

**Comment by udith-shalinda** [comment]
mysql tables won't get created automatically.We have to create them once.

**Comment by wtrocki** [comment]
Can you elaborate more? What is the error and what template is used? Can you share your dbmigrate config or even create PR with some working changes 👯

**Comment by wtrocki** [comment]
I have done quick check on mysql and db migrations will need to be refactored to support MySQL - Second update never works. 

@udith-shalinda went further and tried to implement datasource, but really we cannot have datasource without database migration. Unless there is strong need for MySQL we will stick to Postgress and Mongo

CC @craicoverflow
