### ISSUE TITLE
Create MongoDB DB layer on top of runtime

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#708]
Currently graphback supports only knex based databases. We should create community supported mongo version

**Comment by udith-shalinda** [comment]
Do I need need to create an alternative file for KnexDBDataProvider

**Comment by wtrocki** [comment]
@udith-shalinda Yes. That will be the way forward. We can implement it in the same package for now for simplicity

**Comment by udith-shalinda** [comment]
@wtrocki Anyway I have created a separate file. I had to pass mongoose models from resolvers and  `return context.crudService.findBy("note", args.fields);` will be changed to  `return context.crudService.findBy(MongooseModel, args.fields);`

Can you give me a reference where I can find how to generate mongoose model?

**Comment by wtrocki** [comment]
Why not use mongo driver directly? Using mongose in this context makes less sense. Also please make sure you use latest changes on master. Current crud interface looks different

**Comment by wtrocki** [comment]
I have published new docs that explain the changes on master. Things will be much easier to integrate now

**Comment by udith-shalinda** [comment]
Now I'm using mongo driver instead of mongoose.

**Comment by udith-shalinda** [comment]
With the new version,I'm little bit confused about how you manage table name in curdservice

**Comment by wtrocki** [comment]
@udith-shalinda Mapping abstraction brings some complexity as people can specify different collection name on their type system. 
I guess for the initial version you can use the original name from the type or something like `graphqlType.name.toLowerCase()`

FYI @craicoverflow

**Comment by wtrocki** [comment]
Thanks to awesome contribution to @udith-shalinda we have now mongo supported (relationships/batching will land soon as well)
