### ISSUE TITLE
Validate data model before generating schema

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#713]
The data models should be validated before generating the schema and resolvers. This should ensure that only a valid schema is generated.

Some things that need to be checked:

- [ ] Validate whether model has primary key

**Comment by wtrocki** [comment]
Let's add more info about relationship validation and do it as part of this PR

**Comment by wtrocki** [comment]
@craicoverflow resolved this issue directly in the plugins. For now on we will throw issues in the plugins. There is idea to wrap plugin error to produce easily trackable information but that is not needed for the moment
