### ISSUE TITLE
Feedback: Graphback config should let you skip database creation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#716]
Config only supports 2 databases. Developers should be able to skip db creation completely and provide their own CRUD source.

**Comment by jaskeerat789** [comment]
@wtrocki I am working on this issue

**Comment by jaskeerat789** [comment]
https://github.com/aerogear/graphback/blob/master/packages/graphback-cli/src/components/init.ts#L8
The `initConfig` was imported but never used... should I remove it there is some role of it

**Comment by wtrocki** [comment]
This issue is very similar to the https://github.com/aerogear/graphback/pull/800
I think we had some conflict in those. We initially wanted to skip it but now we actually asking for the db. Sorry for that @jaskeerat789

**Comment by jaskeerat789** [comment]
no problem
