### ISSUE TITLE
replace Db annotation with data annotation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#720]
DB annotation it's very specific to the Data Base having data will be easier to document and understand. 

we can use single namespace for entire ecosystem. this could be used in generators mapping and data base layer

**Comment by wtrocki** [comment]
@craicoverflow

**Comment by craicoverflow** [comment]
The `@db` annotation is very specific to the database because it is tightly coupled with **database** migrations, and mapping data from GraphQL to the database. I see no reason to change it.

- `@data.name` ⬅️ Not obvious this is for mapping to the database name.
- `@db.name` ⬅️ Obvious what it does (to me).

**Comment by wtrocki** [comment]
Trick is that this is no longer specific to the database. 
We going to build mappings that various layers/plugins can consume. Le'ts keep db then.

**Comment by craicoverflow** [comment]
I can't picture a use-case right now where the `@db/data.name` would be used outside of database-specific stuff?

```json
{
  "name: "Enda",
  "location": "Ireland"
}
```

While this data lives on the server, it does not need to be mapped to a different structure. It is only when the data is passed to an external data source might it need to be changed.

Each layer/plugin can consume this mapping but the mapping only takes place when passing to a data source.

I'm happy to continue a discussion about this to see if it should be changed.

I guess one reason for changing it to `@data` would be that the external data source might not always necessarily be a database?
