### ISSUE TITLE
Graphback Getting Started included on website

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#723]
We can use similar approach to: https://aws-amplify.github.io/docs/

**Comment by urvashigupta7** [comment]
@wtrocki I would like to work on it. Can you please specify what exact content needs to be there in Getting Started?

**Comment by urvashigupta7** [comment]
Can I add this content there? https://github.com/aerogear/graphback/blob/master/docs/gettingstarted.md

**Comment by wtrocki** [comment]
Generally this chapter (which by it's own look really poor):
https://graphback.dev/docs/intro/quickstart

Could be put on the website. 
Generally website loooks really poor as we have small team (just 2 people) and have little time to improve it. 

Website can have some gif/slides of using graphback. Any improvements will be welcomed. 
What I would do is to propose some changes yourself - it can be inspired by link above or something like: https://www.prisma.io/

CC @ankitjena - could you share with us source code for the design we got?

**Comment by wtrocki** [comment]
@urvashigupta7 I have some materials and visuals I can share for website if needed. We looking for small improvements rather than complete redesign. 
Any PR will be valuable.

**Comment by urvashigupta7** [comment]
Yes please share.

**Comment by wtrocki** [comment]
Hi @urvashigupta7 do you need any help with this issue?
