### ISSUE TITLE
Db migrations as separate extension in graphqlrc.yml configuration

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#737]
When doing this we can stop basing on the model and use output schema that will be decorated.

**Comment by wtrocki** [comment]
@craicoverflow This actually critical bug - when you have now multiple model files db migration will not work and fail with 

```
$ /Users/wtrocki/Projects/sandbox/test-generator/node_modules/.bin/graphback db
There can be only one type named "Query".

There can be only one type named "Mutation".
✨  Done in 1.00s.
```

**Comment by craicoverflow** [comment]
> 
> ```
> $ /Users/wtrocki/Projects/sandbox/test-generator/node_modules/.bin/graphback db
> There can be only one type named "Query".
> 
> There can be only one type named "Mutation".
> ✨  Done in 1.00s.
> ```

@wtrocki It looks like you have defined multiple `Query` types across multiple schema files. This will also happen if you define more than one `Query` type in a single schema file. This particular error occurs during `buildSchema` and is more down to the design of the data model.

**Comment by wtrocki** [comment]
yes.. So we could not prevent this from happening. 

Solution is to make our dbmigrations config separate from graphback and then use graphql-config root schema. I would hope to do it before official release as we do not want to break config many times. It should be a very simple thing to do but also might require some testing after.

@cecobask Would that be something that you could help us to do?

Base info - our Graphql-migrations package (in packages folder) accepts schema that comes from model folder which can concatenate multiple different schemas. 
We should use schema that is configured in graphqlrc.yml config

**Comment by cecobask** [comment]
Please, provide some feedback of my work in pull request #749. Thank you :)

**Comment by wtrocki** [comment]
Fixed by @cecobask
