### ISSUE TITLE
Graphback init command is not overriding config for templates

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#740]
Graphback init is not clever enough to override config. It ask if you want to create client side queries etc. but results from those are completely ignored. We should remove these questions from init command.

**Comment by alishamohanty** [comment]
Hello @wtrocki, I would like to work on this. Could help me understand this by providing some pointers?

**Comment by wtrocki** [comment]
Sure. try graphback init command. 
To fix it remove this line https://github.com/aerogear/graphback/blob/master/packages/graphback-cli/src/components/init.ts#L129

**Comment by alishamohanty** [comment]
Thanks. I will make a PR soon regarding it.

**Comment by wtrocki** [comment]
@alishamohanty As this is very simple single line fix I will do that now. Sorry

**Comment by alishamohanty** [comment]
Sorry, for getting it late @wtrocki. I wanted to familiarize myself with Graphback before I could make any PR. That is probably the reason, it came out late. I will make sure, next time I do that right. Thank you.

**Comment by wtrocki** [comment]
Graphback is huge ecosystem of packages and templates. The best way to get started is to pick issue and work on it as it is hard to get general info without experience with GraphQL typescript node.js etc.
