### ISSUE TITLE
`graphql-migrations` produces duplicate relation fields when `@db.name` is specificed on a relationship field.

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#745]
`graphql-migrations` does not handle custom relationship field names. This model will create `note_id` and `noteId` in the comment table.

```gql
""" @model """
type Comment {
  id: ID!
  description: String
  author: String
  """
  @db.oneToOne: 'comment'
  @db.name: 'note_id'
  """
  note: Note
}
```

**Comment by wtrocki** [comment]
I guess we going to resolve that in current relationship PR?

**Comment by craicoverflow** [comment]
Yeah, that will be resolved

**Comment by wtrocki** [comment]
![image](https://user-images.githubusercontent.com/981838/75538206-267e2800-5a10-11ea-8ccd-112fd357f46a.png)

**Comment by craicoverflow** [comment]
This is a matter of documentation. `db.name` should not be specified on relationship fields.
