### ISSUE TITLE
Create different profiles for ts compilation

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#755]
On development we should not generate d.ts files as they are disturbing the workflow.
For production we should have d.ts files generated

**Comment by jaskeerat789** [comment]
hey @wtrocki ...I would like to work on this!!!

**Comment by jaskeerat789** [comment]
@wtrocki sir can you tell me the steps to reproduce the problem

**Comment by wtrocki** [comment]
If we navigate to any class from different package vscode will navigate to d.ts files rather than original source code. We need to see if we can remove this d.ts files in development  while still having it build for production and releases

**Comment by wtrocki** [comment]
This issue is currently free
