### ISSUE TITLE
Graphback Config should ask for different databases

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#757]
When doing config we should utilize our datasources intergration:
See
https://github.com/aerogear/graphback/pull/746

**Comment by wtrocki** [comment]
We need to ask for 
- MongoDB (and provide default docker-compose
- Postgres (Nothing changes here)

We not going to support other databases.

Install different runtime package based on the choice (currently installs only @graphback/runtime - if should @graphback/runtime-mongo or @graphback/runtime-knex

DataSources documentation should be also updated

**Comment by wtrocki** [comment]
@craicoverflow This is blocker for relase. If not done by commmunity we will need to do it ourselves.

**Comment by NVS16** [comment]
Can I work on this issue?

**Comment by wtrocki** [comment]
@NVS16 Perfect. Copy some files from our example app:
https://github.com/aerogear/datasync-starter/blob/master/server/docker-compose.yml

**Comment by NVS16** [comment]
Ok. Working on it.

**Comment by ankitjena** [comment]
> Install different runtime package based on the choice (currently installs only @graphback/runtime - if should @graphback/runtime-mongo or @graphback/runtime-knex

@wtrocki We need to have changes in the templates too since they have this as default
```
import { createKnexPGCRUDRuntimeServices } from "@graphback/runtime-knex"
```

**Comment by wtrocki** [comment]
Yes. There is issue to document that but I'm currently occupied by finishing code changes

**Comment by wtrocki** [comment]
See: https://github.com/aerogear/graphback/issues/756

Swapping datasource involves changes in the template which is tricky to do. 
What we can do is to have some file in template that initializes proper datasource. Like datasources.ts and replace it with the cli based on choice. 
This will make it hard to build new templates but we are not woried about it

**Comment by NVS16** [comment]
I had some doubts regarding writing the documentation and wanted your help.

```
I guess we need to at least add some info here:
https://graphback.dev/docs/intro/existingproject
and here:
https://graphback.dev/docs/db/datasources
```

in datasources - We add that we now support mongodb (and remove sqlite3 and mysql) 
in the first link - 
We have to add what a user needs to manually do to change his code so as to comply with postgres or mongo, whatever he chooses.
As far as I can see the user will have to modify these two files in the template - 
1. db.ts
2. graphql.ts 
(Are there anymore files to change?)
I believe I can use the files here - 
https://github.com/aerogear/datasync-starter/blob/master/server/src/db.ts
https://github.com/aerogear/datasync-starter/blob/master/server/src/graphql.ts 
which you had provided me earlier.

Now, maybe we can approach in this way - 
- Make a new folder in the /src folder, let's say, /src/dbsetup/  (or something like that)
- here in this folder we have two subfolders /src/dbsetup/mongodb and /src/dbsetup/postgresql
- and each of the folders will have the respective db.ts and graphql.ts files.
- by default the original db.ts and graphql.ts will have the code for postgresql (let's say) 
- then if the user has chosen mongodb he will just replace it with the files of mongodb present in /src/dbsetup/mongodb

Am I going in the right direction?

**Comment by wtrocki** [comment]
As mentioned before. config is being run on project that has no dB files. it is just some project that wants graphback to be added.

I think @ankitjena created new issue and we need to have software fix for this rather than docs.

**Comment by wtrocki** [comment]
@NVS16 thank you for your contribution
