### ISSUE TITLE
Soft deletes for Graphback datasources.

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#778]
Currently all graphback datasources perform hard deletes. We can do soft deletes as option with some indexing involved to improve perfomance. This is up to discussion so not adding any label yet

**Comment by wtrocki** [comment]
OffixDataSource should use extra _deleted field when fetching data

**Comment by udith-shalinda** [comment]
@wtrocki I would like to work on this. Should I insert an extra field as Flag

**Comment by jaskeerat789** [comment]
Hey @udith-shalinda i am already working on this... I hope you don't mind

**Comment by wtrocki** [comment]
@jaskeerat789 Please add comment next time that you work on something

**Comment by jaskeerat789** [comment]
sure sir

**Comment by jaskeerat789** [comment]
after going through the codebase ... What I understood is that we should add an extra filter while fetching in [this file](https://github.com/aerogear/graphback/blob/master/packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts#L88)

We may also create an extra function to perform the soft delete... [file](https://github.com/aerogear/graphback/blob/master/packages/graphback-runtime-mongodb/src/MongoDBDataProvider.ts#L51)
@wtrocki @udith-shalinda pls guide if I am wrong...

**Comment by wtrocki** [comment]
@jaskeerat789 The main thing here is to see if you will be able to implement that feature yourself without requiring any assistance. @udith-shalinda is our great community member so let's not ping anyone that is not in the core team.

There is nothing wrong with creating PR that is not going to work and ask for help. For the moment it is hard to help without code context

**Comment by jaskeerat789** [comment]
Got it

**Comment by jaskeerat789** [comment]
@wtrocki pls go through the PR

**Comment by wtrocki** [comment]
@wtrocki Move this issue to datasync repository.
