### ISSUE TITLE
Integrate graphql-query-mapper into graphback queries

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#793]
When making queries we always select all data which is no efficient.
We can use graphql-query-mapper library to see what kind of data was requested and map it directly in our API. 

## Targets

- Eliminate select * from all queries.
- Add a way to integrate query-mapper - selectionSet into context so CRUD layer can detect it and act on it.

## Stretch Goals

- Knex doesn't seem to be generic to be able to implement all crud methods and swap databases. There are differences which means that we will need to implement each db directly. Instead of using knex we can rely on actual db drivers which will allow us to get better insights into performance and consistency handlers

**Comment by wtrocki** [comment]
Target here is to avoid * when doing selects. We can use some parts of the query mapper to get actual fields.

**Comment by machi1990** [comment]
This is something I'll be willing to give a try at some point. 

WDYT? @wtrocki @craicoverflow

**Comment by wtrocki** [comment]
Yes. This can be perfect issue to grab

**Comment by craicoverflow** [comment]
Related https://github.com/aerogear/graphback/issues/1281

**Comment by craicoverflow** [comment]
> This is something I'll be willing to give a try at some point.

Yep, this would be great to have.

**Comment by wtrocki** [comment]
We need that for 0.14.0 (specifically we want to execute total count only when a client requests it.

**Comment by wtrocki** [comment]
Bumping this. WE need that for 0.14.0
