### ISSUE TITLE
Generation failed: Error: Can not build schema. Must be initialized Query type

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#796]
If we do not have a query type initialised in the data model, `schemaComposer.buildSchema` fails as queryType is undefined.

See: https://github.com/graphql/graphql-js/issues/448

**Comment by craicoverflow** [comment]
This error is only reproducible in https://github.com/aerogear/graphback/pull/736 but it might be a wider issue which deserves investigation.

**Comment by craicoverflow** [comment]
This was a bug on our side. Closing

**Comment by craicoverflow** [comment]
I've put out a fix in https://github.com/graphql-compose/graphql-compose/pull/237 - in the meantime we will need to workaround it.

**Comment by Eunovo** [comment]
I want to work on this issue. Can I?

**Comment by craicoverflow** [comment]
> I want to work on this issue. Can I?

hey @Eunovo - this is an issue with a library we are using, I've put in a fix request here - https://github.com/graphql-compose/graphql-compose/pull/237

Closing this.

**Comment by nodkz** [comment]
@craicoverflow thanks for PR. Just bump a new version with your fix graphql-compose@7.12.4
