### ISSUE TITLE
Add capabilty to extend GraphQL schema types

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#799]
GraphQL schema types are immutable by design, but we need the ability to modify types throughout the plugin execution chain.

To do this right now we are using `graphql-compose` to modify schema objects, but this has its own issues (https://github.com/graphql-compose/graphql-compose/pull/237).

We should come up with a way to modify GraphQL types.

cc @cecobask @wtrocki

**Comment by wtrocki** [comment]
Generally we need to have pattern for extending schema in plugin - documentex. This will be particularly important for DataSync where we will be modifying queries etc.

Our offix plugin has some of this capabilities hacked but we seen some side impacts in form of null values in params and other stuff

**Comment by nodkz** [comment]
@craicoverflow thanks for PR. Just bump a new version with your fix in graphql-compose@7.12.4

**Comment by wtrocki** [comment]
Works like dream
