### ISSUE TITLE
[Discussion] Runtime exposes database client based on config

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#801]
Currently the two db layers, `runtime-knex` and `runtime-mongo` are separate packages. This causes a problem in templates which have `runtime-knex` by default.

## Idea
We can have micro templates which get extracted when running `graphback config`. Each having configuration for db setup (these include files in template which create connection and connect to context)

**Comment by wtrocki** [comment]
Idea was that there is no problem as we can tell people to switch manually. Generally we would want to avoid importing all database packages in production build. Switch should happen at graphback config time - it can be both by dropping preconfigured code that can be connected manually by user. I think this issue could be follow up for graphback config issue..We might ask for language and drop template with some code

**Comment by wtrocki** [comment]
We can have some micro templates created by config that will connect to datasource

**Comment by ankitjena** [comment]
Micro templates seems like a good idea for now.

**Comment by wtrocki** [comment]
Since we have great docs for the datasources we should print link to the docs in the final message of the config
