### ISSUE TITLE
Descriptions added to fields and types with `graphql-compose` are not added to final schema

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#814]
## Description

This may be an issue with `graphql-compose` or maybe we are misusing it. 

Using SchemaComposer to add or update fields to our schema in the SchemaCRUDPlugin causes the descriptions to be lost in the generated schema. It is not clear why, this requires further investigation.

As a workaround for now doing `buildSchema(printSchema(schema)` saves the descriptions.

**Comment by asraman9792** [comment]
how i can help sir ?

**Comment by wtrocki** [comment]
Actually this was resolved
