### ISSUE TITLE
Integrate graphql-serve with graphback

### ISSUE THREAD

**Issue by ssd71** [aerogear/graphback#828]
The graphql-serve package uses outdated version of the graphback packages. It needs to be ported to the newer versions of said packages.

Work In progress:

- [x] Add serve and print schema commands
- [x] Update Readme
- [ ] Integrate gql serve with graphback-cli
- [ ] Update docs
- [ ] Add tests
- [ ] Improve CLI
- [ ] General code cleanup

**Comment by ssd71** [comment]
I am working on this issue

**Comment by ssd71** [comment]
Some of the work has been done in #830 
I will continue to work on some of these in another PR

**Comment by wtrocki** [comment]
Package has been set to private true. Once we fix readme we can remove it in order to release it

**Comment by craicoverflow** [comment]
This looks to be done, but feel free to reopen if I am wrong.
