### ISSUE TITLE
Code generation engine V2.0

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#83]
## Background
We are using `graphql-code-generator` version `0.18.2` in our code base to help generate the schema. Particularly we are using the method `schemaToTemplateContext` to parse datamodel file and use handlebars to generate schema.

## Version 1.0
`graphql-code-generator` has released version `1.0.0` which removes the above mentioned method as stated in docs
>Remove the old, deprecated code from this repostory (everything related to flattenDocuments and buildSchemaContext).

Current version's method generate string in output file format. Check PR #84 

## Requirement
- We need to use version `1.0.0` to generate Resolver Typings to generate resolvers(these are generated to an output file)
- Figuring out Schema generation in current version.

**Comment by wtrocki** [comment]
We decided we need to rearchitecture currently graphback package to rely on the plugins and utilize latest version of the tool. 

![Screenshot 2019-06-28 at 14 58 13](https://user-images.githubusercontent.com/981838/60349061-c3d41880-99b8-11e9-9446-5957a16fc00d.png)

**Comment by ankitjena** [comment]
Upon further inspection we might not need separate packages after all. Using the visitor pattern we can replace the deprecated context generation part. And redesign the core along the way. Graphql-code-generator doesn't provide much value at out current scope. But we might use it to provide out of the box solutions in future.

**Comment by ankitjena** [comment]
Closing this

**Comment by dotansimha** [comment]
@ankitjena the changes in https://github.com/aerogear/graphback/pull/112 looks great :)
What do you think about wrapping these visitors as `graphql-codegen` plugin? this way it will be available as ready-to-use and independent generator.
It might also make it easier for you to load the schema (because the codegen does that with graphql-toolkit, and it can easily load schema from any file - code/graphql ast/exports/url).

**Comment by wtrocki** [comment]
+100 for wrapping our code and using extended features of codegen
