### ISSUE TITLE
Graphback should generate multiple input types

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#844]
We should have input types that actual match the require fields etc. to enable better validation

We should have 2 input types:

- Used for filtering (without required fields)
- Used for mutations (with required fields same as in original type)

**Comment by rollymaduk** [comment]
How can I help?

**Comment by asraman9792** [comment]
Sir how i can help with the issue ? Can you share me the details sir

**Comment by wtrocki** [comment]
Check schema plugin that generates single input type

**Comment by craicoverflow** [comment]
```gql
input PostInput {
  id: ID
  createdAt: DateTime
  updatedAt: DateTime
  published: Boolean
  title: String
  content: String
  author: ID #should not be here
  authorId: ID
}
```

Noticed that some incorrect fields are added to the input types. This can be fixed as part of this.

**Comment by wtrocki** [comment]
Closing as duplicate @asraman9792 @rollymaduk Please check linked issue
