### ISSUE TITLE
Replace uses of `getBaseType` with `getNamedType`

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#851]
`getBaseType` in `@graphback/core` does the same thing as [`getNamedType`](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L518)

We should use `getNamedType` from the official reference implementation library and remove `getBaseType`.

**Comment by NVS16** [comment]
Can I work on this?

**Comment by craicoverflow** [comment]
> Can I work on this?

Absolutely!

**Comment by NVS16** [comment]
I have made a preliminary PR. Do I need to make any other changes?
