### ISSUE TITLE
Graphback working with denormalized relationships 

### ISSUE THREAD

**Issue by marckat** [aerogear/graphback#857]
Note: MongoDB specific.

I'm working now on my side project application using graphback. 
I'm using RC5 version and found some issue when working with mongo.

Then modeling the data Graphback requires putting some extra param like `oneToMany` over the object, but sometimes we do not want that. 

Consider my response looks like this:
```json
    "id": "1",
      "title": "JSON:API paints my bikeshed!",
      "body": "The shortest article. Ever.",
      "created": "2015-05-22T14:56:29.000Z",
      "updated": "2015-05-22T14:56:28.000Z"
      // This is causing issue
      "author": {
        "name": "people"
      }
}
```

I still want this to be mapped by graphql types, but those do not have id (and it should not have id as they are literally denormalized inside mongo. Graphback assumes now that everything should be normalized which is going to make so many pointless queries and do not work with the existing data I have for this app.

Especially with mongo I can be sending nested objects and mongo will deal with them without any relationship support. If I do not provide any relationship info graphback should assume that root resolver will send all the required data. 

Without this fixed I do not see how one can use graphback now.
I needed to hack code by adding relationships and  remove relationship resolvers to make things work

**Comment by wtrocki** [comment]
@marckat Although we might need some time to fully understand your use case, I think your suggestion is reasonable and doable. However, our team might need to check how to handle this use case. 

Mainly if we need to apply some extra directive to the types that can exist or be queried as part of the specific type (as we definitely do now want to apply model on those and generate queries). Then how we can actually validate that this use case is desired or that is not the user error. I know that this use case should be possible, but we might simply need to add it as an extra capability to make sure that our API will be clean and easy do understand.

**Comment by wtrocki** [comment]
@marckat We will possibly review this case after finishing the current release. 
Before then we will work on the possible workaround that can be applied here.

**Comment by wtrocki** [comment]
@marckat I have played with this and you can workaround this currently by specifying your own scalars in graphback. Result you getting is not fully typed but JSON scalar can be mapped to many types for example:

```
scalar UserJSON 
scalar DataJSON
```

then in resolvers

```
    UserJSON: JSONResolver,
	DataJSON: JSONResolver
```

**Comment by craicoverflow** [comment]
Going to close this and we can track progress of this issue in https://github.com/aerogear/graphback/issues/1022
