### ISSUE TITLE
Replace knex with direct PG queries for better performance

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#858]
Since we use only postgress (and mongo) we no longer need knex layer. 
For simplicity we can use direct integration with postgress instead. 

Check knex package for more details. 
We should use the same package to do refactor and leave existing knex implementation as deprecated

**Comment by asraman9792** [comment]
how can i help sir can you share me the details ?

**Comment by wtrocki** [comment]
@asraman9792 as in description

> Check knex package for more details
 https://github.com/aerogear/graphback/tree/master/packages/graphback-runtime-knex

**Comment by jaskeerat789** [comment]
@wtrocki

**Comment by wtrocki** [comment]
@jaskeerat789

**Comment by udith-shalinda** [comment]
@wtrocki we might need to face  

> data provider should never be modified database structure

issue like here ("https://github.com/aerogear/graphback/pull/770#discussion_r383156201")

**Comment by wtrocki** [comment]
Done, but we still using knex as it gives much more freedom in terms of mapping queries
