### ISSUE TITLE
Rewrite resolver format

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#9]
Rewrite resolver format to work with typescript source code format.

**Comment by ankitjena** [comment]
## Format
### CRUD operations
```
const resolvers = {
    Query: {
        ....
    }
    Mutations: {
        ....
    }
}
```
### Relations resolvers
TODO

**Comment by wtrocki** [comment]
I will suggest to:
- Rewrite format without relations now 
- Drop some simple apollo template into templates folder
- Test them end to end with Altair or Playground.

This will be a really nice and beneficial work to understand the current schema.
If you have questions about the current schema let me know.

**Comment by wtrocki** [comment]
Awesome!
