### ISSUE TITLE
Consider using custom directives directly in SDL, not directives within comments

### ISSUE THREAD

**Issue by lastmjs** [aerogear/graphback#934]
I'm wondering why Graphback requires special directives within GraphQL SDL comments, like this:

```graphql
"""
@model
"""
type Note {
  id: ID!
}
```
I think it would be preferable to just use custom directives directly, why introduce a non-standard language into the SDL?

```graphql
@model
type Note {
  id: ID!
}
```
I imagine parsing custom directives out of the schema should be even easier when they aren't in comments, by using common GraphQL parsing tools already available.

I think this would simplify things and help new users not to be confused by the extra comment quotes

**Comment by craicoverflow** [comment]
We decided to use [graphql-metadata](https://github.com/aerogear/graphql-metadata) for a few reasons.

Directives are a bit verbose, especially when you need a lot of them. The schema requires a separate definition for each directive. If a field requires three separate directives to describe the field then suddenly it becomes a lot less readable. With annotations we can add them above the field and on multiple lines.

It is really easy to bring your own custom annotations. One of the main reasons we introduced a plugin architecture was to make it super easy to extend and easy for our community to bring their own customisations.

**Comment by wtrocki** [comment]
@craicoverflow Awesome writeoff. We will also add that information to docs. 

Generally in TL;DR - Directives are still used in Graphback but they are designed to be processed at runtime. Annotations/Markers are designed for Plugins/Generation phase and they will be transient to runnable schema. 

We talked a lot about this approach as we really wanted Graphback to work with entire GraphQL ecosystem - if we suddenly start using some of the directives like @connection etc. some of the libraries might already use them etc. 


This screenshot shows how we using directives and annotations on single object:

<img width="872" alt="Screenshot 2020-03-19 at 15 46 36" src="https://user-images.githubusercontent.com/981838/77085865-d683f700-69f8-11ea-8ed9-a6265581bc48.png">

THe main challenge here is problem with remembering those annotations. 
We have done spike for VisualStudio plugin that added support for those annotations for GraphQL schemas. We will also invest more in documentation to build some form of cheat sheet for building models. In some cases like relationships, we can infer some of them already. Hopefully, all of that should make things much simpler. We starting with very verbose model as this is easier to support all use cases and then we will look for some more cleverness for some use cases.

**Comment by wtrocki** [comment]
We do not have this nicely explained in the docs. Target of the issue should be to pull out some of the info here to the documentation

**Comment by craicoverflow** [comment]
Thanks for reporting this. We are focused on using graphql-metadata
