### ISSUE TITLE
Relationships failing when model is not included

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#976]
Error:
```Generation failed: TypeError: Cannot read property 'getTypeName' of undefined```

Model: 
```
""" 
@model
"""
type Task {
  id: ID!
  title: String!
  description: String!
  status: TaskStatus
  assigne: User
}

type User {
  id: ID!
  name: String
}
```

Version 0.11.2

**Comment by craicoverflow** [comment]
Taking this.

**Comment by wtrocki** [comment]
I guess this is validation issue only as model is missing annotation

**Comment by craicoverflow** [comment]
Yes I see it as missing validation.

**Comment by craicoverflow** [comment]
There is a blind-spot in the validation of the data models between validation of the models and validation of relationships.

Try to form a relationship with a non-model type:

```gql
""" 
@model
"""
type Task {
  id: ID!
  title: String!
  description: String!
  """
  @oneToMany field: 'task'
  """
  assigned: User
}

# """
# @model
# """
type User {
  id: ID!
  name: String
}
```

The relationship builder catches the issue and validates this successfully:

> Generation failed: Error: Task.assigned is marked as a relationship field, but type User is missing the @model annotation.

Right now, Graphback only process relationship fields which are explicitly annotated with `@oneToOne/@oneToMany` so `Task.assigned` is not even validated anywhere.

## Approach 1

Adding support for implicit relationships (see https://github.com/aerogear/graphback/issues/936) would subsequently validate the missing `@model` annotation. 

## Approach 2

The most appropriate fix for this right now would be to perform some validation on the models and check if the `assigned: User` type is a model.

This would catch an error early in the plugin.

**Comment by wtrocki** [comment]
Good writing. I will hold of with fixing this as we need to get some approach for the MongoDB nested data that is not relationship that will invalidate most of the stuff we have here. I will suggest book some technical call in this week to cover it

**Comment by wtrocki** [comment]
Temporary fix will be to suppress information and put the right error message

**Comment by craicoverflow** [comment]
Closing in favour of #936

**Comment by craicoverflow** [comment]
ping @machi1990

**Comment by craicoverflow** [comment]
Resolved in https://github.com/aerogear/graphback/issues/1432
