### ISSUE TITLE
`graphback.model` configuration should be glob format

### ISSUE THREAD

**Issue by craicoverflow** [aerogear/graphback#977]
If a user places their data model in `./src/datamodel.graphql` they will need to specify the following config:

```yml
graphback:
  model: ./src
```

This will process all `.graphql` files in all subdirectories of `src`. Users may not want this and may have specific reasons to exclude certain files from their generated schema.

This also means that the generated schema is also processed as an input model and custom queries, mutations etc from data model are overwritten by ones in generated schema. This is a :bug: 

It would be really nice if the model config is a glob, so it could be like this:

```yml
graphback:
  model: ./src/*.graphql
```

**Comment by wtrocki** [comment]
It could be:

- Folder
- Glob
- Array

Underlying implementation has simple means to do all of them in the single line of the code

**Comment by craicoverflow** [comment]
> It could be:
> 
>     * Folder
> 
>     * Glob
> 
>     * Array
> 
> 
> Underlying implementation has simple means to do all of them in the single line of the code

Absolutely - if we can cater for everyone's preference it will be even better.
